/**
 * `assignee init` command — optional project-level configuration setup.
 *
 * Auto-detects AWS credentials and region, prompts for confirmation,
 * and creates `.assignee/config.yaml`. The command is entirely optional;
 * all CLI commands work without it by using the standard AWS credential chain.
 *
 * @see Story 18.1, ADR-010
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { Command } from "commander";
import * as clack from "@clack/prompts";
import { stringify as yamlStringify } from "yaml";
import { CommandName, CommandDescription } from "../constants/commands.js";
import { ProcessExitCode } from "../constants/errors.js";
import {
  detectCredentials,
  detectRegion,
} from "../services/credential-detector.js";

/** Directory name for assignee project config. */
const CONFIG_DIR = ".assignee";

/** Config file name inside the config directory. */
const CONFIG_FILE = "config.yaml";

/** Environment options for the interactive prompt. */
const ENVIRONMENT_OPTIONS = [
  { value: "development", label: "development" },
  { value: "staging", label: "staging" },
  { value: "production", label: "production" },
] as const;

/**
 * Shape of the `.assignee/config.yaml` project config file.
 * Must be compatible with the user-config-loader.ts schema (Story 7.2).
 */
export interface ProjectConfig {
  region: string;
  profile: string;
  tags: {
    "managed-by": string;
    environment: string;
  };
}

export const initCommand = new Command(CommandName.INIT)
  .description(CommandDescription.INIT)
  .action(async () => {
    clack.intro("Assignee.ai — Project Initialization");

    // ── Credential detection ──────────────────────────────────────────
    const credentialResult = await detectCredentials();

    if (!credentialResult.detected) {
      clack.log.error(
        credentialResult.reason ??
          "No AWS credentials found. Configure credentials via:\n" +
            "  1) AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY environment variables\n" +
            "  2) ~/.aws/credentials file\n" +
            "  3) AWS SSO login (aws sso login)",
      );
      process.exit(ProcessExitCode.GENERIC_ERROR);
    }

    clack.log.success(
      `AWS credentials detected (source: ${credentialResult.source})`,
    );

    // ── Region detection ──────────────────────────────────────────────
    const regionResult = await detectRegion();

    // ── Check for existing config ─────────────────────────────────────
    const configDir = path.resolve(process.cwd(), CONFIG_DIR);
    const configPath = path.join(configDir, CONFIG_FILE);

    try {
      await fs.access(configPath);
      // Config exists — prompt for overwrite
      const overwrite = await clack.confirm({
        message: "Config already exists. Overwrite?",
        initialValue: false,
      });

      if (clack.isCancel(overwrite) || overwrite === false) {
        clack.outro("Keeping existing configuration.");
        return;
      }
    } catch {
      // Config does not exist — proceed
    }

    // ── Interactive prompts ───────────────────────────────────────────
    const region = await clack.text({
      message: "AWS Region",
      initialValue: regionResult.region ?? "us-east-1",
    });

    if (clack.isCancel(region)) {
      clack.outro("Initialization cancelled.");
      return;
    }

    const profile = await clack.text({
      message: "AWS Profile",
      initialValue: credentialResult.profile ?? "default",
    });

    if (clack.isCancel(profile)) {
      clack.outro("Initialization cancelled.");
      return;
    }

    const environment = await clack.select({
      message: "Environment",
      options: [...ENVIRONMENT_OPTIONS],
    });

    if (clack.isCancel(environment)) {
      clack.outro("Initialization cancelled.");
      return;
    }

    // ── Write config file ─────────────────────────────────────────────
    const config: ProjectConfig = {
      region: region as string,
      profile: profile as string,
      tags: {
        "managed-by": "assignee-ai",
        environment: environment as string,
      },
    };

    await fs.mkdir(configDir, { recursive: true });

    const yamlContent =
      "# Generated by assignee init\n" + yamlStringify(config);
    await fs.writeFile(configPath, yamlContent, "utf-8");

    // ── Success output ────────────────────────────────────────────────
    const profileNote =
      config.profile !== "default" ? ` with profile ${config.profile}` : "";
    clack.outro(
      `Initialized assignee.ai for region ${config.region}${profileNote}. Run \`assignee plan\` to get started.`,
    );
  });
