/**
 * Tests for `assignee init` command.
 *
 * @see Story 18.1, AC #9
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import { parse as parseYaml } from "yaml";

// Mock @clack/prompts before importing the command
vi.mock("@clack/prompts", () => ({
  intro: vi.fn(),
  outro: vi.fn(),
  log: {
    success: vi.fn(),
    error: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
  },
  text: vi.fn(),
  select: vi.fn(),
  confirm: vi.fn(),
  isCancel: vi.fn().mockReturnValue(false),
  autocomplete: vi.fn(),
  autocompleteMultiselect: vi.fn(),
}));

// Mock credential-detector
vi.mock("../services/credential-detector.js", () => ({
  detectCredentials: vi.fn(),
  detectRegion: vi.fn(),
}));

// Mock user-config-loader for --global tests
vi.mock("../config/user-config-loader.js", () => ({
  resolveConfigPath: vi.fn(),
}));

// Mock process.exit to prevent test from terminating
const mockExit = vi
  .spyOn(process, "exit")
  .mockImplementation((() => {}) as never);

import * as clack from "@clack/prompts";
import {
  detectCredentials,
  detectRegion,
} from "../services/credential-detector.js";
import type {
  CredentialDetectionResult,
  RegionDetectionResult,
} from "../services/credential-detector.js";
import { resolveConfigPath } from "../config/user-config-loader.js";

// ── Helpers ──────────────────────────────────────────────────────────────

let tmpDir: string;
let originalCwd: string;

async function runInitAction(args: string[] = ["node", "init"]): Promise<void> {
  // Dynamically import to get fresh module with mocks
  const { initCommand } = await import("./init.js");
  // Use parseAsync to trigger the action
  await initCommand.parseAsync(args);
}

async function runInitGlobal(): Promise<void> {
  await runInitAction(["node", "init", "--global"]);
}

function mockCredentials(result: CredentialDetectionResult): void {
  vi.mocked(detectCredentials).mockResolvedValue(result);
}

function mockRegion(result: RegionDetectionResult): void {
  vi.mocked(detectRegion).mockResolvedValue(result);
}

function mockPrompts(opts: {
  region?: string;
  profile?: string;
  environment?: string;
}): void {
  vi.mocked(clack.text)
    .mockResolvedValueOnce(opts.region ?? "us-east-1")
    .mockResolvedValueOnce(opts.profile ?? "default");
  vi.mocked(clack.select).mockResolvedValueOnce(
    opts.environment ?? "development",
  );
}

// ── Tests ────────────────────────────────────────────────────────────────

describe("assignee init command", () => {
  beforeEach(async () => {
    vi.clearAllMocks();
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "init-test-"));
    originalCwd = process.cwd();
    process.chdir(tmpDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  it("creates .assignee/config.yaml with valid credentials", async () => {
    mockCredentials({
      detected: true,
      source: "env",
      profile: "default",
    });
    mockRegion({ region: "eu-west-1" });
    mockPrompts({
      region: "eu-west-1",
      profile: "default",
      environment: "development",
    });

    await runInitAction();

    // Verify config file was created
    const configPath = path.join(tmpDir, ".assignee", "config.yaml");
    const content = await fs.readFile(configPath, "utf-8");
    const parsed = parseYaml(content) as Record<string, unknown>;

    expect(parsed["region"]).toBe("eu-west-1");
    expect(parsed["profile"]).toBe("default");
    expect(parsed["tags"]).toEqual({
      "managed-by": "assignee-ai",
      environment: "development",
    });
  });

  it("config file content matches expected YAML structure", async () => {
    mockCredentials({
      detected: true,
      source: "file",
      profile: "staging",
    });
    mockRegion({ region: "us-west-2" });
    mockPrompts({
      region: "us-west-2",
      profile: "staging",
      environment: "production",
    });

    await runInitAction();

    const configPath = path.join(tmpDir, ".assignee", "config.yaml");
    const content = await fs.readFile(configPath, "utf-8");

    // Should have the comment header
    expect(content).toContain("# Generated by assignee init");

    const parsed = parseYaml(content) as Record<string, unknown>;
    expect(parsed).toEqual({
      region: "us-west-2",
      profile: "staging",
      tags: {
        "managed-by": "assignee-ai",
        environment: "production",
      },
      defaults: {
        region: "us-west-2",
        tags: {
          "managed-by": "assignee-ai",
          environment: "production",
        },
      },
      preferences: {
        auto_fix: "ask",
      },
    });
  });

  it("prompts for overwrite when config already exists", async () => {
    // Create existing config
    const configDir = path.join(tmpDir, ".assignee");
    await fs.mkdir(configDir, { recursive: true });
    await fs.writeFile(
      path.join(configDir, "config.yaml"),
      "region: old-region\n",
    );

    mockCredentials({
      detected: true,
      source: "env",
      profile: "default",
    });
    mockRegion({ region: "us-east-1" });

    // User declines overwrite
    vi.mocked(clack.confirm).mockResolvedValueOnce(false);

    await runInitAction();

    // Verify confirm was called
    expect(clack.confirm).toHaveBeenCalledWith(
      expect.objectContaining({
        message: "Config already exists. Overwrite?",
      }),
    );

    // Verify outro message
    expect(clack.outro).toHaveBeenCalledWith("Keeping existing configuration.");

    // Verify original config was NOT overwritten
    const content = await fs.readFile(
      path.join(configDir, "config.yaml"),
      "utf-8",
    );
    expect(content).toBe("region: old-region\n");
  });

  it("overwrites config when user confirms", async () => {
    // Create existing config
    const configDir = path.join(tmpDir, ".assignee");
    await fs.mkdir(configDir, { recursive: true });
    await fs.writeFile(
      path.join(configDir, "config.yaml"),
      "region: old-region\n",
    );

    mockCredentials({
      detected: true,
      source: "env",
      profile: "default",
    });
    mockRegion({ region: "us-east-1" });

    // User confirms overwrite
    vi.mocked(clack.confirm).mockResolvedValueOnce(true);
    mockPrompts({
      region: "us-east-1",
      profile: "default",
      environment: "development",
    });

    await runInitAction();

    // Verify config was overwritten with new content
    const content = await fs.readFile(
      path.join(configDir, "config.yaml"),
      "utf-8",
    );
    expect(content).toContain("us-east-1");
    expect(content).not.toContain("old-region");
  });

  it("succeeds without AWS credentials and prints a next-step hint", async () => {
    // Scrub all credential env vars so detectAvailableRoles sees nothing.
    const scrubbed = [
      "ASSIGNEE_OPERATOR_ACCESS_KEY_ID",
      "ASSIGNEE_OPERATOR_SECRET_ACCESS_KEY",
      "ASSIGNEE_READER_ACCESS_KEY_ID",
      "ASSIGNEE_READER_SECRET_ACCESS_KEY",
      "ASSIGNEE_AUDITOR_ACCESS_KEY_ID",
      "ASSIGNEE_AUDITOR_SECRET_ACCESS_KEY",
    ];
    const saved: Record<string, string | undefined> = {};
    for (const key of scrubbed) {
      saved[key] = process.env[key];
      delete process.env[key];
    }

    try {
      mockCredentials({
        detected: false,
        reason:
          "No AWS credentials found. Configure credentials via:\n" +
          "  1) ASSIGNEE_OPERATOR_ACCESS_KEY_ID / ASSIGNEE_OPERATOR_SECRET_ACCESS_KEY environment variables\n" +
          "  2) ~/.aws/credentials file\n" +
          "  3) AWS SSO login (aws sso login)",
      });
      mockRegion({ region: "us-east-1" });
      mockPrompts({
        region: "us-east-1",
        profile: "default",
        environment: "development",
      });

      await runInitAction();

      // Non-fatal: warn + next-step info hint emitted.
      expect(clack.log.warn).toHaveBeenCalledWith(
        expect.stringContaining("No AWS credentials detected"),
      );
      const infoCalls = vi
        .mocked(clack.log.info)
        .mock.calls.map((c) => String(c[0]));
      expect(infoCalls.some((m) => m.includes("assignee setup"))).toBe(true);
      expect(
        infoCalls.some((m) => m.includes("Assignee roles available: none")),
      ).toBe(true);

      // Config file is still written.
      const configPath = path.join(tmpDir, ".assignee", "config.yaml");
      const content = await fs.readFile(configPath, "utf-8");
      expect(content).toContain("us-east-1");
      expect(clack.outro).toHaveBeenCalledWith(
        expect.stringContaining("Initialized assignee.ai for region us-east-1"),
      );
    } finally {
      for (const key of scrubbed) {
        if (saved[key] === undefined) {
          delete process.env[key];
        } else {
          process.env[key] = saved[key];
        }
      }
    }
  });

  it("succeeds with reader-only env credentials and reports reader available", async () => {
    const scrubbed = [
      "ASSIGNEE_OPERATOR_ACCESS_KEY_ID",
      "ASSIGNEE_OPERATOR_SECRET_ACCESS_KEY",
      "ASSIGNEE_READER_ACCESS_KEY_ID",
      "ASSIGNEE_READER_SECRET_ACCESS_KEY",
      "ASSIGNEE_AUDITOR_ACCESS_KEY_ID",
      "ASSIGNEE_AUDITOR_SECRET_ACCESS_KEY",
    ];
    const saved: Record<string, string | undefined> = {};
    for (const key of scrubbed) {
      saved[key] = process.env[key];
      delete process.env[key];
    }
    // Real-shaped AWS access key id (AKIA + 16 alphanumerics) and secret.
    process.env["ASSIGNEE_READER_ACCESS_KEY_ID"] = "AKIAIOSFODNN7EXAMPLE";
    process.env["ASSIGNEE_READER_SECRET_ACCESS_KEY"] =
      "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY";

    try {
      mockCredentials({
        detected: false,
        reason: "No operator credentials found",
      });
      mockRegion({ region: "us-west-2" });
      mockPrompts({
        region: "us-west-2",
        profile: "default",
        environment: "development",
      });

      await runInitAction();

      const infoCalls = vi
        .mocked(clack.log.info)
        .mock.calls.map((c) => String(c[0]));
      expect(
        infoCalls.some((m) => m === "Assignee roles available: reader"),
      ).toBe(true);

      const configPath = path.join(tmpDir, ".assignee", "config.yaml");
      const content = await fs.readFile(configPath, "utf-8");
      expect(content).toContain("us-west-2");
    } finally {
      for (const key of scrubbed) {
        if (saved[key] === undefined) {
          delete process.env[key];
        } else {
          process.env[key] = saved[key];
        }
      }
    }
  });

  it("reports all 3 roles available when operator, reader, and auditor envs are set", async () => {
    const scrubbed = [
      "ASSIGNEE_OPERATOR_ACCESS_KEY_ID",
      "ASSIGNEE_OPERATOR_SECRET_ACCESS_KEY",
      "ASSIGNEE_READER_ACCESS_KEY_ID",
      "ASSIGNEE_READER_SECRET_ACCESS_KEY",
      "ASSIGNEE_AUDITOR_ACCESS_KEY_ID",
      "ASSIGNEE_AUDITOR_SECRET_ACCESS_KEY",
    ];
    const saved: Record<string, string | undefined> = {};
    for (const key of scrubbed) {
      saved[key] = process.env[key];
      delete process.env[key];
    }
    process.env["ASSIGNEE_OPERATOR_ACCESS_KEY_ID"] = "AKIAIOSFODNN7OPERATOR";
    process.env["ASSIGNEE_OPERATOR_SECRET_ACCESS_KEY"] =
      "wJalrXUtnFEMI/K7MDENG/bPxRfiCYOPERATORKEY";
    process.env["ASSIGNEE_READER_ACCESS_KEY_ID"] = "AKIAIOSFODNN7READER00";
    process.env["ASSIGNEE_READER_SECRET_ACCESS_KEY"] =
      "wJalrXUtnFEMI/K7MDENG/bPxRfiCYREADERKEY00";
    process.env["ASSIGNEE_AUDITOR_ACCESS_KEY_ID"] = "AKIAIOSFODNN7AUDITOR0";
    process.env["ASSIGNEE_AUDITOR_SECRET_ACCESS_KEY"] =
      "wJalrXUtnFEMI/K7MDENG/bPxRfiCYAUDITORKEY";

    try {
      mockCredentials({
        detected: true,
        source: "env",
        profile: "default",
      });
      mockRegion({ region: "us-east-1" });
      mockPrompts({
        region: "us-east-1",
        profile: "default",
        environment: "production",
      });

      await runInitAction();

      expect(clack.log.success).toHaveBeenCalledWith(
        expect.stringContaining("AWS credentials detected"),
      );
      const infoCalls = vi
        .mocked(clack.log.info)
        .mock.calls.map((c) => String(c[0]));
      expect(
        infoCalls.some(
          (m) => m === "Assignee roles available: operator, reader, auditor",
        ),
      ).toBe(true);

      const configPath = path.join(tmpDir, ".assignee", "config.yaml");
      const content = await fs.readFile(configPath, "utf-8");
      expect(content).toContain("us-east-1");
    } finally {
      for (const key of scrubbed) {
        if (saved[key] === undefined) {
          delete process.env[key];
        } else {
          process.env[key] = saved[key];
        }
      }
    }
  });

  it("shows success summary with region and profile", async () => {
    mockCredentials({
      detected: true,
      source: "env",
      profile: "my-profile",
    });
    mockRegion({ region: "ap-southeast-1" });
    mockPrompts({
      region: "ap-southeast-1",
      profile: "my-profile",
      environment: "staging",
    });

    await runInitAction();

    expect(clack.outro).toHaveBeenCalledWith(
      expect.stringContaining(
        "Initialized assignee.ai for region ap-southeast-1",
      ),
    );
    expect(clack.outro).toHaveBeenCalledWith(
      expect.stringContaining("with profile my-profile"),
    );
    expect(clack.outro).toHaveBeenCalledWith(
      expect.stringContaining("assignee plan"),
    );
  });

  it("does not show profile note for default profile", async () => {
    mockCredentials({
      detected: true,
      source: "env",
      profile: "default",
    });
    mockRegion({ region: "us-east-1" });
    mockPrompts({
      region: "us-east-1",
      profile: "default",
      environment: "development",
    });

    await runInitAction();

    const outroCall = vi.mocked(clack.outro).mock.calls[0]?.[0] as string;
    expect(outroCall).not.toContain("with profile");
  });
});

describe("assignee init --global", () => {
  let globalConfigDir: string;

  beforeEach(async () => {
    vi.clearAllMocks();
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "init-global-test-"));
    globalConfigDir = path.join(tmpDir, ".config", "assignee");
    originalCwd = process.cwd();
    process.chdir(tmpDir);

    // Mock resolveConfigPath to use tmpDir
    vi.mocked(resolveConfigPath).mockReturnValue(
      path.join(globalConfigDir, "config.yaml"),
    );
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  it("--global flag triggers global config wizard and writes AssigneeConfig YAML", async () => {
    // Mock the global wizard prompts in order:
    // 1. region (text)
    // 2. tag entry 1 (text)
    // 3. tag entry empty = done (text)
    // 4. naming prefix (text)
    // 5. auto_fix (select)
    // 6. output_format (select)
    // 7. verbosity (select)
    vi.mocked(clack.text)
      .mockResolvedValueOnce("us-west-2") // region
      .mockResolvedValueOnce("team=backend") // tag 1
      .mockResolvedValueOnce("") // done with tags
      .mockResolvedValueOnce("myco-"); // naming prefix

    vi.mocked(clack.select)
      .mockResolvedValueOnce("ask") // auto_fix
      .mockResolvedValueOnce("table") // output_format
      .mockResolvedValueOnce("normal"); // verbosity

    await runInitGlobal();

    // Verify config file was created
    const configPath = path.join(globalConfigDir, "config.yaml");
    const content = await fs.readFile(configPath, "utf-8");
    expect(content).toContain("# Generated by assignee init --global");

    const parsed = parseYaml(content) as Record<string, unknown>;
    const defaults = parsed["defaults"] as Record<string, unknown>;
    expect(defaults["region"]).toBe("us-west-2");
    expect(defaults["tags"]).toEqual({ team: "backend" });
    expect((defaults["naming"] as Record<string, unknown>)["prefix"]).toBe(
      "myco-",
    );

    const prefs = parsed["preferences"] as Record<string, unknown>;
    expect(prefs["auto_fix"]).toBe("ask");
    expect(prefs["output_format"]).toBe("table");
    expect(prefs["verbosity"]).toBe("normal");
  });

  it("auto_fix defaults to 'ask' when user presses Enter", async () => {
    vi.mocked(clack.text)
      .mockResolvedValueOnce("us-east-1") // region
      .mockResolvedValueOnce("") // done with tags
      .mockResolvedValueOnce(""); // no prefix

    vi.mocked(clack.select)
      .mockResolvedValueOnce("ask") // auto_fix — default
      .mockResolvedValueOnce("table")
      .mockResolvedValueOnce("normal");

    await runInitGlobal();

    const content = await fs.readFile(
      path.join(globalConfigDir, "config.yaml"),
      "utf-8",
    );
    const parsed = parseYaml(content) as Record<string, unknown>;
    const prefs = parsed["preferences"] as Record<string, unknown>;
    expect(prefs["auto_fix"]).toBe("ask");
  });

  it("prompts for overwrite when global config already exists", async () => {
    // Create existing global config
    await fs.mkdir(globalConfigDir, { recursive: true });
    await fs.writeFile(
      path.join(globalConfigDir, "config.yaml"),
      "defaults:\n  region: old-region\n",
    );

    // User declines overwrite
    vi.mocked(clack.confirm).mockResolvedValueOnce(false);

    await runInitGlobal();

    expect(clack.confirm).toHaveBeenCalledWith(
      expect.objectContaining({
        message: "Global config already exists. Overwrite?",
      }),
    );
    expect(clack.outro).toHaveBeenCalledWith("Keeping existing configuration.");
  });

  // Note: "no --global flag" behavior is fully tested in the "assignee init command" describe block above.

  // L-A9 regression: malformed tag entries (`=value`, `key=`, no `=`) used to
  // be silently dropped. Users had no way to know their input was rejected.
  // The fix surfaces a clack.log.warn for each malformed entry.
  it("warns when tag entry has no '=' separator", async () => {
    vi.mocked(clack.text)
      .mockResolvedValueOnce("us-east-1") // region
      .mockResolvedValueOnce("environmentdev") // malformed: no `=`
      .mockResolvedValueOnce("") // done with tags
      .mockResolvedValueOnce(""); // no prefix
    vi.mocked(clack.select)
      .mockResolvedValueOnce("ask")
      .mockResolvedValueOnce("table")
      .mockResolvedValueOnce("normal");

    await runInitGlobal();

    expect(clack.log.warn).toHaveBeenCalledWith(
      expect.stringContaining('Ignored tag "environmentdev"'),
    );

    // The config still wrote successfully without the bad tag.
    const content = await fs.readFile(
      path.join(globalConfigDir, "config.yaml"),
      "utf-8",
    );
    const parsed = parseYaml(content) as Record<string, unknown>;
    const defaults = parsed["defaults"] as Record<string, unknown> | undefined;
    expect(defaults?.["tags"]).toBeUndefined();
  });

  it("warns when tag entry starts with '=' (empty key)", async () => {
    vi.mocked(clack.text)
      .mockResolvedValueOnce("us-east-1")
      .mockResolvedValueOnce("=lonely-value")
      .mockResolvedValueOnce("")
      .mockResolvedValueOnce("");
    vi.mocked(clack.select)
      .mockResolvedValueOnce("ask")
      .mockResolvedValueOnce("table")
      .mockResolvedValueOnce("normal");

    await runInitGlobal();

    expect(clack.log.warn).toHaveBeenCalledWith(
      expect.stringContaining('Ignored tag "=lonely-value"'),
    );
  });

  it("warns when tag entry has empty value (`key=`)", async () => {
    vi.mocked(clack.text)
      .mockResolvedValueOnce("us-east-1")
      .mockResolvedValueOnce("environment=") // empty value
      .mockResolvedValueOnce("")
      .mockResolvedValueOnce("");
    vi.mocked(clack.select)
      .mockResolvedValueOnce("ask")
      .mockResolvedValueOnce("table")
      .mockResolvedValueOnce("normal");

    await runInitGlobal();

    expect(clack.log.warn).toHaveBeenCalledWith(
      expect.stringContaining('Ignored tag "environment="'),
    );
  });

  it("accepts a valid tag and does NOT warn", async () => {
    vi.mocked(clack.text)
      .mockResolvedValueOnce("us-east-1")
      .mockResolvedValueOnce("environment=production")
      .mockResolvedValueOnce("")
      .mockResolvedValueOnce("");
    vi.mocked(clack.select)
      .mockResolvedValueOnce("ask")
      .mockResolvedValueOnce("table")
      .mockResolvedValueOnce("normal");

    await runInitGlobal();

    // No "Ignored tag" warnings — only valid entry was supplied.
    const ignoredWarnings = vi
      .mocked(clack.log.warn)
      .mock.calls.filter((c) => String(c[0] ?? "").includes("Ignored tag"));
    expect(ignoredWarnings).toHaveLength(0);

    const content = await fs.readFile(
      path.join(globalConfigDir, "config.yaml"),
      "utf-8",
    );
    const parsed = parseYaml(content) as Record<string, unknown>;
    const defaults = parsed["defaults"] as Record<string, unknown>;
    expect(defaults["tags"]).toEqual({ environment: "production" });
  });
});

// ── M-S8: detectAvailableRoles delegates to @assignee/core ─────────────────

describe("detectAvailableRoles (M-S8)", () => {
  const ALL_VARS = [
    "ASSIGNEE_OPERATOR_ACCESS_KEY_ID",
    "ASSIGNEE_OPERATOR_SECRET_ACCESS_KEY",
    "ASSIGNEE_READER_ACCESS_KEY_ID",
    "ASSIGNEE_READER_SECRET_ACCESS_KEY",
    "ASSIGNEE_AUDITOR_ACCESS_KEY_ID",
    "ASSIGNEE_AUDITOR_SECRET_ACCESS_KEY",
  ];

  it("returns each role only when its access+secret pair is set non-empty", async () => {
    const env: NodeJS.ProcessEnv = {};
    for (const v of ALL_VARS) env[v] = undefined;
    env["ASSIGNEE_OPERATOR_ACCESS_KEY_ID"] = "AKIAIOSFODNN7EXAMPLE";
    env["ASSIGNEE_OPERATOR_SECRET_ACCESS_KEY"] =
      "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY";
    env["ASSIGNEE_AUDITOR_ACCESS_KEY_ID"] = "AKIAJOHNDOECODE0EXMPL";
    env["ASSIGNEE_AUDITOR_SECRET_ACCESS_KEY"] =
      "auditorSecretValueRealistic12345678901234";

    const { detectAvailableRoles } = await import("./init.js");
    expect(detectAvailableRoles(env)).toEqual(["operator", "auditor"]);
  });

  it("rejects whitespace-only access keys", async () => {
    const env: NodeJS.ProcessEnv = {};
    for (const v of ALL_VARS) env[v] = undefined;
    env["ASSIGNEE_READER_ACCESS_KEY_ID"] = "   ";
    env["ASSIGNEE_READER_SECRET_ACCESS_KEY"] =
      "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY";

    const { detectAvailableRoles } = await import("./init.js");
    expect(detectAvailableRoles(env)).toEqual([]);
  });
});
