/**
 * Tests for `assignee init` command.
 *
 * @see Story 18.1, AC #9
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import { parse as parseYaml } from "yaml";

// Mock @clack/prompts before importing the command
vi.mock("@clack/prompts", () => ({
  intro: vi.fn(),
  outro: vi.fn(),
  log: {
    success: vi.fn(),
    error: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
  },
  text: vi.fn(),
  select: vi.fn(),
  confirm: vi.fn(),
  isCancel: vi.fn().mockReturnValue(false),
}));

// Mock credential-detector
vi.mock("../services/credential-detector.js", () => ({
  detectCredentials: vi.fn(),
  detectRegion: vi.fn(),
}));

// Mock process.exit to prevent test from terminating
const mockExit = vi
  .spyOn(process, "exit")
  .mockImplementation((() => {}) as never);

import * as clack from "@clack/prompts";
import {
  detectCredentials,
  detectRegion,
} from "../services/credential-detector.js";
import type {
  CredentialDetectionResult,
  RegionDetectionResult,
} from "../services/credential-detector.js";

// ── Helpers ──────────────────────────────────────────────────────────────

let tmpDir: string;
let originalCwd: string;

async function runInitAction(): Promise<void> {
  // Dynamically import to get fresh module with mocks
  const { initCommand } = await import("./init.js");
  // Extract and call the action handler directly
  const actionHandler = (
    initCommand as unknown as { _actionHandler: () => Promise<void> }
  )._actionHandler;

  // Commander stores the action in _actionHandler; invoke it
  // Use parseAsync to trigger the action
  await initCommand.parseAsync(["node", "init"]);
}

function mockCredentials(result: CredentialDetectionResult): void {
  vi.mocked(detectCredentials).mockResolvedValue(result);
}

function mockRegion(result: RegionDetectionResult): void {
  vi.mocked(detectRegion).mockResolvedValue(result);
}

function mockPrompts(opts: {
  region?: string;
  profile?: string;
  environment?: string;
}): void {
  vi.mocked(clack.text)
    .mockResolvedValueOnce(opts.region ?? "us-east-1")
    .mockResolvedValueOnce(opts.profile ?? "default");
  vi.mocked(clack.select).mockResolvedValueOnce(
    opts.environment ?? "development",
  );
}

// ── Tests ────────────────────────────────────────────────────────────────

describe("assignee init command", () => {
  beforeEach(async () => {
    vi.clearAllMocks();
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "init-test-"));
    originalCwd = process.cwd();
    process.chdir(tmpDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  it("creates .assignee/config.yaml with valid credentials", async () => {
    mockCredentials({
      detected: true,
      source: "env",
      profile: "default",
    });
    mockRegion({ region: "eu-west-1" });
    mockPrompts({
      region: "eu-west-1",
      profile: "default",
      environment: "development",
    });

    await runInitAction();

    // Verify config file was created
    const configPath = path.join(tmpDir, ".assignee", "config.yaml");
    const content = await fs.readFile(configPath, "utf-8");
    const parsed = parseYaml(content) as Record<string, unknown>;

    expect(parsed["region"]).toBe("eu-west-1");
    expect(parsed["profile"]).toBe("default");
    expect(parsed["tags"]).toEqual({
      "managed-by": "assignee-ai",
      environment: "development",
    });
  });

  it("config file content matches expected YAML structure", async () => {
    mockCredentials({
      detected: true,
      source: "file",
      profile: "staging",
    });
    mockRegion({ region: "us-west-2" });
    mockPrompts({
      region: "us-west-2",
      profile: "staging",
      environment: "production",
    });

    await runInitAction();

    const configPath = path.join(tmpDir, ".assignee", "config.yaml");
    const content = await fs.readFile(configPath, "utf-8");

    // Should have the comment header
    expect(content).toContain("# Generated by assignee init");

    const parsed = parseYaml(content) as Record<string, unknown>;
    expect(parsed).toEqual({
      region: "us-west-2",
      profile: "staging",
      tags: {
        "managed-by": "assignee-ai",
        environment: "production",
      },
    });
  });

  it("prompts for overwrite when config already exists", async () => {
    // Create existing config
    const configDir = path.join(tmpDir, ".assignee");
    await fs.mkdir(configDir, { recursive: true });
    await fs.writeFile(
      path.join(configDir, "config.yaml"),
      "region: old-region\n",
    );

    mockCredentials({
      detected: true,
      source: "env",
      profile: "default",
    });
    mockRegion({ region: "us-east-1" });

    // User declines overwrite
    vi.mocked(clack.confirm).mockResolvedValueOnce(false);

    await runInitAction();

    // Verify confirm was called
    expect(clack.confirm).toHaveBeenCalledWith(
      expect.objectContaining({
        message: "Config already exists. Overwrite?",
      }),
    );

    // Verify outro message
    expect(clack.outro).toHaveBeenCalledWith("Keeping existing configuration.");

    // Verify original config was NOT overwritten
    const content = await fs.readFile(
      path.join(configDir, "config.yaml"),
      "utf-8",
    );
    expect(content).toBe("region: old-region\n");
  });

  it("overwrites config when user confirms", async () => {
    // Create existing config
    const configDir = path.join(tmpDir, ".assignee");
    await fs.mkdir(configDir, { recursive: true });
    await fs.writeFile(
      path.join(configDir, "config.yaml"),
      "region: old-region\n",
    );

    mockCredentials({
      detected: true,
      source: "env",
      profile: "default",
    });
    mockRegion({ region: "us-east-1" });

    // User confirms overwrite
    vi.mocked(clack.confirm).mockResolvedValueOnce(true);
    mockPrompts({
      region: "us-east-1",
      profile: "default",
      environment: "development",
    });

    await runInitAction();

    // Verify config was overwritten with new content
    const content = await fs.readFile(
      path.join(configDir, "config.yaml"),
      "utf-8",
    );
    expect(content).toContain("us-east-1");
    expect(content).not.toContain("old-region");
  });

  it("produces actionable error when no credentials are found", async () => {
    mockCredentials({
      detected: false,
      reason:
        "No AWS credentials found. Configure credentials via:\n" +
        "  1) AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY environment variables\n" +
        "  2) ~/.aws/credentials file\n" +
        "  3) AWS SSO login (aws sso login)",
    });

    await runInitAction();

    expect(clack.log.error).toHaveBeenCalledWith(
      expect.stringContaining("No AWS credentials found"),
    );
    expect(mockExit).toHaveBeenCalledWith(1);
  });

  it("shows success summary with region and profile", async () => {
    mockCredentials({
      detected: true,
      source: "env",
      profile: "my-profile",
    });
    mockRegion({ region: "ap-southeast-1" });
    mockPrompts({
      region: "ap-southeast-1",
      profile: "my-profile",
      environment: "staging",
    });

    await runInitAction();

    expect(clack.outro).toHaveBeenCalledWith(
      expect.stringContaining(
        "Initialized assignee.ai for region ap-southeast-1",
      ),
    );
    expect(clack.outro).toHaveBeenCalledWith(
      expect.stringContaining("with profile my-profile"),
    );
    expect(clack.outro).toHaveBeenCalledWith(
      expect.stringContaining("assignee plan"),
    );
  });

  it("does not show profile note for default profile", async () => {
    mockCredentials({
      detected: true,
      source: "env",
      profile: "default",
    });
    mockRegion({ region: "us-east-1" });
    mockPrompts({
      region: "us-east-1",
      profile: "default",
      environment: "development",
    });

    await runInitAction();

    const outroCall = vi.mocked(clack.outro).mock.calls[0]?.[0] as string;
    expect(outroCall).not.toContain("with profile");
  });
});
