// Post a commit comment with apply results after merge.

const COMMENT_MARKER = '<!-- assignee-apply-comment -->';

/**
 * Format apply result into a readable Markdown comment body.
 * @param {object} params
 * @param {string} params.applyResult - 'success' or 'failed'
 * @param {string} params.resourceArn - ARN of provisioned resource (may be empty)
 * @param {string} params.rawOutput - Raw CLI output
 * @returns {string} Formatted Markdown body
 */
function formatApplyComment({ applyResult, resourceArn, rawOutput }) {
  const isSuccess = applyResult === 'success';
  const statusIcon = isSuccess ? '✅' : '❌';
  const statusText = isSuccess ? 'Succeeded' : 'Failed';

  const lines = [
    COMMENT_MARKER,
    `## Assignee Apply ${statusIcon}`,
    '',
    `**Status:** ${statusText}`,
  ];

  if (resourceArn) {
    lines.push(`**Resource ARN:** \`${resourceArn}\``);
  }

  // Try to extract cost from raw output
  if (rawOutput) {
    let parsedOutput;
    try {
      parsedOutput = JSON.parse(rawOutput);
    } catch {
      // Not JSON, that's fine
    }

    if (parsedOutput) {
      const cost = parsedOutput.costEstimate || parsedOutput.cost;
      if (cost) {
        const monthly = typeof cost === 'object' ? (cost.monthly || cost.monthlyEstimate || 'N/A') : cost;
        lines.push(`**Estimated Monthly Cost:** ${monthly}`);
      }
    }

    if (!isSuccess) {
      lines.push('');
      lines.push('### Error Details');
      lines.push('');
      lines.push('```');
      lines.push(rawOutput.substring(0, 3000)); // Truncate very long output
      lines.push('```');
    }
  }

  lines.push('');
  lines.push('_Generated by [assignee.ai](https://github.com/SergSlon/assignee-ai) GitHub Action_');

  return lines.join('\n');
}

/**
 * Main entry point for the post-comment action step.
 * Posts a commit comment on the merge SHA.
 * @param {object} params
 * @param {object} params.github - GitHub API client
 * @param {object} params.context - GitHub Actions context
 * @param {string} params.applyResult - 'success' or 'failed'
 * @param {string} params.resourceArn - ARN of provisioned resource
 * @param {string} params.rawOutput - Raw CLI output
 */
async function postApplyComment({ github, context, applyResult, resourceArn, rawOutput }) {
  const body = formatApplyComment({ applyResult, resourceArn, rawOutput });

  await github.rest.repos.createCommitComment({
    owner: context.repo.owner,
    repo: context.repo.repo,
    commit_sha: context.sha,
    body,
  });
}

// Export for testing and for actions/github-script usage
module.exports = postApplyComment;
module.exports.formatApplyComment = formatApplyComment;
module.exports.COMMENT_MARKER = COMMENT_MARKER;
