// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.

/** Captured 2026-03-22. read_sections on CFN RDS DBInstance page. Truncated from 97K chars. */
export const rdsEngine = {
  success: {
    result: `## Syntax

To declare this entity in your CloudFormation template, use the following syntax:

### JSON

\`\`\`
{
  "Type" : "AWS::RDS::DBInstance",
  "Properties" : {
      "AdditionalStorageVolumes" : [ AdditionalStorageVolume, ... ],
      "AllocatedStorage" : String,
      "AllowMajorVersionUpgrade" : Boolean,
      "ApplyImmediately" : Boolean,
      "AssociatedRoles" : [ DBInstanceRole, ... ],
      "AutomaticBackupReplicationKmsKeyId" : String,
      "AutomaticBackupReplicationRegion" : String,
      "AutomaticBackupReplicationRetentionPeriod" : Integer,
      "AutoMinorVersionUpgrade" : Boolean,
      "AvailabilityZone" : String,
      "BackupRetentionPeriod" : Integer,
      "BackupTarget" : String,
      "CACertificateIdentifier" : String,
      "CertificateRotationRestart" : Boolean,
      "CharacterSetName" : String,
      "CopyTagsToSnapshot" : Boolean,
      "CustomIAMInstanceProfile" : String,
      "DatabaseInsightsMode" : String,
      "DBClusterIdentifier" : String,
      "DBClusterSnapshotIdentifier" : String,
      "DBInstanceClass" : String,
      "DBInstanceIdentifier" : String,
      "DBName" : String,
      "DBParameterGroupName" : String,
      "DBSecurityGroups" : [ String, ... ],
      "DBSnapshotIdentifier" : String,
      "DBSubnetGroupName" : String,
      "DBSystemId" : String,
      "DedicatedLogVolume" : Boolean,
      "DeleteAutomatedBackups" : Boolean,
      "DeletionProtection" : Boolean,
      "Domain" : String,
      "DomainAuthSecretArn" : String,
      "DomainDnsIps" : [ String, ... ],
      "DomainFqdn" : String,
      "DomainIAMRoleName" : String,
      "DomainOu" : String,
      "EnableCloudwatchLogsExports" : [ String, ... ],
      "EnableIAMDatabaseAuthentication" : Boolean,
      "EnablePerformanceInsights" : Boolean,
      "Engine" : String,
      "EngineLifecycleSupport" : String,
      "EngineVersion" : String,
      "Iops" : Integer,
      "KmsKeyId" : String,
      "LicenseModel" : String,
      "ManageMasterUserPasswor

[Content truncated for test fixture]`,
  },
} as const;
