// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.

/** Synthetic: very long content — stress test for truncation/synthesis. */
export const longContent = {
  success: {
    result:
      "## Overview\n\n" +
      "This is a very long documentation page that covers many aspects of the resource configuration. ".repeat(
        50,
      ) +
      "\n\n## Properties\n\n" +
      "PropertyA: Description of property A.\n" +
      "PropertyB: Description of property B.\n" +
      "PropertyC: Description of property C.\n",
  },
} as const;

/** Synthetic: response with "Note: not found" pattern — stripped by display.ts regex. */
export const withNotFoundNote = {
  success: {
    result:
      "> **Note**: Section 'Syntax' not found in the document.\n\n" +
      "## Properties\n\n" +
      "**BucketName**\n" +
      "A name for the bucket.",
  },
} as const;

/** Synthetic: no matching sections error — triggers fallback to read_documentation. */
export const noMatchingSections = {
  error: new Error("No matching sections were found"),
} as const;

/** Synthetic: generic server error. */
export const serverError = {
  error: new Error("Internal server error: documentation service unavailable"),
} as const;
