// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.

/** Captured 2026-03-22 from aws-documentation-mcp-server. Input: { search_phrase: "BucketName AWS::S3::Bucket" }. 10 results, 3 kept. */
export const s3BucketName = {
  success: {
    query_id: "q-s3-bucket-name-001",
    search_results: [
      {
        rank_order: 1,
        url: "https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html",
        title: "AWS::S3::Bucket - AWS CloudFormation",
        context: "Use the CloudFormation AWS::S3::Bucket resource for S3.",
      },
      {
        rank_order: 2,
        url: "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html",
        title: "AWS::S3::Bucket - AWS CloudFormation",
        context: "Use the AWS CloudFormation AWS::S3::Bucket resource for S3.",
      },
      {
        rank_order: 3,
        url: "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-cors-corsrule.html",
        title: "AWS::S3::Bucket CorsRule - AWS CloudFormation",
        context:
          "Specifies a cross-origin access rule for an Amazon S3 bucket.",
      },
    ],
    facets: {},
  },
} as const;

/** Captured 2026-03-22 from aws-documentation-mcp-server. Input: { search_phrase: "InstanceType AWS::EC2::Instance" } */
export const ec2InstanceType = {
  success: {
    query_id: "q-ec2-instance-type-001",
    search_results: [
      {
        rank_order: 1,
        url: "https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-ec2-instance.html",
        title: "AWS::EC2::Instance - AWS CloudFormation",
        context: "Specifies an EC2 instance.",
      },
      {
        rank_order: 2,
        url: "https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-ec2.InstanceType.html",
        title: "class InstanceType · AWS CDK",
        context: "# class InstanceType",
      },
      {
        rank_order: 3,
        url: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-discovery.html",
        title:
          "Find an Amazon EC2 instance type - Amazon Elastic Compute Cloud",
        context:
          "Discover suitable EC2 instance types based on compute, memory, storage needs. Filter by Availability Zone, memory size, instance storage, hibernation support.",
      },
    ],
    facets: {},
  },
} as const;

/** Captured 2026-03-22 from aws-documentation-mcp-server. Input: { search_phrase: "Runtime AWS::Lambda::Function" } */
export const lambdaRuntime = {
  success: {
    query_id: "q-lambda-runtime-001",
    search_results: [
      {
        rank_order: 1,
        url: "https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html",
        title: "Working with Lambda environment variables - AWS Lambda",
        context:
          "Configure Lambda environment variables customize function behavior, encrypt secrets, manage keys console.",
      },
      {
        rank_order: 2,
        url: "https://docs.aws.amazon.com/lambda/latest/dg/runtime-management-configure-settings.html",
        title: "Configuring Lambda runtime management settings - AWS Lambda",
        context:
          "Lambda runtime management settings allow configuring automatic updates, updates on function changes, or manual updates with runtime version ARNs via console or CLI.",
      },
      {
        rank_order: 3,
        url: "https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-properties-lambda-version-runtimepolicy.html",
        title: "AWS::Lambda::Version RuntimePolicy - AWS CloudFormation",
        context:
          "Use the CloudFormation AWS::Lambda::Version.RuntimePolicy resource for Lambda.",
      },
    ],
    facets: {},
  },
} as const;

/** Captured 2026-03-22 from aws-documentation-mcp-server. Input: { search_phrase: "Engine AWS::RDS::DBInstance" } */
export const rdsEngine = {
  success: {
    query_id: "q-rds-engine-001",
    search_results: [
      {
        rank_order: 1,
        url: "https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-rds-dbinstance.html",
        title: "AWS::RDS::DBInstance - AWS CloudFormation",
        context:
          "Use the CloudFormation AWS::RDS::DBInstance resource for RDS.",
      },
      {
        rank_order: 2,
        url: "https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-properties-rds-dbinstance-dbinstancerole.html",
        title: "AWS::RDS::DBInstance DBInstanceRole - AWS CloudFormation",
        context:
          "Use the CloudFormation AWS::RDS::DBInstance.DBInstanceRole resource for RDS.",
      },
      {
        rank_order: 3,
        url: "https://docs.aws.amazon.com/sdk-for-cpp/latest/api/aws-cpp-sdk-rds/html/class_aws_1_1_r_d_s_1_1_model_1_1_d_b_instance.html",
        title: "AWS SDK for C++: Aws::RDS::Model::DBInstance Class Reference",
        context:
          "Aws::RDS::Model::DBInstance Class Reference - AWS SDK for C++ v1",
      },
    ],
    facets: {},
  },
} as const;

/** Synthetic: unstructured response — URL embedded in plain text (regex fallback path). */
export const unstructuredWithUrl = {
  success:
    "See https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketName.html for details",
} as const;

/** Synthetic: empty search results — no URLs in structured response. */
export const emptyResults = {
  success: {
    structuredContent: {
      search_results: [],
    },
  },
} as const;

/** Synthetic: no results — plain text response with no URL. */
export const noResultsText = {
  success: "No results found for the given search phrase.",
} as const;

/** Synthetic: null response — server returned nothing. */
export const nullResponse = {
  success: null,
} as const;
