// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText, iamResultEnvelope } from "./_helpers.js";

/** Captured 2026-03-22. All S3 bucket creation actions allowed. */
export const s3BucketAllowed = {
  success: mcpText(
    iamResultEnvelope({
      EvaluationResults: [
        {
          EvalActionName: "cloudcontrol:CreateResource",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "CloudControlFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 10, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "cloudcontrol:GetResourceRequestStatus",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "CloudControlFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 10, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "s3:CreateBucket",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "AmazonS3FullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 8, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "s3:PutBucketTagging",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "AmazonS3FullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 8, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
      ],
    }),
  ),
} as const;
