// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText, iamResultEnvelope } from "./_helpers.js";

/** Captured 2026-03-22. EC2 instance — ec2:RunInstances and iam:PassRole denied. */
export const ec2InstancePartialDeny = {
  success: mcpText(
    iamResultEnvelope({
      EvaluationResults: [
        {
          EvalActionName: "cloudcontrol:CreateResource",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "CloudControlFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 10, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "ec2:RunInstances",
          EvalResourceName: "*",
          EvalDecision: "implicitDeny",
          MatchedStatements: [],
          MissingContextValues: [],
        },
        {
          EvalActionName: "ec2:CreateTags",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "AmazonEC2TaggingAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 8, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "iam:PassRole",
          EvalResourceName: "*",
          EvalDecision: "implicitDeny",
          MatchedStatements: [],
          MissingContextValues: [],
        },
      ],
    }),
  ),
} as const;
