// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** ECR storage. Input: { service_code: "AmazonECR", filters: [productFamily=EC2 Container Registry, usagetype=USE1-TimedStorage-ByteHrs] } */
export const ecrStorage = {
  success: mcpText({
    status: "success",
    service_name: "AmazonECR",
    data: [
      {
        product: {
          productFamily: "EC2 Container Registry",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "USE1-TimedStorage-ByteHrs",
            servicecode: "AmazonECR",
            servicename: "Amazon EC2 Container Registry",
          },
          sku: "ECRSTORSKU000001",
        },
        terms: {
          OnDemand: {
            "ECRSTORSKU000001.JRTCKXETXF": {
              priceDimensions: {
                "ECRSTORSKU000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "GB-Mo",
                  endRange: "Inf",
                  description:
                    "$0.10 per GB per month for data stored in private or public repositories",
                  appliesTo: [],
                  rateCode: "ECRSTORSKU000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.1000000000",
                  },
                },
              },
              sku: "ECRSTORSKU000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonECR in us-east-1 from AWS Pricing API",
  }),
} as const;
