// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
// Extended by PD-3 (2026-05-13): added EU-region, data-transfer, and empty fixtures.
import { mcpText } from "./_helpers.js";

/** SQS Standard queue requests. Input: { service_code: "AmazonSQS", filters: [productFamily=API Request, queueType=Standard] } */
export const sqsStandardRequests = {
  success: mcpText({
    status: "success",
    service_name: "AmazonSQS",
    data: [
      {
        product: {
          productFamily: "API Request",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "USE1-Requests-Tier1",
            queueType: "Standard",
            servicecode: "AmazonSQS",
            servicename: "Amazon Simple Queue Service",
          },
          sku: "SQSSTDREQ0000001",
        },
        terms: {
          OnDemand: {
            "SQSSTDREQ0000001.JRTCKXETXF": {
              priceDimensions: {
                "SQSSTDREQ0000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Requests",
                  endRange: "Inf",
                  description:
                    "$0.40 per million Amazon SQS Requests per month for Standard queue",
                  appliesTo: [],
                  rateCode: "SQSSTDREQ0000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0000004000",
                  },
                },
              },
              sku: "SQSSTDREQ0000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonSQS in us-east-1 from AWS Pricing API",
  }),
} as const;

/**
 * SQS Standard queue requests — eu-west-1 (Variation B).
 * Input: { service_code: "AmazonSQS", region: "eu-west-1", filters: [productFamily=API Request, queueType=Standard] }
 * Pricing is the same rate as us-east-1; regionCode differs.
 */
export const sqsStandardRequestsEu = {
  success: mcpText({
    status: "success",
    service_name: "AmazonSQS",
    data: [
      {
        product: {
          productFamily: "API Request",
          attributes: {
            regionCode: "eu-west-1",
            usagetype: "EU-Requests-Tier1",
            queueType: "Standard",
            servicecode: "AmazonSQS",
            servicename: "Amazon Simple Queue Service",
          },
          sku: "SQSSTDREQEU000001",
        },
        terms: {
          OnDemand: {
            "SQSSTDREQEU000001.JRTCKXETXF": {
              priceDimensions: {
                "SQSSTDREQEU000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Requests",
                  endRange: "Inf",
                  description:
                    "$0.40 per million Amazon SQS Requests per month for Standard queue",
                  appliesTo: [],
                  rateCode: "SQSSTDREQEU000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0000004000",
                  },
                },
              },
              sku: "SQSSTDREQEU000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonSQS in eu-west-1 from AWS Pricing API",
  }),
} as const;

/** SQS FIFO queue requests. Input: { service_code: "AmazonSQS", filters: [productFamily=API Request, queueType=FIFO] } */
export const sqsFifoRequests = {
  success: mcpText({
    status: "success",
    service_name: "AmazonSQS",
    data: [
      {
        product: {
          productFamily: "API Request",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "USE1-Requests-FIFO-Tier1",
            queueType: "FIFO",
            servicecode: "AmazonSQS",
            servicename: "Amazon Simple Queue Service",
          },
          sku: "SQSFIFOREQ000001",
        },
        terms: {
          OnDemand: {
            "SQSFIFOREQ000001.JRTCKXETXF": {
              priceDimensions: {
                "SQSFIFOREQ000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Requests",
                  endRange: "Inf",
                  description:
                    "$0.50 per million Amazon SQS Requests per month for FIFO queue",
                  appliesTo: [],
                  rateCode: "SQSFIFOREQ000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0000005000",
                  },
                },
              },
              sku: "SQSFIFOREQ000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonSQS in us-east-1 from AWS Pricing API",
  }),
} as const;

/**
 * SQS Data Transfer Out (PD-3).
 * Input: { service_code: "AWSDataTransfer", filters: [
 *   productFamily=Data Transfer,
 *   fromLocationType=AWS Region,
 *   toLocationType=Other,
 *   transferType=AWS Outbound,
 *   fromRegionCode=us-east-1  (injected by breakdown.ts SDK-bypass path)
 * ]}
 * Mirrors s3DataTransfer fixture shape — same AWSDataTransfer service code.
 */
export const sqsDataTransferOut = {
  success: mcpText({
    status: "success",
    service_name: "AWSDataTransfer",
    data: [
      {
        product: {
          productFamily: "Data Transfer",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "DataTransfer-Out-Bytes",
            transferType: "AWS Outbound",
            fromLocation: "US East (N. Virginia)",
            fromLocationType: "AWS Region",
            toLocation: "External",
            toLocationType: "Other",
            servicecode: "AWSDataTransfer",
            servicename: "AWS Data Transfer",
          },
          sku: "DTOUTSKU00000002",
        },
        terms: {
          OnDemand: {
            "DTOUTSKU00000002.JRTCKXETXF": {
              priceDimensions: {
                "DTOUTSKU00000002.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "GB",
                  endRange: "Inf",
                  description:
                    "$0.09 per GB - next 9.999 TB / month data transfer out beyond the global free tier",
                  appliesTo: [],
                  rateCode: "DTOUTSKU00000002.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "1",
                  pricePerUnit: {
                    USD: "0.0900000000",
                  },
                },
              },
              sku: "DTOUTSKU00000002",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260223232215",
        publicationDate: "2026-02-23T23:22:15Z",
      },
    ],
    message:
      "Retrieved pricing for AWSDataTransfer in us-east-1 from AWS Pricing API",
  }),
} as const;

/**
 * Empty response for unsupported/obscure regions (Variation D — graceful fallback).
 * Simulates the Pricing MCP returning no data for an unknown region.
 */
export const sqsEmptyResponse = {
  success: mcpText({
    status: "success",
    service_name: "AmazonSQS",
    data: [],
    message:
      "No results found for AmazonSQS in ap-east-99 from AWS Pricing API",
  }),
} as const;
