// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** SNS publishes. Input: { service_code: "AmazonSNS", filters: [productFamily=API Request, group=SNS-Requests-Tier1] } */
export const snsPublishes = {
  success: mcpText({
    status: "success",
    service_name: "AmazonSNS",
    data: [
      {
        product: {
          productFamily: "API Request",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "USE1-Requests-Tier1",
            group: "SNS-Requests-Tier1",
            servicecode: "AmazonSNS",
            servicename: "Amazon Simple Notification Service",
          },
          sku: "SNSPUBREQSK00001",
        },
        terms: {
          OnDemand: {
            "SNSPUBREQSK00001.JRTCKXETXF": {
              priceDimensions: {
                "SNSPUBREQSK00001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Requests",
                  endRange: "Inf",
                  description: "$0.50 per million Amazon SNS requests",
                  appliesTo: [],
                  rateCode: "SNSPUBREQSK00001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0000005000",
                  },
                },
              },
              sku: "SNSPUBREQSK00001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonSNS in us-east-1 from AWS Pricing API",
  }),
} as const;
