// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 from aws-pricing-mcp-server. Input: { service_code: "AWSSystemsManager", filters: [productFamily=AWS Systems Manager] }. 34 items captured, 1 kept. */
export const ssmParameter = {
  success: mcpText({
    status: "success",
    service_name: "AWSSystemsManager",
    data: [
      {
        product: {
          productFamily: "AWS Systems Manager",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "USE1-SmAdvParamStorageHrs",
            servicecode: "AWSSystemsManager",
            servicename: "AWS Systems Manager",
          },
          sku: "2SC234H95RE9KUWA",
        },
        terms: {
          OnDemand: {
            "2SC234H95RE9KUWA.JRTCKXETXF": {
              priceDimensions: {
                "2SC234H95RE9KUWA.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "API Requests",
                  endRange: "Inf",
                  description: "SSM Parameter Storage in US East (N. Virginia)",
                  appliesTo: [],
                  rateCode: "2SC234H95RE9KUWA.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0000700000",
                  },
                },
              },
              sku: "2SC234H95RE9KUWA",
              effectiveDate: "2025-08-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20250828153807",
        publicationDate: "2025-08-28T15:38:07Z",
      },
    ],
    message:
      "Retrieved pricing for AWSSystemsManager in us-east-1 from AWS Pricing API",
  }),
} as const;
