// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** EC2 decomposer: EBS gp3 storage. Input: { service_code: "AmazonEC2", filters: [productFamily=Storage, volumeApiName=gp3] } */
export const ebsGp3Storage = {
  success: mcpText({
    status: "success",
    service_name: "AmazonEC2",
    data: [
      {
        product: {
          productFamily: "Storage",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "EBS:VolumeUsage.gp3",
            volumeApiName: "gp3",
            servicecode: "AmazonEC2",
            servicename: "Amazon Elastic Compute Cloud",
          },
          sku: "GP3VOLSKU00001",
        },
        terms: {
          OnDemand: {
            "GP3VOLSKU00001.JRTCKXETXF": {
              priceDimensions: {
                "GP3VOLSKU00001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "GB-Mo",
                  endRange: "Inf",
                  description:
                    "$0.08 per GB-month of General Purpose (gp3) provisioned storage",
                  appliesTo: [],
                  rateCode: "GP3VOLSKU00001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0800000000",
                  },
                },
              },
              sku: "GP3VOLSKU00001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonEC2 in us-east-1 from AWS Pricing API",
  }),
} as const;

/** EC2 decomposer: Public IPv4 address. Input: { service_code: "AmazonVPC", filters: [productFamily=IP Address, group=ElasticIP:Address] } */
export const publicIpv4 = {
  success: mcpText({
    status: "success",
    service_name: "AmazonVPC",
    data: [
      {
        product: {
          productFamily: "IP Address",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "ElasticIP:IdleAddress",
            group: "ElasticIP:Address",
            servicecode: "AmazonVPC",
            servicename: "Amazon Virtual Private Cloud",
          },
          sku: "IPV4ADDRSKU0001",
        },
        terms: {
          OnDemand: {
            "IPV4ADDRSKU0001.JRTCKXETXF": {
              priceDimensions: {
                "IPV4ADDRSKU0001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description:
                    "$0.005 per Elastic IP address not attached to a running instance per hour",
                  appliesTo: [],
                  rateCode: "IPV4ADDRSKU0001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0050000000",
                  },
                },
              },
              sku: "IPV4ADDRSKU0001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonVPC in us-east-1 from AWS Pricing API",
  }),
} as const;

/** EC2 decomposer: Data transfer out. Input: { service_code: "AWSDataTransfer", filters: [productFamily=Data Transfer, transferType=AWS Outbound] } */
export const dataTransferOut = {
  success: mcpText({
    status: "success",
    service_name: "AWSDataTransfer",
    data: [
      {
        product: {
          productFamily: "Data Transfer",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "DataTransfer-Out-Bytes",
            fromLocationType: "AWS Region",
            toLocationType: "External",
            transferType: "AWS Outbound",
            servicecode: "AWSDataTransfer",
            servicename: "AWS Data Transfer",
          },
          sku: "DTOUTSKU000001",
        },
        terms: {
          OnDemand: {
            "DTOUTSKU000001.JRTCKXETXF": {
              priceDimensions: {
                "DTOUTSKU000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "GB",
                  endRange: "Inf",
                  description: "$0.09 per GB - data transfer out to Internet",
                  appliesTo: [],
                  rateCode: "DTOUTSKU000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0900000000",
                  },
                },
              },
              sku: "DTOUTSKU000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AWSDataTransfer in us-east-1 from AWS Pricing API",
  }),
} as const;
