// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Lambda decomposer: Requests. Input: { service_code: "AWSLambda", filters: [productFamily=Serverless, group=AWS-Lambda-Requests, usagetype=Request] } */
export const lambdaRequests = {
  success: mcpText({
    status: "success",
    service_name: "AWSLambda",
    data: [
      {
        product: {
          productFamily: "Serverless",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "Request",
            group: "AWS-Lambda-Requests",
            servicecode: "AWSLambda",
            servicename: "AWS Lambda",
          },
          sku: "LMBREQSKU000001",
        },
        terms: {
          OnDemand: {
            "LMBREQSKU000001.JRTCKXETXF": {
              priceDimensions: {
                "LMBREQSKU000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Requests",
                  endRange: "Inf",
                  description: "$0.20 per 1M requests",
                  appliesTo: [],
                  rateCode: "LMBREQSKU000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.2000000000",
                  },
                },
              },
              sku: "LMBREQSKU000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AWSLambda in us-east-1 from AWS Pricing API",
  }),
} as const;

/** Lambda decomposer: Duration (GB-second). Input: { service_code: "AWSLambda", filters: [productFamily=Serverless, group=AWS-Lambda-Duration, usagetype=Lambda-GB-Second] } */
export const lambdaDuration = {
  success: mcpText({
    status: "success",
    service_name: "AWSLambda",
    data: [
      {
        product: {
          productFamily: "Serverless",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "Lambda-GB-Second",
            group: "AWS-Lambda-Duration",
            servicecode: "AWSLambda",
            servicename: "AWS Lambda",
          },
          sku: "LMBDURSKU000001",
        },
        terms: {
          OnDemand: {
            "LMBDURSKU000001.JRTCKXETXF": {
              priceDimensions: {
                "LMBDURSKU000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Second",
                  endRange: "Inf",
                  description: "$0.0000166667 per GB-second",
                  appliesTo: [],
                  rateCode: "LMBDURSKU000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0000166667",
                  },
                },
              },
              sku: "LMBDURSKU000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AWSLambda in us-east-1 from AWS Pricing API",
  }),
} as const;
