// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 via DescribeType. Input: { resource_type: "AWS::EC2::Subnet" }. 18 props in full schema, trimmed to 5. */
export const subnet = {
  success: mcpText({
    typeName: "AWS::EC2::Subnet",
    description:
      "Specifies a subnet for the specified VPC.\n For an IPv4 only subnet, specify an IPv4 CIDR block. If the VPC has an IPv6 CIDR block, you can create an IPv6 only subnet or a dual stack subnet instead. For an IPv6 only subnet, specify an IPv6 CIDR block. For a dual stack subnet, specify both an IPv4 CIDR block and an IPv6 CIDR block.",
    properties: {
      VpcId: {
        type: "string",
        description: "The ID of the VPC the subnet is in.",
      },
      CidrBlock: {
        type: "string",
        description:
          "The IPv4 CIDR block assigned to the subnet.\n If you update this property, we create a new subnet, and then delete the existing one.",
      },
      AvailabilityZone: {
        type: "string",
        description:
          "The Availability Zone of the subnet.\n If you update this property, we create a new subnet, and then delete the existing one.",
      },
      MapPublicIpOnLaunch: {
        type: "boolean",
        description:
          "Indicates whether instances launched in this subnet receive a public IPv4 address. The default value is ``false``.\n  AWS charges for all public IPv4 addresses, including public IPv4 addresses associated with running instances and Elastic IP addresses.",
      },
      Tags: {
        type: "array",
        description: "Any tags assigned to the subnet.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Tag",
        },
      },
    },
    required: ["VpcId"],
    readOnlyProperties: [
      "/properties/SubnetId",
      "/properties/AvailabilityZoneId",
      "/properties/NetworkAclAssociationId",
    ],
    primaryIdentifier: ["/properties/SubnetId"],
    additionalProperties: false,
  }),
} as const;
