// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 via DescribeType. Input: { resource_type: "AWS::EC2::VPC" }. 8 props in full schema, trimmed to 5. */
export const vpc = {
  success: mcpText({
    typeName: "AWS::EC2::VPC",
    description:
      "Specifies a virtual private cloud (VPC).\n To add an IPv6 CIDR block to the VPC, see [AWS::EC2::VPCCidrBlock](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpccidrblock.html).",
    properties: {
      CidrBlock: {
        type: "string",
        description:
          "The IPv4 network range for the VPC, in CIDR notation. For example, ``10.0.0.0/16``. We modify the specified CIDR block to its canonical form; for example, if you specify ``100.68.0.18/18``, we modify it to ``100.68.0.0/18``.",
      },
      EnableDnsHostnames: {
        type: "boolean",
        description:
          "Indicates whether the instances launched in the VPC get DNS hostnames. If enabled, instances in the VPC get DNS hostnames; otherwise, they do not.",
      },
      EnableDnsSupport: {
        type: "boolean",
        description:
          'Indicates whether the DNS resolution is supported for the VPC. If enabled, queries to the Amazon provided DNS server at the 169.254.169.253 IP address, or the reserved IP address at the base of the VPC network range "plus two" succeed. If disabled, the Amazon provided DNS service in the VPC that resolves public DNS hostnames to IP addresses is not enabled.',
      },
      InstanceTenancy: {
        type: "string",
        description:
          "The allowed tenancy of instances launched into the VPC.\n ``default``: An instance launched into the VPC runs on shared hardware by default, unless you explicitly specify a different tenancy during instance launch.\n ``dedicated``: An instance launched into the VPC runs on dedicated hardware by default, unless you explicitly specify a tenancy of ``host`` during instance launch. You cannot specify a tenancy of ``default`` during instance launch.",
        enum: ["default", "dedicated"],
      },
      Tags: {
        type: "array",
        description: "The tags for the VPC.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Tag",
        },
      },
    },
    required: [],
    readOnlyProperties: [
      "/properties/VpcId",
      "/properties/CidrBlockAssociations",
      "/properties/DefaultNetworkAcl",
      "/properties/DefaultSecurityGroup",
    ],
    primaryIdentifier: ["/properties/VpcId"],
    additionalProperties: false,
  }),
} as const;
