// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 via DescribeType. Input: { TypeName: "AWS::Custom::FakeResource" }. Returns error (TypeNotFoundException). */
export const generic = {
  success: {
    type: "text" as const,
    text: `An error occurred (TypeNotFoundException) when calling the DescribeType operation: The type 'AWS::Custom::FakeResource' cannot be found.`,
  },
} as const;

/** Synthetic: empty schema edge case — DescribeType never returns empty schemas for known types. */
export const empty = {
  success: mcpText({
    typeName: "AWS::Unknown::Type",
    properties: {},
  }),
} as const;
