// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 via DescribeType. Input: { resource_type: "AWS::ElasticLoadBalancingV2::LoadBalancer" }. 12 props in full schema, trimmed to 7. */
export const elbv2LoadBalancer = {
  success: mcpText({
    typeName: "AWS::ElasticLoadBalancingV2::LoadBalancer",
    description:
      "Specifies an Application Load Balancer, a Network Load Balancer, or a Gateway Load Balancer.",
    properties: {
      Name: {
        type: "string",
        description:
          'The name of the load balancer. This name must be unique per region per account, can have a maximum of 32 characters, must contain only alphanumeric characters or hyphens, must not begin or end with a hyphen, and must not begin with "internal-".\n If you don\'t specify a name, AWS CloudFormation generates a unique physical ID for the load balancer.',
      },
      Type: {
        type: "string",
        description:
          "The type of load balancer. The default is ``application``.",
        enum: ["application", "network", "gateway"],
      },
      Scheme: {
        type: "string",
        description:
          "The nodes of an Internet-facing load balancer have public IP addresses. The DNS name of an Internet-facing load balancer is publicly resolvable to the public IP addresses of the nodes. Therefore, Internet-facing load balancers can route requests from clients over the internet.\n The nodes of an internal load balancer have only private IP addresses. The DNS name of an internal load balancer is publicly resolvable to the private IP addresses of the nodes. Therefore, internal load balancers can only route requests from clients with access to the VPC for the load balancer.\n The default is an Internet-facing load balancer.\n You cannot specify a scheme for a Gateway Load Balancer.",
        enum: ["internet-facing", "internal"],
      },
      Subnets: {
        type: "array",
        description:
          "The IDs of the subnets. You can specify only one subnet per Availability Zone. You must specify either subnets or subnet mappings, but not both.",
        insertionOrder: false,
        items: {
          type: "string",
        },
      },
      SecurityGroups: {
        type: "array",
        description: "The IDs of the security groups for the load balancer.",
        insertionOrder: false,
        items: {
          type: "string",
        },
      },
      IpAddressType: {
        type: "string",
        description:
          "The IP address type. The possible values are ``ipv4`` (for IPv4 addresses) and ``dualstack`` (for IPv4 and IPv6 addresses). You can't specify ``dualstack`` for a load balancer with a UDP or TCP_UDP listener.",
        enum: ["ipv4", "dualstack"],
      },
      Tags: {
        type: "array",
        description: "The tags to assign to the load balancer.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Tag",
        },
      },
    },
    required: [],
    readOnlyProperties: [
      "/properties/LoadBalancerArn",
      "/properties/LoadBalancerFullName",
      "/properties/LoadBalancerName",
      "/properties/DNSName",
      "/properties/CanonicalHostedZoneID",
    ],
    primaryIdentifier: ["/properties/LoadBalancerArn"],
    additionalProperties: false,
  }),
} as const;
