// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 via DescribeType. Input: { resource_type: "AWS::S3::Bucket" }. 30 props in full schema, trimmed to 10. */
export const s3Bucket = {
  success: mcpText({
    typeName: "AWS::S3::Bucket",
    description:
      "The ``AWS::S3::Bucket`` resource creates an Amazon S3 bucket in the same AWS Region where you create the AWS CloudFormation stack.\n To control how AWS CloudFormation handles the bucket when the stack is deleted, you can set a deletion policy for your bucket. You can choose to *retain* the bucket or to *delete* the bucket. For more information, see [DeletionPolicy Attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html).\n  You can only delete empty buckets. Deletion fails for buckets that have contents.",
    properties: {
      Tags: {
        type: "array",
        description:
          "An arbitrary set of tags (key-value pairs) for this S3 bucket.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Tag",
        },
      },
      Arn: {
        description: "",
        $ref: "#/definitions/Arn",
      },
      BucketName: {
        type: "string",
        description:
          "A name for the bucket. If you don't specify a name, AWS CloudFormation generates a unique ID and uses that ID for the bucket name. The bucket name must contain only lowercase letters, numbers, periods (.), and dashes (-) and must follow [Amazon S3 bucket restrictions and limitations](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html). For more information, see [Rules for naming Amazon S3 buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) in the *Amazon S3 User Guide*. \n  If you specify a name, you can't perform updates that require replacement of this resource. You can perform updates that require no or some interruption. If you need to replace the resource, specify a new name.",
      },
      VersioningConfiguration: {
        description:
          "Enables multiple versions of all objects in this bucket. You might enable versioning to prevent objects from being deleted or overwritten by mistake or to archive objects so that you can retrieve previous versions of them.\n  When you enable versioning on a bucket for the first time, it might take a short amount of time for the change to be fully propagated. We recommend that you wait for 15 minutes after enabling versioning before issuing write operations (``PUT`` or ``DELETE``) on objects in the bucket.",
        $ref: "#/definitions/VersioningConfiguration",
      },
      BucketEncryption: {
        description:
          "Specifies default encryption for a bucket using server-side encryption with Amazon S3-managed keys (SSE-S3), AWS KMS-managed keys (SSE-KMS), or dual-layer server-side encryption with KMS-managed keys (DSSE-KMS). For information about the Amazon S3 default encryption feature, see [Amazon S3 Default Encryption for S3 Buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html) in the *Amazon S3 User Guide*.",
        $ref: "#/definitions/BucketEncryption",
      },
      AccessControl: {
        type: "string",
        description:
          "This is a legacy property, and it is not recommended for most use cases. A majority of modern use cases in Amazon S3 no longer require the use of ACLs, and we recommend that you keep ACLs disabled. For more information, see [Controlling object ownership](https://docs.aws.amazon.com//AmazonS3/latest/userguide/about-object-ownership.html) in the *Amazon S3 User Guide*.\n  A canned access control list (ACL) that grants predefined permissions to the bucket. For more information about canned ACLs, see [Canned ACL](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl) in the *Amazon S3 User Guide*.\n  S3 buckets are created with ACLs disabled by default. Therefore, unless you explicitly set the [AWS::S3::OwnershipControls](https://docs.aws.amazon.com//AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-ownershipcontrols.html) property to enable ACLs, your resource will fail to deploy with any value other than Private. Use cases requiring ACLs are uncommon.\n  The majority of access control configurations can be successfully and more easily achieved with bucket policies. For more information, see [AWS::S3::BucketPolicy](https://docs.aws.amazon.com//AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html). For examples of common policy configurations, including S3 Server Access Logs buckets and more, see [Bucket policy examples](https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html) in the *Amazon S3 User Guide*.",
        enum: [
          "AuthenticatedRead",
          "AwsExecRead",
          "BucketOwnerFullControl",
          "BucketOwnerRead",
          "LogDeliveryWrite",
          "Private",
          "PublicRead",
          "PublicReadWrite",
        ],
      },
      PublicAccessBlockConfiguration: {
        description:
          "Configuration that defines how Amazon S3 handles public access.",
        $ref: "#/definitions/PublicAccessBlockConfiguration",
      },
      LifecycleConfiguration: {
        description:
          "Specifies the lifecycle configuration for objects in an Amazon S3 bucket. For more information, see [Object Lifecycle Management](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html) in the *Amazon S3 User Guide*.",
        $ref: "#/definitions/LifecycleConfiguration",
      },
    },
    required: [],
    readOnlyProperties: [
      "/properties/Arn",
      "/properties/DomainName",
      "/properties/DualStackDomainName",
      "/properties/RegionalDomainName",
      "/properties/MetadataTableConfiguration/S3TablesDestination/TableNamespace",
      "/properties/MetadataTableConfiguration/S3TablesDestination/TableArn",
      "/properties/MetadataConfiguration/Destination",
      "/properties/MetadataConfiguration/JournalTableConfiguration/TableName",
      "/properties/MetadataConfiguration/JournalTableConfiguration/TableArn",
      "/properties/MetadataConfiguration/InventoryTableConfiguration/TableName",
      "/properties/MetadataConfiguration/InventoryTableConfiguration/TableArn",
      "/properties/WebsiteURL",
    ],
    primaryIdentifier: ["/properties/BucketName"],
    additionalProperties: false,
  }),
} as const;
