// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { securityResultEnvelope } from "./_helpers.js";

/** Captured 2026-04-10. S3 bucket with CRITICAL + HIGH + MEDIUM findings (v0.1.7 envelope). */
export const s3BucketPosture = {
  success: securityResultEnvelope({
    service: "securityhub",
    enabled: true,
    findings: [
      {
        severity: "CRITICAL",
        title: "S3 bucket has public read access",
        recommendation:
          "Block public access by enabling S3 Block Public Access settings at the bucket level. Set BlockPublicAcls, IgnorePublicAcls, BlockPublicPolicy, and RestrictPublicBuckets to true.",
        service: "SecurityHub",
        controlId: "S3.2",
        complianceStatus: "FAILED",
        resourceArn: "arn:aws:s3:::assignee-test-capture-bucket",
      },
      {
        severity: "HIGH",
        title: "S3 bucket does not have default encryption enabled",
        recommendation:
          "Enable default encryption on the S3 bucket using SSE-S3 (AES-256) or SSE-KMS. Use aws s3api put-bucket-encryption to configure server-side encryption.",
        service: "SecurityHub",
        controlId: "S3.4",
        complianceStatus: "FAILED",
        resourceArn: "arn:aws:s3:::assignee-test-capture-bucket",
      },
      {
        severity: "MEDIUM",
        title: "S3 bucket versioning is not enabled",
        recommendation:
          "Enable versioning on the S3 bucket to preserve, retrieve, and restore every version of every object. Use aws s3api put-bucket-versioning --bucket BUCKET --versioning-configuration Status=Enabled.",
        service: "SecurityHub",
        controlId: "S3.14",
        complianceStatus: "FAILED",
        resourceArn: "arn:aws:s3:::assignee-test-capture-bucket",
      },
    ],
    summary: {
      total: 3,
      critical: 1,
      high: 1,
      medium: 1,
      low: 0,
      informational: 0,
    },
  }),
} as const;

/** Captured 2026-04-10. No findings — clean security posture (v0.1.7 envelope). */
export const noFindings = {
  success: securityResultEnvelope({
    service: "securityhub",
    enabled: true,
    findings: [],
    summary: {
      total: 0,
      critical: 0,
      high: 0,
      medium: 0,
      low: 0,
      informational: 0,
    },
  }),
} as const;

/** Captured 2026-04-10. Security Hub not enabled in region (v0.1.7 envelope). */
export const serviceDisabled = {
  success: securityResultEnvelope({
    service: "securityhub",
    enabled: false,
    message:
      "Security Hub is not enabled in us-east-1. Enable it via the AWS console or CLI.",
  }),
} as const;

/** Captured 2026-04-10. CheckSecurityServices response (v0.1.7 envelope). */
export const checkServicesAllEnabled = {
  success: securityResultEnvelope({
    region: "us-east-1",
    services_checked: ["securityhub"],
    all_enabled: true,
    service_statuses: {
      securityhub: { enabled: true, details: "Security Hub is active" },
    },
  }),
} as const;

/** Captured 2026-04-10. CheckSecurityServices — service disabled (v0.1.7 envelope). */
export const checkServicesDisabled = {
  success: securityResultEnvelope({
    region: "us-east-1",
    services_checked: ["securityhub"],
    all_enabled: false,
    service_statuses: {
      securityhub: {
        enabled: false,
        details: "Security Hub is not enabled in this region",
      },
    },
  }),
} as const;
