/**
 * Utility for reading and writing .env files with merge semantics.
 * Preserves comments, blank lines, and existing env vars.
 *
 * @see Story 18.8 — IAM Security Overhaul
 */

import * as fs from "node:fs";
import * as path from "node:path";

/** Keys that should be removed during migration from older credential models. */
const DEPRECATED_KEYS = [
  "MCP_AWS_ACCESS_KEY_ID",
  "MCP_AWS_SECRET_ACCESS_KEY",
  "AWS_ACCESS_KEY_ID",
  "AWS_SECRET_ACCESS_KEY",
];

/**
 * Compute the set of stale `*_SESSION_TOKEN` keys that must be evicted
 * because their paired `*_ACCESS_KEY_ID` is being rewritten without a
 * matching session token in the same update.
 *
 * Session tokens are only valid for the temporary AKID/SECRET pair they
 * were issued with. If `assignee setup` rotates an operator user to a
 * fresh long-lived AKIA-prefixed key, any pre-existing
 * `ASSIGNEE_OPERATOR_SESSION_TOKEN` from a previous SSO/STS session is
 * stale — leaving it on disk causes Bedrock and CCAPI to reject calls
 * with "The security token included in the request is invalid".
 *
 * Scope is intentionally restricted to the three roles `assignee setup`
 * actually rotates — OPERATOR / READER / AUDITOR (see
 * `apps/cli/src/commands/setup/constants.ts`). A broader regex like
 * `^(.+)_ACCESS_KEY_ID$` would also match `AWS_ACCESS_KEY_ID` (which
 * users may legitimately have from `aws sso export`), the deprecated
 * `MCP_AWS_ACCESS_KEY_ID`, or compound keys such as
 * `ASSIGNEE_OPERATOR_PRIMARY_ACCESS_KEY_ID`, evicting unrelated session
 * tokens or deriving nonsense token keys. Add a new role here only when
 * the setup command starts rotating it.
 */
function staleSessionTokenKeys(updates: Record<string, string>): Set<string> {
  const stale = new Set<string>();
  for (const key of Object.keys(updates)) {
    const m = /^(ASSIGNEE_(?:OPERATOR|READER|AUDITOR))_ACCESS_KEY_ID$/.exec(
      key,
    );
    if (!m) continue;
    const tokenKey = `${m[1]!}_SESSION_TOKEN`;
    if (!(tokenKey in updates)) stale.add(tokenKey);
  }
  return stale;
}

/**
 * Reads an existing .env file, upserts the given key-value pairs,
 * removes deprecated MCP_AWS_* keys, evicts stale `*_SESSION_TOKEN`
 * entries paired with a rotated `*_ACCESS_KEY_ID`, and writes the
 * result back.
 *
 * @param envPath - Absolute path to the .env file.
 * @param updates - Key-value pairs to upsert.
 */
export function mergeEnvFile(
  envPath: string,
  updates: Record<string, string>,
): void {
  let lines: string[] = [];

  // Read existing file if present
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, "utf-8");
    lines = content.split("\n");
  }

  // Track which keys have been updated (to avoid duplicates)
  const updatedKeys = new Set<string>();
  const staleTokens = staleSessionTokenKeys(updates);

  // Process existing lines: update values for matching keys, remove deprecated keys
  const processedLines: string[] = [];
  for (const line of lines) {
    const trimmed = line.trim();

    // Skip deprecated keys
    if (DEPRECATED_KEYS.some((key) => trimmed.startsWith(`${key}=`))) {
      continue;
    }

    // Skip stale `*_SESSION_TOKEN` keys whose paired AKID is being rotated.
    if ([...staleTokens].some((key) => trimmed.startsWith(`${key}=`))) {
      continue;
    }

    // Check if this line is a key=value pair that needs updating
    const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)=/);
    if (match) {
      const key = match[1]!;
      if (key in updates) {
        processedLines.push(`${key}=${updates[key]}`);
        updatedKeys.add(key);
        continue;
      }
    }

    processedLines.push(line);
  }

  // Append any new keys that weren't already in the file
  const newKeys = Object.keys(updates).filter((k) => !updatedKeys.has(k));
  if (newKeys.length > 0) {
    // Add a blank line separator if the file doesn't end with one
    const lastLine = processedLines[processedLines.length - 1];
    if (lastLine !== undefined && lastLine.trim() !== "") {
      processedLines.push("");
    }

    processedLines.push(
      "# ── Assignee.ai IAM Credentials (generated by assignee setup) ──",
    );
    for (const key of newKeys) {
      processedLines.push(`${key}=${updates[key]}`);
    }
  }

  // Ensure file ends with a newline
  const output = processedLines.join("\n").replace(/\n*$/, "\n");

  // Ensure directory exists with 0700 permissions — parent of .env should not
  // be world-readable since it hosts AWS credentials. New dirs get 0700 via
  // mkdirSync mode; pre-existing dirs keep their mode, so chmod belt-and-braces.
  const dir = path.dirname(envPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  }
  try {
    fs.chmodSync(dir, 0o700);
  } catch {
    // chmod may fail on Windows — non-fatal
  }

  // Write with 0600 permissions — .env contains AWS credentials.
  // Writing with mode only affects new files; existing files keep their mode,
  // so we also chmod after write to harden any pre-existing .env.
  fs.writeFileSync(envPath, output, { encoding: "utf-8", mode: 0o600 });
  try {
    fs.chmodSync(envPath, 0o600);
  } catch {
    // chmod may fail on Windows — non-fatal
  }
}
