/**
 * Global init flow — ~/.config/assignee/config.yaml.
 *
 * @see Story 27.5
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as clack from "@clack/prompts";
import { stringify as yamlStringify } from "yaml";
import { resolveConfigPath } from "../../config/user-config-loader.js";
import { promptGlobalConfig } from "./global-wizard.js";

/**
 * Runs the global config flow. Returns when done (or after early exit).
 */
export async function runGlobalInit(): Promise<void> {
  const configPath = resolveConfigPath();
  const configDir = path.dirname(configPath);

  // Check for existing global config
  try {
    await fs.access(configPath);
    const overwrite = await clack.confirm({
      message: `Global config already exists at ${configPath}. Overwrite it?`,
      initialValue: false,
    });

    if (clack.isCancel(overwrite) || overwrite === false) {
      clack.outro(
        `Keeping existing configuration at ${configPath}. No changes made.`,
      );
      return;
    }
  } catch {
    // Config does not exist — proceed
  }

  const config = await promptGlobalConfig();
  if (!config) return;

  await fs.mkdir(configDir, { recursive: true });
  const yamlContent =
    "# Generated by assignee init --global\n" + yamlStringify(config);
  await fs.writeFile(configPath, yamlContent, "utf-8");

  clack.outro(
    `Global config written to ${configPath}. Your defaults will apply to all projects.`,
  );
}
