/**
 * Project init flow — ./.assignee/config.yaml.
 *
 * Reports credential status (non-fatal), detects region, and writes the
 * project config via the project-wizard.
 *
 * Epic 92 u.d: accepts a `NonInteractiveOverrides` bag so the Commander
 * entry point can drive the flow non-interactively when `--yes` /
 * `--region` / `--auto-fix` are supplied. Interactive path (no flags)
 * is unchanged — the prompts still fire when the override fields are
 * undefined.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as clack from "@clack/prompts";
import { stringify as yamlStringify } from "yaml";
import {
  detectCredentials,
  detectRegion,
} from "../../services/credential-detector.js";
import { CHECKPOINT_DIR, FileName } from "../../config/constants.js";
import { detectAvailableRoles } from "./credentials-detect.js";
import { promptProjectConfig } from "./project-wizard.js";
import type { NonInteractiveOverrides } from "./project-config-types.js";

export type { NonInteractiveOverrides } from "./project-config-types.js";

/**
 * Report the credential state with a single concise clack block.
 */
function reportCredentialState(credentialResult: {
  detected: boolean;
  source?: string;
  profile?: string;
}): void {
  const availableRoles = detectAvailableRoles();
  if (credentialResult.detected) {
    clack.log.success(
      `AWS credentials detected (source: ${credentialResult.source})`,
    );
    if (availableRoles.length > 0) {
      clack.log.info(`Assignee roles available: ${availableRoles.join(", ")}`);
    } else {
      clack.log.info(
        "Assignee roles available: none (operator, reader, auditor all unset)",
      );
    }
  } else {
    // UX (M-T2): single multi-line warn block, scan-friendly.
    const rolesLine =
      availableRoles.length > 0
        ? `Assignee roles available: ${availableRoles.join(", ")}`
        : "Assignee roles available: none (operator, reader, auditor all unset)";
    clack.log.warn(
      "No AWS credentials detected. The project config will still be created.\n" +
        "Next steps: run `assignee setup` to create least-privilege IAM users (recommended), " +
        "OR export `AWS_ACCESS_KEY_ID` + `AWS_SECRET_ACCESS_KEY` before running `assignee plan`.\n" +
        "Note: `AWS_PROFILE` alone is not currently supported — use explicit env vars or run " +
        "`assignee setup` to create role-specific credentials.\n" +
        rolesLine,
    );
  }
}

/** Run the project-level init flow. */
export async function runProjectInit(
  overrides: NonInteractiveOverrides = {},
): Promise<void> {
  const credentialResult = await detectCredentials();
  reportCredentialState(credentialResult);

  const regionResult = await detectRegion();

  const configDir = path.resolve(process.cwd(), CHECKPOINT_DIR);
  const configPath = path.join(configDir, FileName.CONFIG);

  // Check for existing config
  try {
    await fs.access(configPath);
    // D-06: when --yes is set, treat it as implicit overwrite consent.
    // This matches how `npm init --yes` / `gh init --yes` behave and lets
    // CI pipelines re-run init without an interactive block.
    if (overrides.yes === true) {
      // Silent overwrite; caller opted in via --yes.
    } else {
      const overwrite = await clack.confirm({
        message: `Project config already exists at ${configPath}. Overwrite it?`,
        initialValue: false,
      });

      if (clack.isCancel(overwrite) || overwrite === false) {
        clack.outro(
          `Keeping existing configuration at ${configPath}. No changes made.`,
        );
        return;
      }
    }
  } catch {
    // Config does not exist — proceed
  }

  const config = await promptProjectConfig(
    {
      region: overrides.region ?? regionResult.region,
      profile: credentialResult.profile,
    },
    overrides,
  );
  if (!config) return;

  await fs.mkdir(configDir, { recursive: true });

  const yamlContent = "# Generated by assignee init\n" + yamlStringify(config);
  await fs.writeFile(configPath, yamlContent, "utf-8");

  const profileNote =
    config.profile !== "default" ? ` with profile ${config.profile}` : "";
  clack.outro(
    `Initialized assignee.ai for region ${config.region}${profileNote}. Run \`assignee plan\` to get started.`,
  );
}
