// Post or update a PR comment with plan results.
// Uses an HTML marker for comment deduplication.

const COMMENT_MARKER = '<!-- assignee-plan-comment -->';

/**
 * Format plan JSON into a readable Markdown comment body.
 * @param {string} planJsonStr - Raw plan JSON string from CLI output
 * @returns {string} Formatted Markdown body
 */
function formatPlanComment(planJsonStr) {
  if (!planJsonStr || planJsonStr.trim() === '') {
    return [
      COMMENT_MARKER,
      '## Assignee Plan',
      '',
      '> **No plan output was generated.** The intent file may be missing or the plan command encountered an error.',
      '',
      '_Generated by [assignee.ai](https://github.com/SergSlon/assignee-ai) GitHub Action_',
    ].join('\n');
  }

  let plan;
  try {
    plan = JSON.parse(planJsonStr);
  } catch {
    return [
      COMMENT_MARKER,
      '## Assignee Plan',
      '',
      '> **Error:** Could not parse plan output.',
      '',
      '```',
      planJsonStr,
      '```',
      '',
      '_Generated by [assignee.ai](https://github.com/SergSlon/assignee-ai) GitHub Action_',
    ].join('\n');
  }

  const lines = [COMMENT_MARKER, '## Assignee Plan', ''];

  // Resource table
  const resources = plan.resources || plan.desiredState || [];
  if (resources.length > 0) {
    lines.push('### Resources');
    lines.push('');
    lines.push('| Resource Type | Action | Details |');
    lines.push('|---|---|---|');
    for (const r of resources) {
      const type = r.resourceType || r.type || 'Unknown';
      const action = r.action || 'CREATE';
      const details = r.details || r.identifier || '-';
      lines.push(`| \`${type}\` | ${action} | ${details} |`);
    }
    lines.push('');
  }

  // Cost estimate
  if (plan.costEstimate || plan.cost) {
    const cost = plan.costEstimate || plan.cost;
    lines.push('### Cost Estimate');
    lines.push('');
    if (typeof cost === 'object') {
      lines.push(`- **Monthly:** ${cost.monthly || cost.monthlyEstimate || 'N/A'}`);
      lines.push(`- **Free Tier:** ${cost.freeTier ? 'Eligible' : 'Not eligible'}`);
    } else {
      lines.push(`- **Estimated:** ${cost}`);
    }
    lines.push('');
  }

  // Best practice findings
  const findings = plan.bestPractices || plan.findings || [];
  if (findings.length > 0) {
    lines.push('### Best Practice Findings');
    lines.push('');
    for (const f of findings) {
      const severity = f.severity || 'info';
      const icon = severity === 'critical' ? '🔴' : severity === 'high' ? '🟠' : severity === 'medium' ? '🟡' : '🔵';
      lines.push(`- ${icon} **${f.ruleId || f.id || 'Rule'}**: ${f.message || f.description || '-'}`);
    }
    lines.push('');
  }

  // Diff / desired state
  if (plan.diff) {
    lines.push('### Changes');
    lines.push('');
    lines.push('```diff');
    lines.push(typeof plan.diff === 'string' ? plan.diff : JSON.stringify(plan.diff, null, 2));
    lines.push('```');
    lines.push('');
  }

  lines.push('_Generated by [assignee.ai](https://github.com/SergSlon/assignee-ai) GitHub Action_');

  return lines.join('\n');
}

/**
 * Find an existing comment with the assignee plan marker.
 * @param {object} github - GitHub API client
 * @param {object} context - GitHub Actions context
 * @returns {object|null} Existing comment or null
 */
async function findExistingComment(github, context) {
  const { data: comments } = await github.rest.issues.listComments({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: context.issue.number,
    per_page: 100,
  });

  return comments.find((c) => c.body && c.body.includes(COMMENT_MARKER)) || null;
}

/**
 * Main entry point for the post-comment action step.
 * @param {object} params
 * @param {object} params.github - GitHub API client
 * @param {object} params.context - GitHub Actions context
 * @param {string} params.planJson - Raw plan JSON string
 */
async function postPlanComment({ github, context, planJson }) {
  const body = formatPlanComment(planJson);

  const existing = await findExistingComment(github, context);

  if (existing) {
    await github.rest.issues.updateComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      comment_id: existing.id,
      body,
    });
  } else {
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: context.issue.number,
      body,
    });
  }
}

// Export for testing and for actions/github-script usage
module.exports = postPlanComment;
module.exports.formatPlanComment = formatPlanComment;
module.exports.findExistingComment = findExistingComment;
module.exports.COMMENT_MARKER = COMMENT_MARKER;
