#!/usr/bin/env tsx
/**
 * generate-reference-pages.ts — W10-02 (P062 → L6-F16)
 *
 * Generates one `docs/reference/<type>.md` per supported AWS resource type
 * from the help-hints registry (`packages/core/src/config/help-hints.ts`).
 *
 * Usage:
 *   tsx scripts/generate-reference-pages.ts           # generate/update files
 *   tsx scripts/generate-reference-pages.ts --check   # exit non-zero if files would change
 *
 * The --check mode is wired into CI (Worker C wires the step in ci.yml).
 * Registry is the single source of truth (feedback_help_hints_sso).
 *
 * Each generated file carries a banner:
 *   <!-- AUTO-GENERATED by scripts/generate-reference-pages.ts — DO NOT EDIT -->
 *
 * The banner is the fingerprint `--check` uses: if any file's first line
 * does not match the banner, or if its content differs from what `generate`
 * would emit, --check fails with a non-zero exit.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as url from "node:url";

// ── Configuration ────────────────────────────────────────────────────────────

const REPO_ROOT = path.resolve(
  path.dirname(url.fileURLToPath(import.meta.url)),
  "..",
);
const REFERENCE_DIR = path.join(REPO_ROOT, "docs", "reference");
const BANNER =
  "<!-- AUTO-GENERATED by scripts/generate-reference-pages.ts — DO NOT EDIT -->";

// ── Registry import ───────────────────────────────────────────────────────────

// Dynamic import so this script can run from the repo root after `pnpm build`.
// The registry is a pure module with no I/O, so it's safe to import directly.
async function loadRegistry(): Promise<{
  types: readonly string[];
  patterns: ReadonlyArray<{
    patternId: string;
    displayName: string;
    resourceCount: number;
  }>;
}> {
  // Prefer the TypeScript source when tsx/ts-node is available (dev workflow).
  // Fall back to the compiled JS in dist for CI environments.
  const srcPath = path.join(
    REPO_ROOT,
    "packages/core/src/config/help-hints.js",
  );
  const distPath = path.join(
    REPO_ROOT,
    "packages/core/dist/config/help-hints.js",
  );

  // ts-node / tsx resolve .ts — try source-relative import first
  let mod: {
    getSupportedResourceTypes?: () => readonly string[];
    getCompoundPatterns?: () => ReadonlyArray<{
      patternId: string;
      displayName: string;
      resourceCount: number;
    }>;
  };

  try {
    // tsx transforms .ts → JS on the fly; this path works in dev
    const tsSrcPath = path.join(
      REPO_ROOT,
      "packages/core/src/config/help-hints.ts",
    );
    if (fs.existsSync(tsSrcPath)) {
      // tsx/ts-node context: dynamic import resolves .ts
      mod = await import(tsSrcPath);
    } else if (fs.existsSync(srcPath)) {
      mod = await import(srcPath);
    } else {
      mod = await import(distPath);
    }
  } catch {
    // Fallback: try the built dist
    mod = await import(distPath);
  }

  if (!mod.getSupportedResourceTypes || !mod.getCompoundPatterns) {
    throw new Error(
      "help-hints module does not export getSupportedResourceTypes or getCompoundPatterns",
    );
  }

  return {
    types: mod.getSupportedResourceTypes(),
    patterns: mod.getCompoundPatterns(),
  };
}

// ── Page generator ────────────────────────────────────────────────────────────

/**
 * Convert a CFN type string to a slug suitable for a filename.
 * "AWS::S3::Bucket" → "aws-s3-bucket"
 */
function typeToSlug(cfnType: string): string {
  return cfnType
    .replace(/^AWS::/, "")
    .replace(/::/g, "-")
    .toLowerCase();
}

/**
 * Generate the markdown content for a single resource-type reference page.
 */
function generatePage(cfnType: string): string {
  const slug = typeToSlug(cfnType);
  const [_aws, service, resourceName] = cfnType.split("::");

  return [
    BANNER,
    "",
    `# ${cfnType}`,
    "",
    `**CloudFormation type**: \`${cfnType}\`  `,
    `**Service**: ${service ?? "Unknown"}  `,
    `**Resource**: ${resourceName ?? "Unknown"}  `,
    `**Slug**: \`${slug}\``,
    "",
    "## Overview",
    "",
    `This page is the reference entry for \`${cfnType}\` as supported by Assignee.ai.`,
    "It is auto-generated from the supported-types registry — edit",
    "`packages/core/src/config/resource-types/supported.ts` or the plugin at",
    "`packages/core/src/plugins/` to update the authoritative source.",
    "",
    "## Assignee.ai support",
    "",
    `Assignee.ai provisions \`${cfnType}\` resources via the AWS CloudControl API.`,
    "A dedicated plugin handles schema elicitation, default injection, and",
    "best-practice rule evaluation for this type.",
    "",
    "### Typical intent examples",
    "",
    `\`\`\`bash`,
    `assignee plan "Create a ${resourceName ?? cfnType}"`,
    `assignee apply "Create a ${resourceName ?? cfnType} named my-${slug}"`,
    `\`\`\``,
    "",
    "### Best-practice rules",
    "",
    "Best-practice rules for this type are defined in",
    "`packages/best-practices/rules/`. Run `assignee plan` to see which rules",
    "apply to your specific configuration.",
    "",
    "### Pricing",
    "",
    "Assignee.ai fetches real-time pricing from the AWS Pricing MCP at plan time.",
    "No hardcoded dollar amounts are stored in this file.",
    "",
    "## Further reading",
    "",
    `- [AWS CloudFormation documentation for ${cfnType}](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-${service?.toLowerCase()}-${resourceName?.toLowerCase()}.html)`,
    "- [`docs/reference/README.md`](README.md) — Reference quadrant overview",
    "- [`docs/how-to/quickstart.md`](../how-to/quickstart.md) — Getting started",
    "",
  ].join("\n");
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const checkMode = process.argv.includes("--check");
  const registry = await loadRegistry();

  if (!fs.existsSync(REFERENCE_DIR)) {
    if (checkMode) {
      console.error(
        `[generate-reference-pages] ERROR: ${REFERENCE_DIR} does not exist`,
      );
      process.exit(1);
    }
    fs.mkdirSync(REFERENCE_DIR, { recursive: true });
  }

  let hasDiff = false;
  const generatedSlugs = new Set<string>();

  for (const cfnType of registry.types) {
    const slug = typeToSlug(cfnType);
    const filePath = path.join(REFERENCE_DIR, `${slug}.md`);
    const content = generatePage(cfnType);
    generatedSlugs.add(`${slug}.md`);

    if (checkMode) {
      if (!fs.existsSync(filePath)) {
        console.error(`[generate-reference-pages] MISSING: ${filePath}`);
        hasDiff = true;
      } else {
        const existing = fs.readFileSync(filePath, "utf-8");
        if (existing !== content) {
          console.error(`[generate-reference-pages] STALE: ${filePath}`);
          hasDiff = true;
        }
      }
    } else {
      fs.writeFileSync(filePath, content, "utf-8");
      console.log(
        `[generate-reference-pages] wrote: ${path.relative(REPO_ROOT, filePath)}`,
      );
    }
  }

  // Check for stale auto-generated files in check mode
  if (checkMode) {
    const existingFiles = fs
      .readdirSync(REFERENCE_DIR)
      .filter((f) => f.endsWith(".md") && f !== "README.md");
    for (const f of existingFiles) {
      const fullPath = path.join(REFERENCE_DIR, f);
      const firstLine = fs.readFileSync(fullPath, "utf-8").split("\n")[0] ?? "";
      if (firstLine === BANNER && !generatedSlugs.has(f)) {
        console.error(
          `[generate-reference-pages] ORPHAN: ${fullPath} (no longer in registry)`,
        );
        hasDiff = true;
      }
    }
  }

  if (checkMode) {
    if (hasDiff) {
      console.error(
        "[generate-reference-pages] --check FAILED: committed reference pages are stale. Run: tsx scripts/generate-reference-pages.ts",
      );
      process.exit(1);
    } else {
      console.log(
        `[generate-reference-pages] --check PASSED: ${registry.types.length} pages up to date`,
      );
    }
  } else {
    console.log(
      `[generate-reference-pages] done: ${registry.types.length} pages written to ${REFERENCE_DIR}`,
    );
  }
}

main().catch((err) => {
  console.error("[generate-reference-pages] fatal:", err);
  process.exit(1);
});
