#!/usr/bin/env node
/**
 * generate-notice.ts — W10-08 (P074 → L3-F19)
 *
 * Generates NOTICE and THIRD-PARTY-NOTICES.md from the pnpm dependency tree.
 * Uses `pnpm licenses list --json` as the data source.
 *
 * Usage:
 *   node scripts/generate-notice.ts           # generate/update NOTICE files
 *   node scripts/generate-notice.ts --check   # exit non-zero if files would change
 *
 * The --check mode is wired into CI (Worker C wires in ci.yml).
 *
 * Format: SPDX-compatible markdown. Packages grouped by SPDX license ID.
 * Note: Full SPDX-format validation tooling (spdx-tools, etc.) is not yet
 * wired; we emit SPDX expressions as-reported by pnpm and document the
 * package-level SPDX ID per package. Full SPDX document validation can be
 * added in a future epic once spdx-tools is in the dev-dependencies.
 *
 * WARNING: DO NOT import from @assignee/core or workspace packages here.
 * This script runs at CI pre-check time before the workspace packages
 * are necessarily built.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as url from "node:url";
import * as child_process from "node:child_process";

// ── Configuration ────────────────────────────────────────────────────────────

const REPO_ROOT = path.resolve(
  path.dirname(url.fileURLToPath(import.meta.url)),
  "..",
);

const NOTICE_PATH = path.join(REPO_ROOT, "NOTICE");
const THIRD_PARTY_PATH = path.join(REPO_ROOT, "THIRD-PARTY-NOTICES.md");

const NOTICE_BANNER =
  "<!-- AUTO-GENERATED by scripts/generate-notice.ts — DO NOT EDIT MANUALLY -->";

// ── Types ─────────────────────────────────────────────────────────────────────

interface PnpmLicenseEntry {
  name: string;
  versions?: string[];
  license?: string;
  homepage?: string;
}

interface PackageInfo {
  name: string;
  versions: string[];
  license: string;
  homepage: string;
}

// ── pnpm licenses fetcher ─────────────────────────────────────────────────────

function fetchLicenses(): PackageInfo[] {
  let stdout: string;
  try {
    stdout = child_process.execSync("pnpm licenses list --json", {
      cwd: REPO_ROOT,
      encoding: "utf-8",
      timeout: 60_000,
    });
  } catch (err) {
    throw new Error(
      `Failed to run 'pnpm licenses list --json': ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  let data: Record<string, PnpmLicenseEntry[]>;
  try {
    data = JSON.parse(stdout) as Record<string, PnpmLicenseEntry[]>;
  } catch {
    throw new Error("Failed to parse pnpm licenses list --json output as JSON");
  }

  const packages: PackageInfo[] = [];
  const seen = new Set<string>();

  for (const [licenseId, entries] of Object.entries(data)) {
    for (const entry of entries) {
      const key = `${entry.name}::${licenseId}`;
      if (seen.has(key)) continue;
      seen.add(key);
      packages.push({
        name: entry.name,
        versions: entry.versions ?? [],
        license: licenseId,
        homepage: entry.homepage ?? "",
      });
    }
  }

  packages.sort((a, b) => a.name.localeCompare(b.name));
  return packages;
}

// ── Content generators ────────────────────────────────────────────────────────

function generateNotice(packages: PackageInfo[], date: string): string {
  return [
    "NOTICE",
    "======",
    "",
    "Assignee.ai",
    "Copyright 2024-2026 Assignee.ai Contributors",
    "",
    "This product includes software developed by third parties.",
    "See THIRD-PARTY-NOTICES.md for details.",
    "",
    `Generated: ${date}`,
    `Total third-party packages: ${packages.length}`,
    "",
    "SPDX-License-Identifier: MIT",
    "",
  ].join("\n");
}

function generateThirdPartyNotices(
  packages: PackageInfo[],
  date: string,
): string {
  // Group by license
  const byLicense = new Map<string, PackageInfo[]>();
  for (const pkg of packages) {
    const group = byLicense.get(pkg.license) ?? [];
    group.push(pkg);
    byLicense.set(pkg.license, group);
  }

  const lines: string[] = [
    NOTICE_BANNER,
    "<!-- Run: node scripts/generate-notice.ts to update -->",
    "",
    "# Third-Party Notices",
    "",
    "Assignee.ai incorporates the following open-source software packages.",
    "All packages are used under their respective licenses as listed below.",
    "",
    `Generated: ${date}  `,
    `Total packages: ${packages.length}`,
    "",
    "---",
    "",
    "## License Summary",
    "",
  ];

  for (const licenseId of [...byLicense.keys()].sort()) {
    const pkgs = (byLicense.get(licenseId) ?? []).sort((a, b) =>
      a.name.localeCompare(b.name),
    );
    const plural = pkgs.length === 1 ? "package" : "packages";
    lines.push(`### ${licenseId} (${pkgs.length} ${plural})`);
    lines.push("");
    for (const pkg of pkgs) {
      const version = pkg.versions.join(", ") || "unknown";
      const homepage = pkg.homepage;
      if (homepage) {
        lines.push(
          `- **${pkg.name}** \`${version}\` — [${homepage}](${homepage})`,
        );
      } else {
        lines.push(`- **${pkg.name}** \`${version}\``);
      }
    }
    lines.push("");
  }

  lines.push(
    "---",
    "",
    "## Full SPDX-Compatible Declaration",
    "",
    "Each package listed above carries an SPDX expression in the License Summary.",
    "For the full text of each license, visit the [SPDX license list](https://spdx.org/licenses/).",
    "",
  );

  return lines.join("\n");
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const checkMode = process.argv.includes("--check");
  const date = new Date().toISOString().slice(0, 10);

  const packages = fetchLicenses();
  const noticeContent = generateNotice(packages, date);
  const thirdPartyContent = generateThirdPartyNotices(packages, date);

  if (checkMode) {
    let hasDiff = false;

    for (const [filePath, expected] of [
      [NOTICE_PATH, noticeContent],
      [THIRD_PARTY_PATH, thirdPartyContent],
    ] as [string, string][]) {
      if (!fs.existsSync(filePath)) {
        console.error(`[generate-notice] MISSING: ${filePath}`);
        hasDiff = true;
      } else {
        const existing = fs.readFileSync(filePath, "utf-8");
        // For check mode, compare everything except the generated date line
        // (date changes daily but content is otherwise stable).
        const normalize = (s: string) =>
          s.replace(/^Generated: \d{4}-\d{2}-\d{2}/m, "Generated: DATE").trim();
        if (normalize(existing) !== normalize(expected)) {
          console.error(`[generate-notice] STALE: ${filePath}`);
          hasDiff = true;
        }
      }
    }

    if (hasDiff) {
      console.error(
        "[generate-notice] --check FAILED: NOTICE files are stale. Run: node scripts/generate-notice.ts",
      );
      process.exit(1);
    } else {
      console.log(
        `[generate-notice] --check PASSED: ${packages.length} packages, files up to date`,
      );
    }
  } else {
    fs.writeFileSync(NOTICE_PATH, noticeContent, "utf-8");
    console.log(
      `[generate-notice] wrote: NOTICE (${packages.length} packages)`,
    );

    fs.writeFileSync(THIRD_PARTY_PATH, thirdPartyContent, "utf-8");
    console.log(`[generate-notice] wrote: THIRD-PARTY-NOTICES.md`);
  }
}

main().catch((err) => {
  console.error("[generate-notice] fatal:", err);
  process.exit(1);
});
