#!/usr/bin/env tsx
/**
 * generate-reference-pages.ts
 *
 * Generates one `docs/reference/<type>.md` per supported AWS resource type
 * from the help-hints registry (`packages/core/src/config/help-hints.ts`).
 *
 * Usage:
 *   tsx scripts/generate-reference-pages.ts           # generate/update files
 *   tsx scripts/generate-reference-pages.ts --check   # exit non-zero if files would change
 *
 * The --check mode is wired into CI. The registry is the single source of
 * truth — never hand-edit a generated page.
 *
 * Each generated file carries a banner:
 *   <!-- AUTO-GENERATED by scripts/generate-reference-pages.ts — DO NOT EDIT -->
 *
 * The banner is the fingerprint `--check` uses: if any file's first line
 * does not match the banner, or if its content differs from what `generate`
 * would emit, --check fails with a non-zero exit.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as url from "node:url";

// ── Configuration ────────────────────────────────────────────────────────────

const REPO_ROOT = path.resolve(
  path.dirname(url.fileURLToPath(import.meta.url)),
  "..",
);
const REFERENCE_DIR = path.join(REPO_ROOT, "docs", "reference");
const BANNER =
  "<!-- AUTO-GENERATED by scripts/generate-reference-pages.ts — DO NOT EDIT -->";

// ── Registry import ───────────────────────────────────────────────────────────

// Dynamic import so this script can run from the repo root after `pnpm build`.
// The registry is a pure module with no I/O, so it's safe to import directly.
async function loadRegistry(): Promise<{
  types: readonly string[];
  patterns: ReadonlyArray<{
    patternId: string;
    displayName: string;
    resourceCount: number;
  }>;
}> {
  // Prefer the TypeScript source when tsx/ts-node is available (dev workflow).
  // Fall back to the compiled JS in dist for CI environments.
  const srcPath = path.join(
    REPO_ROOT,
    "packages/core/src/config/help-hints.js",
  );
  const distPath = path.join(
    REPO_ROOT,
    "packages/core/dist/config/help-hints.js",
  );

  // ts-node / tsx resolve .ts — try source-relative import first
  let mod: {
    getSupportedResourceTypes?: () => readonly string[];
    getCompoundPatterns?: () => ReadonlyArray<{
      patternId: string;
      displayName: string;
      resourceCount: number;
    }>;
  };

  try {
    // tsx transforms .ts → JS on the fly; this path works in dev
    const tsSrcPath = path.join(
      REPO_ROOT,
      "packages/core/src/config/help-hints.ts",
    );
    // Windows: ESM dynamic import() requires `file://` URL form for absolute
    // paths (raw `D:\...` rejected with "Only URLs with a scheme in: file,
    // data, and node are supported"). `pathToFileURL` is a no-op on POSIX.
    if (fs.existsSync(tsSrcPath)) {
      // tsx/ts-node context: dynamic import resolves .ts
      mod = await import(url.pathToFileURL(tsSrcPath).href);
    } else if (fs.existsSync(srcPath)) {
      mod = await import(url.pathToFileURL(srcPath).href);
    } else {
      mod = await import(url.pathToFileURL(distPath).href);
    }
  } catch {
    // Fallback: try the built dist
    mod = await import(url.pathToFileURL(distPath).href);
  }

  if (!mod.getSupportedResourceTypes || !mod.getCompoundPatterns) {
    throw new Error(
      "help-hints module does not export getSupportedResourceTypes or getCompoundPatterns",
    );
  }

  return {
    types: mod.getSupportedResourceTypes(),
    patterns: mod.getCompoundPatterns(),
  };
}

// ── Page generator ────────────────────────────────────────────────────────────

/**
 * Convert a CFN type string to a slug suitable for a filename.
 * "AWS::S3::Bucket" → "aws-s3-bucket"
 */
function typeToSlug(cfnType: string): string {
  return cfnType
    .replace(/^AWS::/, "")
    .replace(/::/g, "-")
    .toLowerCase();
}

/**
 * Compound-only types that have NO dedicated plugin file. These are
 * provisioned inline by their parent resource (or by the generic plugin)
 * rather than by a dedicated plugin under `resource-plugins/plugins/`.
 *
 * Source of truth: `packages/core/src/resource-plugins/index.ts` — any
 * supported CFN type whose plugin file is NOT registered there is compound-
 * only.
 */
const COMPOUND_ONLY_TYPES = new Set<string>([
  "AWS::EC2::VPCGatewayAttachment",
  "AWS::EC2::SubnetRouteTableAssociation",
]);

/**
 * Map CFN service token to the matching directory under
 * `packages/best-practices/`. The CFN service name doesn't always match
 * the BP directory name (e.g. `ElasticLoadBalancingV2` → `elbv2`,
 * `ApiGatewayV2` → `apigateway`). Returns null if no per-service
 * directory is appropriate (caller falls back to a generalised path).
 */
function bpDirForService(service: string): string | null {
  const map: Record<string, string> = {
    ApiGatewayV2: "apigateway",
    AutoScaling: "autoscaling",
    CloudFront: "cloudfront",
    CloudWatch: "cloudwatch",
    DynamoDB: "dynamodb",
    EC2: "ec2",
    ECR: "ecr",
    ECS: "ecs",
    EFS: "efs",
    ElasticLoadBalancingV2: "elbv2",
    Events: "events",
    IAM: "iam",
    KMS: "kms",
    Lambda: "lambda",
    Logs: "logs",
    RDS: "rds",
    S3: "s3",
    SecretsManager: "secretsmanager",
    SNS: "sns",
    SQS: "sqs",
    SSM: "ssm",
    // VPC rules live under `vpc/` even though VPC resources have CFN
    // service token `EC2`; keep the EC2 mapping above as the default
    // for VPC-namespaced types.
  };
  return map[service] ?? null;
}

/**
 * Curated per-type intent phrases used in the "Typical intent examples"
 * block. Without curation we'd render awkward strings like
 * "Create a EIP" or "Create a Api"; the lookup keeps idiomatic English
 * for composite type names.
 *
 * Each entry returns the noun phrase only (no leading "Create a/an"). The
 * generator wraps it in `Create <phrase>` so we can encode the article
 * once at the call site.
 */
function intentPhrase(cfnType: string): string {
  const map: Record<string, string> = {
    "AWS::S3::Bucket": "an S3 bucket",
    "AWS::S3::BucketPolicy": "an S3 bucket policy",
    "AWS::SSM::Parameter": "an SSM parameter",
    "AWS::IAM::Role": "an IAM role",
    "AWS::EC2::Instance": "an EC2 instance",
    "AWS::EC2::VPC": "a VPC",
    "AWS::EC2::Subnet": "a subnet",
    "AWS::EC2::SecurityGroup": "a security group",
    "AWS::EC2::InternetGateway": "an internet gateway",
    "AWS::EC2::RouteTable": "a route table",
    "AWS::EC2::Route": "a route",
    "AWS::EC2::NatGateway": "a NAT gateway",
    "AWS::EC2::EIP": "an Elastic IP",
    "AWS::EC2::VPCGatewayAttachment": "a VPC gateway attachment",
    "AWS::EC2::SubnetRouteTableAssociation": "a subnet route-table association",
    "AWS::RDS::DBInstance": "a Postgres database",
    "AWS::RDS::DBSubnetGroup": "a DB subnet group",
    "AWS::Lambda::Function": "a Lambda function",
    "AWS::DynamoDB::Table": "a DynamoDB table",
    "AWS::SQS::Queue": "an SQS queue",
    "AWS::SNS::Topic": "an SNS topic",
    "AWS::SNS::Subscription": "an SNS subscription",
    "AWS::ElasticLoadBalancingV2::LoadBalancer": "a load balancer",
    "AWS::ECS::Cluster": "an ECS cluster",
    "AWS::ECR::Repository": "an ECR repository",
    "AWS::Logs::LogGroup": "a CloudWatch log group",
    "AWS::ApiGatewayV2::Api": "a WebSocket API",
    "AWS::CloudWatch::Alarm": "a CloudWatch alarm",
    "AWS::SecretsManager::Secret": "a secret",
    "AWS::EFS::FileSystem": "an EFS file system",
    "AWS::EFS::MountTarget": "an EFS mount target",
    "AWS::Events::Rule": "an EventBridge rule",
    "AWS::Events::EventBus": "an EventBridge bus",
    "AWS::Events::Connection": "an EventBridge connection",
    "AWS::Events::ApiDestination": "an EventBridge API destination",
    "AWS::KMS::Key": "a KMS key",
    "AWS::CloudFront::Distribution": "a CloudFront distribution",
    "AWS::CloudFront::OriginAccessControl":
      "a CloudFront origin access control",
  };
  return map[cfnType] ?? `a ${cfnType.split("::").pop() ?? cfnType}`;
}

/**
 * Generate the markdown content for a single resource-type reference page.
 *
 * TODO (deferred): extend the generator to import each plugin and emit a
 * fields table from its `commonFields` schema (`commonFields[].name`,
 * `.question.label`, `.question.hint`, default values). Today's pages
 * only describe the type; the plugin's elicited fields are documented
 * elsewhere. This is a larger lift (requires loading every plugin's
 * compiled module) and is tracked separately.
 */
/**
 * Compound-only types are not directly addressable via a user intent —
 * they are emitted only by compound patterns (e.g. vpc-networking).
 * Their reference page replaces the user-intent example with an
 * actionable callout pointing at the parent compound.
 */
const COMPOUND_ONLY_CALLOUT: Record<string, string> = {
  "AWS::EC2::VPCGatewayAttachment":
    "> [!NOTE]\n> Compound-only — provisioned via the `vpc-networking` pattern, not by direct intent. See [`../resource-types.md`](../resource-types.md#vpc-networking) for the parent compound.",
  "AWS::EC2::SubnetRouteTableAssociation":
    "> [!NOTE]\n> Compound-only — provisioned via the `vpc-networking` pattern, not by direct intent. See [`../resource-types.md`](../resource-types.md#vpc-networking) for the parent compound.",
};

function generatePage(cfnType: string): string {
  const slug = typeToSlug(cfnType);
  const [_aws, service, resourceName] = cfnType.split("::");
  const isCompoundOnly = COMPOUND_ONLY_TYPES.has(cfnType);
  const phrase = intentPhrase(cfnType);
  const bpDir = service ? bpDirForService(service) : null;

  const supportSentence = isCompoundOnly
    ? "This type has no dedicated plugin; it is handled inline by the parent resource (or by the generic plugin) during compound provisioning. It is not directly elicited from a top-level intent."
    : "A dedicated plugin handles schema elicitation, default injection, and best-practice rule evaluation for this type.";

  const bpRulesSentence = bpDir
    ? `Best-practice rules for this type live under \`packages/best-practices/${bpDir}/\` (per-service subdirectories). Run \`assignee infra plan\` to see which rules apply to your specific configuration.`
    : "Best-practice rules for this type live under `packages/best-practices/` (per-service subdirectories: `s3/`, `lambda/`, `iam/`, etc.). Run `assignee infra plan` to see which rules apply to your specific configuration.";

  // For compound-only types, replace the user-intent example with the
  // compound-only callout — the example "assignee infra plan \"Create a VPC
  // gateway attachment\"" was actively misleading because that intent
  // resolves to a parent type, never to the compound-only resource.
  const intentBlock = isCompoundOnly
    ? (COMPOUND_ONLY_CALLOUT[cfnType] ??
      "> [!NOTE]\n> Compound-only — provisioned via a parent compound pattern, not by direct intent.")
    : [
        `\`\`\`bash`,
        `assignee infra plan "Create ${phrase}"`,
        `assignee infra apply "Create ${phrase} named my-${slug}"`,
        `\`\`\``,
      ].join("\n");

  return [
    BANNER,
    "",
    `# ${cfnType}`,
    "",
    `**CloudFormation type**: \`${cfnType}\`  `,
    `**Service**: ${service ?? "Unknown"}  `,
    `**Resource**: ${resourceName ?? "Unknown"}  `,
    `**Slug**: \`${slug}\``,
    "",
    "## Overview",
    "",
    `This page is the reference entry for \`${cfnType}\` as supported by Assignee.ai.`,
    "It is auto-generated from the supported-types registry — edit",
    "`packages/core/src/config/resource-types/supported.ts` or the plugin at",
    "`packages/core/src/resource-plugins/plugins/` to update the authoritative source.",
    "",
    "## Assignee.ai support",
    "",
    `Assignee.ai provisions \`${cfnType}\` resources via the AWS CloudControl API.`,
    supportSentence,
    "",
    "### Typical intent examples",
    "",
    intentBlock,
    "",
    "### Best-practice rules",
    "",
    bpRulesSentence,
    "",
    "### Pricing",
    "",
    "Assignee.ai fetches real-time pricing from the AWS Pricing MCP at plan time.",
    "No hardcoded dollar amounts are stored in this file.",
    "",
    "## Further reading",
    "",
    `- [AWS CloudFormation documentation for ${cfnType}](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-${service?.toLowerCase()}-${resourceName?.toLowerCase()}.html)`,
    "- [`docs/reference/README.md`](README.md) — Reference quadrant overview",
    "- [`docs/how-to/quickstart.md`](../how-to/quickstart.md) — Getting started",
    "",
  ].join("\n");
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const checkMode = process.argv.includes("--check");
  const registry = await loadRegistry();

  if (!fs.existsSync(REFERENCE_DIR)) {
    if (checkMode) {
      console.error(
        `[generate-reference-pages] ERROR: ${REFERENCE_DIR} does not exist`,
      );
      process.exit(1);
    }
    fs.mkdirSync(REFERENCE_DIR, { recursive: true });
  }

  let hasDiff = false;
  const generatedSlugs = new Set<string>();

  for (const cfnType of registry.types) {
    const slug = typeToSlug(cfnType);
    const filePath = path.join(REFERENCE_DIR, `${slug}.md`);
    const content = generatePage(cfnType);
    generatedSlugs.add(`${slug}.md`);

    if (checkMode) {
      if (!fs.existsSync(filePath)) {
        console.error(`[generate-reference-pages] MISSING: ${filePath}`);
        hasDiff = true;
      } else {
        const existing = fs.readFileSync(filePath, "utf-8");
        if (existing !== content) {
          console.error(`[generate-reference-pages] STALE: ${filePath}`);
          hasDiff = true;
        }
      }
    } else {
      fs.writeFileSync(filePath, content, "utf-8");
      console.log(
        `[generate-reference-pages] wrote: ${path.relative(REPO_ROOT, filePath)}`,
      );
    }
  }

  // Check for stale auto-generated files in check mode
  if (checkMode) {
    const existingFiles = fs
      .readdirSync(REFERENCE_DIR)
      .filter((f) => f.endsWith(".md") && f !== "README.md");
    for (const f of existingFiles) {
      const fullPath = path.join(REFERENCE_DIR, f);
      const firstLine = fs.readFileSync(fullPath, "utf-8").split("\n")[0] ?? "";
      if (firstLine === BANNER && !generatedSlugs.has(f)) {
        console.error(
          `[generate-reference-pages] ORPHAN: ${fullPath} (no longer in registry)`,
        );
        hasDiff = true;
      }
    }
  }

  if (checkMode) {
    if (hasDiff) {
      console.error(
        "[generate-reference-pages] --check FAILED: committed reference pages are stale. Run: tsx scripts/generate-reference-pages.ts",
      );
      process.exit(1);
    } else {
      console.log(
        `[generate-reference-pages] --check PASSED: ${registry.types.length} pages up to date`,
      );
    }
  } else {
    console.log(
      `[generate-reference-pages] done: ${registry.types.length} pages written to ${REFERENCE_DIR}`,
    );
  }
}

main().catch((err) => {
  console.error("[generate-reference-pages] fatal:", err);
  process.exit(1);
});
