// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText, billingSessionResponse } from "./_helpers.js";

/** Captured 2026-04-10 from billing-cost-management-mcp-server@0.0.17. S3 service cost for current month. */
export const s3BucketCost = {
  success: billingSessionResponse([
    {
      TimePeriod: { Start: "2026-04-01", End: "2026-05-01" },
      Groups: [
        {
          Keys: ["Amazon Simple Storage Service"],
          Metrics: {
            UnblendedCost: { Amount: "0.023", Unit: "USD" },
          },
        },
      ],
      Total: {},
      Estimated: true,
    },
  ]),
} as const;

/** Captured 2026-04-10. Multiple services (S3 + Lambda) cost data grouped by SERVICE. */
export const multiResourceCost = {
  success: billingSessionResponse([
    {
      TimePeriod: { Start: "2026-04-01", End: "2026-05-01" },
      Groups: [
        {
          Keys: ["Amazon Simple Storage Service"],
          Metrics: {
            UnblendedCost: { Amount: "0.023", Unit: "USD" },
          },
        },
        {
          Keys: ["AWS Lambda"],
          Metrics: {
            UnblendedCost: { Amount: "1.47", Unit: "USD" },
          },
        },
      ],
      Total: {},
      Estimated: true,
    },
  ]),
} as const;

/** Captured 2026-04-10. Empty response — no cost data for the queried services. */
export const noCostData = {
  success: billingSessionResponse([
    {
      TimePeriod: { Start: "2026-04-01", End: "2026-05-01" },
      Groups: [],
      Total: {},
      Estimated: true,
    },
  ]),
} as const;

/** Captured 2026-04-10. Cost forecast (still uses mcpText format — getCostForecast operation). */
export const costForecast = {
  success: mcpText({
    Total: {
      Amount: "3.50",
      Unit: "USD",
    },
    ForecastResultsByTime: [
      {
        TimePeriod: { Start: "2026-04-10", End: "2026-05-01" },
        MeanValue: "3.50",
        PredictionIntervalLowerBound: "2.80",
        PredictionIntervalUpperBound: "4.20",
      },
    ],
  }),
} as const;
