// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.

/** Captured 2026-03-22. read_sections on CFN DynamoDB Table page. Truncated from 20K chars. */
export const dynamoDbBillingMode = {
  success: {
    result: `## Syntax

To declare this entity in your CloudFormation template, use the following syntax:

### JSON

\`\`\`
{
  "Type" : "AWS::DynamoDB::Table",
  "Properties" : {
      "AttributeDefinitions" : [ AttributeDefinition, ... ],
      "BillingMode" : String,
      "ContributorInsightsSpecification" : ContributorInsightsSpecification,
      "DeletionProtectionEnabled" : Boolean,
      "GlobalSecondaryIndexes" : [ GlobalSecondaryIndex, ... ],
      "ImportSourceSpecification" : ImportSourceSpecification,
      "KeySchema" : [ KeySchema, ... ],
      "KinesisStreamSpecification" : KinesisStreamSpecification,
      "LocalSecondaryIndexes" : [ LocalSecondaryIndex, ... ],
      "OnDemandThroughput" : OnDemandThroughput,
      "PointInTimeRecoverySpecification" : PointInTimeRecoverySpecification,
      "ProvisionedThroughput" : ProvisionedThroughput,
      "ResourcePolicy" : ResourcePolicy,
      "SSESpecification" : SSESpecification,
      "StreamSpecification" : StreamSpecification,
      "TableClass" : String,
      "TableName" : String,
      "Tags" : [ Tag, ... ],
      "TimeToLiveSpecification" : TimeToLiveSpecification,
      "WarmThroughput" : WarmThroughput
    }
}
\`\`\`

### YAML

\`\`\`
Type: AWS::DynamoDB::Table
Properties:
  AttributeDefinitions: 
    - AttributeDefinition
  BillingMode: String
  ContributorInsightsSpecification: 
    ContributorInsightsSpecification
  DeletionProtectionEnabled: Boolean
  GlobalSecondaryIndexes: 
    - GlobalSecondaryIndex
  ImportSourceSpecification: 
    ImportSourceSpecification
  KeySchema: 
    - KeySchema
  KinesisStreamSpecification: 
    KinesisStreamSpecification
  LocalSecondaryIndexes: 
    - LocalSecondaryIndex
  OnDemandThroughput: 
    OnDemandThroughput
  PointInTimeRecoverySpecification: 
    PointInTimeRecoverySpecification
  ProvisionedThroughput: 
    ProvisionedThroughput
  ResourcePolicy: 
    ResourcePolicy
  SSESpecification: 
    SSESpecification
  StreamSpecification: 
    StreamSpecification
  TableClass: Stri

[Content truncated for test fixture]`,
  },
} as const;
