// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 from aws-documentation-mcp-server read_documentation. Full S3 Bucket page, truncated from 5K chars. */
export const s3BucketFull = {
  success: {
    result: `AWS Documentation from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html:

This is the new *CloudFormation Template Reference Guide*.
Please update your bookmarks and links. For help getting started with CloudFormation, see the
[AWS CloudFormation User Guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html").

# AWS::S3::Bucket

The \`AWS::S3::Bucket\` resource creates an Amazon S3 bucket in the same AWS Region where you create the AWS CloudFormation stack.

To control how AWS CloudFormation handles the bucket when the stack is
deleted, you can set a deletion policy for your bucket. You can choose to
*retain* the bucket or to *delete* the bucket. For
more information, see [DeletionPolicy
Attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html").

###### Important

You can only delete empty buckets. Deletion fails for buckets that have contents.

## Syntax

To declare this entity in your CloudFormation template, use the following syntax:

### JSON

\`\`\`
{
  "Type" : "AWS::S3::Bucket",
  "Properties" : {
      "AbacStatus" : String,
      "AccelerateConfiguration" : AccelerateConfiguration,
      "AccessControl" : String,
      "AnalyticsConfigurations" : [ AnalyticsConfiguration, ... ],
      "BucketEncryption" : BucketEncryption,
      "BucketName" : String,
      "BucketNamePrefix" : String,
      "BucketNamespace" : String,
      "CorsConfiguration" : CorsConfiguration,
      "IntelligentTieringConfigurations" : [ IntelligentTieringConfiguration, ... ],
      "InventoryConfigurations" : [ InventoryConfiguration, ... ],
      "LifecycleConfiguration" : LifecycleConfiguration,
      "LoggingConfiguration" : LoggingConfiguration,
      "MetadataConfiguration" : MetadataConfiguration,
      "MetadataTableConfiguration" : MetadataTableConfiguration,
      "MetricsConfigurations" : [ MetricsConfiguration, ... ],
      "NotificationConfiguration" : NotificationConfiguration,
      "ObjectLockConfiguration" : ObjectLockConfiguration,
      "ObjectLockEnabled" : Boolean,
      "OwnershipControls" : OwnershipControls,
      "PublicAccessBlockConfiguration" : PublicAccessBlockConfiguration,
      "ReplicationConfiguration" : ReplicationConfiguration,
      "Tags" : [ Tag, ... ],
      "VersioningConfiguration" : VersioningConfiguration,
      "WebsiteConfiguration" : WebsiteConfiguration
    }
}
\`\`\`

### YAML

\`\`\`
Type: AWS::S3::Bucket
Properties:
  AbacStatus: String
  AccelerateConfiguration: 
    AccelerateConfiguration
  AccessControl: String
  AnalyticsConfigurations: 
    - AnalyticsConfiguration
  BucketEncryption: 
    BucketEncryption
  BucketName: String
  BucketNamePrefix: String
  BucketNamespace: String
  CorsConfiguration: 
    CorsConfiguration
  Inte

[Content truncated for test fixture]`,
  },
} as const;

/** Captured 2026-03-22. Full Lambda Function page, truncated from 5K chars. */
export const lambdaFunctionFull = {
  success: {
    result: `AWS Documentation from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html:

This is the new *CloudFormation Template Reference Guide*.
Please update your bookmarks and links. For help getting started with CloudFormation, see the
[AWS CloudFormation User Guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html").

# AWS::Lambda::Function

The \`AWS::Lambda::Function\` resource creates a Lambda function. To create a function, you need a
[deployment package](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html "https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html") and an
[execution role](https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html "https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html").
The deployment package is a .zip file archive or container image that contains your function code.
The execution role grants the function permission to use AWS services, such as Amazon CloudWatch Logs
for log streaming and AWS X-Ray for request tracing.

You set the package type to \`Image\` if the deployment package is a
[container image](https://docs.aws.amazon.com/lambda/latest/dg/lambda-images.html "https://docs.aws.amazon.com/lambda/latest/dg/lambda-images.html"). For these functions,
include the URI of the container image in the Amazon ECR registry in the [\`ImageUri\` property of the \`Code\` property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-imageuri "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-imageuri"). You do not need to specify the handler and
runtime properties.

You set the package type to \`Zip\` if the deployment package is a [.zip file archive](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html#gettingstarted-package-zip "https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html#gettingstarted-package-zip").
For these functions, specify the Amazon S3 location of your .zip file in the \`Code\` property.
Alternatively, for Node.js and Python functions, you can define your function inline in the [\`ZipFile\` property of the \`Code\` property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile"). In both cases, you must also specify the
handler and runtime properties.

You can use [code signing](https://docs.aws.amazon.com/lambda/latest/dg/configuration-codesigning.html "https://docs.aws.amazon.com/lambda/latest/dg/configuration-codesigning.html")
if your deployment package is a .zip file archive. T

[Content truncated for test fixture]`,
  },
} as const;

/** Synthetic: empty page — edge case. */
export const emptyPage = {
  success: { result: "" },
} as const;
