// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.

/** Captured 2026-03-22 from aws-documentation-mcp-server read_sections. Input: { url: CFN S3 Bucket page, section_titles: [Overview,Description,Properties,Syntax] }. Truncated from 24K chars. */
export const s3BucketName = {
  success: {
    result: `## Syntax

To declare this entity in your CloudFormation template, use the following syntax:

### JSON

\`\`\`
{
  "Type" : "AWS::S3::Bucket",
  "Properties" : {
      "AbacStatus" : String,
      "AccelerateConfiguration" : AccelerateConfiguration,
      "AccessControl" : String,
      "AnalyticsConfigurations" : [ AnalyticsConfiguration, ... ],
      "BucketEncryption" : BucketEncryption,
      "BucketName" : String,
      "BucketNamePrefix" : String,
      "BucketNamespace" : String,
      "CorsConfiguration" : CorsConfiguration,
      "IntelligentTieringConfigurations" : [ IntelligentTieringConfiguration, ... ],
      "InventoryConfigurations" : [ InventoryConfiguration, ... ],
      "LifecycleConfiguration" : LifecycleConfiguration,
      "LoggingConfiguration" : LoggingConfiguration,
      "MetadataConfiguration" : MetadataConfiguration,
      "MetadataTableConfiguration" : MetadataTableConfiguration,
      "MetricsConfigurations" : [ MetricsConfiguration, ... ],
      "NotificationConfiguration" : NotificationConfiguration,
      "ObjectLockConfiguration" : ObjectLockConfiguration,
      "ObjectLockEnabled" : Boolean,
      "OwnershipControls" : OwnershipControls,
      "PublicAccessBlockConfiguration" : PublicAccessBlockConfiguration,
      "ReplicationConfiguration" : ReplicationConfiguration,
      "Tags" : [ Tag, ... ],
      "VersioningConfiguration" : VersioningConfiguration,
      "WebsiteConfiguration" : WebsiteConfiguration
    }
}
\`\`\`

### YAML

\`\`\`
Type: AWS::S3::Bucket
Properties:
  AbacStatus: String
  AccelerateConfiguration:
    AccelerateConfiguration
  AccessControl: String
  AnalyticsConfigurations:
    - AnalyticsConfiguration
  BucketEncryption:
    BucketEncryption
  BucketName: String
  BucketNamePrefix: String
  BucketNamespace: String
  CorsConfiguration:
    CorsConfiguration
  IntelligentTieringConfigurations:
    - IntelligentTieringConfiguration
  InventoryConfigurations:
    - InventoryConfiguration
  LifecycleConfiguration:


[Content truncated for test fixture]`,
  },
} as const;
