// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22. read_sections on CFN Lambda Function page. Truncated from 28K chars. */
export const lambdaRuntime = {
  success: {
    result: `## Syntax

To declare this entity in your CloudFormation template, use the following syntax:

### JSON

\`\`\`
{
  "Type" : "AWS::Lambda::Function",
  "Properties" : {
      "Architectures" : [ String, ... ],
      "CapacityProviderConfig" : CapacityProviderConfig,
      "Code" : Code,
      "CodeSigningConfigArn" : String,
      "DeadLetterConfig" : DeadLetterConfig,
      "Description" : String,
      "DurableConfig" : DurableConfig,
      "Environment" : Environment,
      "EphemeralStorage" : EphemeralStorage,
      "FileSystemConfigs" : [ FileSystemConfig, ... ],
      "FunctionName" : String,
      "FunctionScalingConfig" : FunctionScalingConfig,
      "Handler" : String,
      "ImageConfig" : ImageConfig,
      "KmsKeyArn" : String,
      "Layers" : [ String, ... ],
      "LoggingConfig" : LoggingConfig,
      "MemorySize" : Integer,
      "PackageType" : String,
      "PublishToLatestPublished" : Boolean,
      "RecursiveLoop" : String,
      "ReservedConcurrentExecutions" : Integer,
      "Role" : String,
      "Runtime" : String,
      "RuntimeManagementConfig" : RuntimeManagementConfig,
      "SnapStart" : SnapStart,
      "Tags" : [ Tag, ... ],
      "TenancyConfig" : TenancyConfig,
      "Timeout" : Integer,
      "TracingConfig" : TracingConfig,
      "VpcConfig" : VpcConfig
    }
}
\`\`\`

### YAML

\`\`\`
Type: AWS::Lambda::Function
Properties:
  Architectures: 
    - String
  CapacityProviderConfig: 
    CapacityProviderConfig
  Code: 
    Code
  CodeSigningConfigArn: String
  DeadLetterConfig: 
    DeadLetterConfig
  Description: String
  DurableConfig: 
    DurableConfig
  Environment: 
    Environment
  EphemeralStorage: 
    EphemeralStorage
  FileSystemConfigs: 
    - FileSystemConfig
  FunctionName: String
  FunctionScalingConfig: 
    FunctionScalingConfig
  Handler: String
  ImageConfig: 
    ImageConfig
  KmsKeyArn: String
  Layers: 
    - String
  LoggingConfig: 
    LoggingConfig
  MemorySize: Integer
  PackageType: String
  PublishToLatestPublish

[Content truncated for test fixture]`,
  },
} as const;
