// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22. read_sections on CFN EC2 Instance page. Truncated from 50K chars. */
export const ec2InstanceType = {
  success: {
    result: `## Syntax

To declare this entity in your CloudFormation template, use the following syntax:

### JSON

\`\`\`
{
  "Type" : "AWS::EC2::Instance",
  "Properties" : {
      "AdditionalInfo" : String,
      "Affinity" : String,
      "AvailabilityZone" : String,
      "BlockDeviceMappings" : [ BlockDeviceMapping, ... ],
      "CpuOptions" : CpuOptions,
      "CreditSpecification" : CreditSpecification,
      "DisableApiTermination" : Boolean,
      "EbsOptimized" : Boolean,
      "ElasticGpuSpecifications" : [ ElasticGpuSpecification, ... ],
      "ElasticInferenceAccelerators" : [ ElasticInferenceAccelerator, ... ],
      "EnclaveOptions" : EnclaveOptions,
      "HibernationOptions" : HibernationOptions,
      "HostId" : String,
      "HostResourceGroupArn" : String,
      "IamInstanceProfile" : String,
      "ImageId" : String,
      "InstanceInitiatedShutdownBehavior" : String,
      "InstanceType" : String,
      "Ipv6AddressCount" : Integer,
      "Ipv6Addresses" : [ InstanceIpv6Address, ... ],
      "KernelId" : String,
      "KeyName" : String,
      "LaunchTemplate" : LaunchTemplateSpecification,
      "LicenseSpecifications" : [ LicenseSpecification, ... ],
      "MetadataOptions" : MetadataOptions,
      "Monitoring" : Boolean,
      "NetworkInterfaces" : [ NetworkInterface, ... ],
      "PlacementGroupName" : String,
      "PrivateDnsNameOptions" : PrivateDnsNameOptions,
      "PrivateIpAddress" : String,
      "PropagateTagsToVolumeOnCreation" : Boolean,
      "RamdiskId" : String,
      "SecurityGroupIds" : [ String, ... ],
      "SecurityGroups" : [ String, ... ],
      "SourceDestCheck" : Boolean,
      "SsmAssociations" : [ SsmAssociation, ... ],
      "SubnetId" : String,
      "Tags" : [ Tag, ... ],
      "Tenancy" : String,
      "UserData" : String,
      "Volumes" : [ Volume, ... ]
    }
}
\`\`\`

### YAML

\`\`\`
Type: AWS::EC2::Instance
Properties:
  AdditionalInfo: String
  Affinity: String
  AvailabilityZone: String
  BlockDeviceMappings: 
    - BlockDe

[Content truncated for test fixture]`,
  },
} as const;
