// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText, iamResultEnvelope } from "./_helpers.js";

/** SSM Parameter — all actions allowed. Input: { actions: [cloudcontrol:CreateResource, ssm:PutParameter, ssm:AddTagsToResource] } */
export const ssmParameterAllowed = {
  success: mcpText(
    iamResultEnvelope({
      EvaluationResults: [
        {
          EvalActionName: "cloudcontrol:CreateResource",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "CloudControlFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 10, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "cloudcontrol:GetResourceRequestStatus",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "CloudControlFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 10, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "ssm:PutParameter",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "AmazonSSMFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 8, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "ssm:AddTagsToResource",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "AmazonSSMFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 8, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
      ],
    }),
  ),
} as const;
