// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText, iamResultEnvelope } from "./_helpers.js";

/** ELBv2 — all creation actions allowed. Input: { actions: [cloudcontrol:CreateResource, elasticloadbalancing:CreateLoadBalancer] } */
export const elbv2LoadBalancerAllowed = {
  success: mcpText(
    iamResultEnvelope({
      EvaluationResults: [
        {
          EvalActionName: "cloudcontrol:CreateResource",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "CloudControlFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 10, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "cloudcontrol:GetResourceRequestStatus",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "CloudControlFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 10, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "elasticloadbalancing:CreateLoadBalancer",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "ElasticLoadBalancingFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 8, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "elasticloadbalancing:AddTags",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "ElasticLoadBalancingFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 8, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
      ],
    }),
  ),
} as const;
