// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText, iamResultEnvelope } from "./_helpers.js";

/** DynamoDB — all creation actions allowed. Input: { actions: [cloudcontrol:CreateResource, dynamodb:CreateTable, dynamodb:TagResource] } */
export const dynamoDbTableAllowed = {
  success: mcpText(
    iamResultEnvelope({
      EvaluationResults: [
        {
          EvalActionName: "cloudcontrol:CreateResource",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "CloudControlFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 10, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "cloudcontrol:GetResourceRequestStatus",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "CloudControlFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 10, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "dynamodb:CreateTable",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "AmazonDynamoDBFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 8, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
        {
          EvalActionName: "dynamodb:TagResource",
          EvalResourceName: "*",
          EvalDecision: "allowed",
          MatchedStatements: [
            {
              SourcePolicyId: "AmazonDynamoDBFullAccess",
              SourcePolicyType: "IAM Policy",
              StartPosition: { Line: 3, Column: 14 },
              EndPosition: { Line: 8, Column: 5 },
            },
          ],
          MissingContextValues: [],
        },
      ],
    }),
  ),
} as const;
