// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 from aws-pricing-mcp-server. Input: { service_code: "AmazonRDS", filters: [instanceType=db.t3.micro, engine=MySQL, deployment=Single-AZ] } */
export const rdsT3MicroMysql = {
  success: mcpText({
    status: "success",
    service_name: "AmazonRDS",
    data: [
      {
        product: {
          productFamily: "Database Instance",
          attributes: {
            instanceType: "db.t3.micro",
            regionCode: "us-east-1",
            usagetype: "InstanceUsage:db.t3.micro",
            databaseEngine: "MySQL",
            deploymentOption: "Single-AZ",
            servicecode: "AmazonRDS",
            servicename: "Amazon Relational Database Service",
            memory: "1 GiB",
            vcpu: "2",
            storage: "EBS Only",
            currentGeneration: "Yes",
            instanceFamily: "General purpose",
          },
          sku: "AXC2TYPWXFK88MVY",
        },
        terms: {
          OnDemand: {
            "AXC2TYPWXFK88MVY.JRTCKXETXF": {
              priceDimensions: {
                "AXC2TYPWXFK88MVY.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description:
                    "USD 0.017 per db.t3.micro Single-AZ instance hour (or partial hour) running MySQL",
                  appliesTo: [],
                  rateCode: "AXC2TYPWXFK88MVY.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0170000000",
                  },
                },
              },
              sku: "AXC2TYPWXFK88MVY",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
          Reserved: "<filtered by output_options.pricing_terms>",
        },
        version: "20260318225923",
        publicationDate: "2026-03-18T22:59:23Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonRDS in us-east-1 from AWS Pricing API",
  }),
} as const;

/** Captured 2026-03-22 from aws-pricing-mcp-server. Input: { service_code: "AmazonRDS", filters: [instanceType=db.r6g.large, engine=Aurora MySQL] }. 2 items captured, 1 kept. */
export const rdsR6gLargeAuroraMysql = {
  success: mcpText({
    status: "success",
    service_name: "AmazonRDS",
    data: [
      {
        product: {
          productFamily: "Database Instance",
          attributes: {
            instanceType: "db.r6g.large",
            regionCode: "us-east-1",
            usagetype: "InstanceUsage:db.r6g.large",
            databaseEngine: "Aurora MySQL",
            deploymentOption: "Single-AZ",
            servicecode: "AmazonRDS",
            servicename: "Amazon Relational Database Service",
            memory: "16 GiB",
            vcpu: "2",
            storage: "EBS Only",
            currentGeneration: "Yes",
            instanceFamily: "Memory optimized",
          },
          sku: "SVB4AAU3H83DPGMK",
        },
        terms: {
          OnDemand: {
            "SVB4AAU3H83DPGMK.JRTCKXETXF": {
              priceDimensions: {
                "SVB4AAU3H83DPGMK.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description:
                    "$ 0.26 per RDS db.r6g.large Single-AZ instance hour (or partial hour) running Aurora MySQL",
                  appliesTo: [],
                  rateCode: "SVB4AAU3H83DPGMK.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.2600000000",
                  },
                },
              },
              sku: "SVB4AAU3H83DPGMK",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
          Reserved: "<filtered by output_options.pricing_terms>",
        },
        version: "20260318225923",
        publicationDate: "2026-03-18T22:59:23Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonRDS in us-east-1 from AWS Pricing API",
  }),
} as const;

/** Captured 2026-03-22 from aws-pricing-mcp-server. Input: { service_code: "AmazonRDS", filters: [instanceType=db.t3.micro, engine=MariaDB, deployment=Single-AZ] } */
export const rdsT3MicroMariadb = {
  success: mcpText({
    status: "success",
    service_name: "AmazonRDS",
    data: [
      {
        product: {
          productFamily: "Database Instance",
          attributes: {
            instanceType: "db.t3.micro",
            regionCode: "us-east-1",
            usagetype: "InstanceUsage:db.t3.micro",
            databaseEngine: "MariaDB",
            deploymentOption: "Single-AZ",
            servicecode: "AmazonRDS",
            servicename: "Amazon Relational Database Service",
            memory: "1 GiB",
            vcpu: "2",
            storage: "EBS Only",
            currentGeneration: "Yes",
            instanceFamily: "General purpose",
          },
          sku: "5J8PBWJNX88YGMQK",
        },
        terms: {
          OnDemand: {
            "5J8PBWJNX88YGMQK.JRTCKXETXF": {
              priceDimensions: {
                "5J8PBWJNX88YGMQK.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description:
                    "USD 0.017 per db.t3.micro Single-AZ instance hour (or partial hour) running MariaDB",
                  appliesTo: [],
                  rateCode: "5J8PBWJNX88YGMQK.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0170000000",
                  },
                },
              },
              sku: "5J8PBWJNX88YGMQK",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
          Reserved: "<filtered by output_options.pricing_terms>",
        },
        version: "20260318225923",
        publicationDate: "2026-03-18T22:59:23Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonRDS in us-east-1 from AWS Pricing API",
  }),
} as const;
