// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 from aws-pricing-mcp-server. Input: { service_code: "AmazonS3", filters: [productFamily=Storage, usagetype=TimedStorage-ByteHrs] } */
export const s3Storage = {
  success: mcpText({
    status: "success",
    service_name: "AmazonS3",
    data: [
      {
        product: {
          productFamily: "Storage",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "TimedStorage-ByteHrs",
            servicecode: "AmazonS3",
            servicename: "Amazon Simple Storage Service",
          },
          sku: "WP9ANXZGBYYSGJEA",
        },
        terms: {
          OnDemand: {
            "WP9ANXZGBYYSGJEA.JRTCKXETXF": {
              priceDimensions: {
                "WP9ANXZGBYYSGJEA.JRTCKXETXF.D42MF2PVJS": {
                  unit: "GB-Mo",
                  endRange: "512000",
                  description:
                    "$0.022 per GB - next 450 TB / month of storage used",
                  appliesTo: [],
                  rateCode: "WP9ANXZGBYYSGJEA.JRTCKXETXF.D42MF2PVJS",
                  beginRange: "51200",
                  pricePerUnit: {
                    USD: "0.0220000000",
                  },
                },
                "WP9ANXZGBYYSGJEA.JRTCKXETXF.PXJDJ3YRG3": {
                  unit: "GB-Mo",
                  endRange: "Inf",
                  description:
                    "$0.021 per GB - storage used / month over 500 TB",
                  appliesTo: [],
                  rateCode: "WP9ANXZGBYYSGJEA.JRTCKXETXF.PXJDJ3YRG3",
                  beginRange: "512000",
                  pricePerUnit: {
                    USD: "0.0210000000",
                  },
                },
                "WP9ANXZGBYYSGJEA.JRTCKXETXF.PGHJ3S3EYE": {
                  unit: "GB-Mo",
                  endRange: "51200",
                  description:
                    "$0.023 per GB - first 50 TB / month of storage used",
                  appliesTo: [],
                  rateCode: "WP9ANXZGBYYSGJEA.JRTCKXETXF.PGHJ3S3EYE",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0230000000",
                  },
                },
              },
              sku: "WP9ANXZGBYYSGJEA",
              effectiveDate: "2026-02-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260223232215",
        publicationDate: "2026-02-23T23:22:15Z",
      },
    ],
    message: "Retrieved pricing for AmazonS3 in us-east-1 from AWS Pricing API",
  }),
} as const;

/** S3 decomposer: PUT requests. Input: { service_code: "AmazonS3", filters: [productFamily=API Request, usagetype=Requests-Tier1] } */
export const s3PutRequests = {
  success: mcpText({
    status: "success",
    service_name: "AmazonS3",
    data: [
      {
        product: {
          productFamily: "API Request",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "Requests-Tier1",
            group: "S3-API-Tier1",
            servicecode: "AmazonS3",
            servicename: "Amazon Simple Storage Service",
          },
          sku: "S3PUTREQSKU0001",
        },
        terms: {
          OnDemand: {
            "S3PUTREQSKU0001.JRTCKXETXF": {
              priceDimensions: {
                "S3PUTREQSKU0001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Requests",
                  endRange: "Inf",
                  description:
                    "$0.005 per 1,000 PUT, COPY, POST, or LIST requests",
                  appliesTo: [],
                  rateCode: "S3PUTREQSKU0001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0050000000",
                  },
                },
              },
              sku: "S3PUTREQSKU0001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260223232215",
        publicationDate: "2026-02-23T23:22:15Z",
      },
    ],
    message: "Retrieved pricing for AmazonS3 in us-east-1 from AWS Pricing API",
  }),
} as const;

/** S3 decomposer: GET requests. Input: { service_code: "AmazonS3", filters: [productFamily=API Request, usagetype=Requests-Tier2] } */
export const s3GetRequests = {
  success: mcpText({
    status: "success",
    service_name: "AmazonS3",
    data: [
      {
        product: {
          productFamily: "API Request",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "Requests-Tier2",
            group: "S3-API-Tier2",
            servicecode: "AmazonS3",
            servicename: "Amazon Simple Storage Service",
          },
          sku: "S3GETREQSKU0001",
        },
        terms: {
          OnDemand: {
            "S3GETREQSKU0001.JRTCKXETXF": {
              priceDimensions: {
                "S3GETREQSKU0001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Requests",
                  endRange: "Inf",
                  description: "$0.0004 per 1,000 GET and all other requests",
                  appliesTo: [],
                  rateCode: "S3GETREQSKU0001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0004000000",
                  },
                },
              },
              sku: "S3GETREQSKU0001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260223232215",
        publicationDate: "2026-02-23T23:22:15Z",
      },
    ],
    message: "Retrieved pricing for AmazonS3 in us-east-1 from AWS Pricing API",
  }),
} as const;

/** S3 decomposer: Data Transfer. Input: { service_code: "AWSDataTransfer", filters: [productFamily=Data Transfer, usagetype=DataTransfer-Out-Bytes] } */
export const s3DataTransfer = {
  success: mcpText({
    status: "success",
    service_name: "AWSDataTransfer",
    data: [
      {
        product: {
          productFamily: "Data Transfer",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "DataTransfer-Out-Bytes",
            transferType: "AWS Outbound",
            fromLocation: "US East (N. Virginia)",
            fromLocationType: "AWS Region",
            toLocation: "External",
            toLocationType: "Other",
            servicecode: "AWSDataTransfer",
            servicename: "AWS Data Transfer",
          },
          sku: "DTOUTSKU00000001",
        },
        terms: {
          OnDemand: {
            "DTOUTSKU00000001.JRTCKXETXF": {
              priceDimensions: {
                "DTOUTSKU00000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "GB",
                  endRange: "Inf",
                  description:
                    "$0.09 per GB - next 9.999 TB / month data transfer out beyond the global free tier",
                  appliesTo: [],
                  rateCode: "DTOUTSKU00000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "1",
                  pricePerUnit: {
                    USD: "0.0900000000",
                  },
                },
              },
              sku: "DTOUTSKU00000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260223232215",
        publicationDate: "2026-02-23T23:22:15Z",
      },
    ],
    message:
      "Retrieved pricing for AWSDataTransfer in us-east-1 from AWS Pricing API",
  }),
} as const;
