// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 from aws-pricing-mcp-server. Input: { service_code: "AmazonEC2", filters: [instanceType=t3.micro, os=Linux, tenancy=Shared] } */
export const ec2T3Micro = {
  success: mcpText({
    status: "success",
    service_name: "AmazonEC2",
    data: [
      {
        product: {
          productFamily: "Compute Instance",
          attributes: {
            instanceType: "t3.micro",
            operatingSystem: "Linux",
            tenancy: "Shared",
            regionCode: "us-east-1",
            usagetype: "BoxUsage:t3.micro",
            capacitystatus: "Used",
            preInstalledSw: "NA",
            servicecode: "AmazonEC2",
            servicename: "Amazon Elastic Compute Cloud",
            memory: "1 GiB",
            vcpu: "2",
            storage: "EBS only",
            currentGeneration: "Yes",
            instanceFamily: "General purpose",
          },
          sku: "CRAJUW7BTXFMT2UJ",
        },
        terms: {
          OnDemand: {
            "CRAJUW7BTXFMT2UJ.JRTCKXETXF": {
              priceDimensions: {
                "CRAJUW7BTXFMT2UJ.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description:
                    "$0.0104 per On Demand Linux t3.micro Instance Hour",
                  appliesTo: [],
                  rateCode: "CRAJUW7BTXFMT2UJ.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0104000000",
                  },
                },
              },
              sku: "CRAJUW7BTXFMT2UJ",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
          Reserved: "<filtered by output_options.pricing_terms>",
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonEC2 in us-east-1 from AWS Pricing API",
  }),
} as const;

/** Captured 2026-03-22 from aws-pricing-mcp-server. Input: { service_code: "AmazonEC2", filters: [instanceType=t3.small, os=Linux, tenancy=Shared] } */
export const ec2T3Small = {
  success: mcpText({
    status: "success",
    service_name: "AmazonEC2",
    data: [
      {
        product: {
          productFamily: "Compute Instance",
          attributes: {
            instanceType: "t3.small",
            operatingSystem: "Linux",
            tenancy: "Shared",
            regionCode: "us-east-1",
            usagetype: "BoxUsage:t3.small",
            capacitystatus: "Used",
            preInstalledSw: "NA",
            servicecode: "AmazonEC2",
            servicename: "Amazon Elastic Compute Cloud",
            memory: "2 GiB",
            vcpu: "2",
            storage: "EBS only",
            currentGeneration: "Yes",
            instanceFamily: "General purpose",
          },
          sku: "QA3NBPZEQKZ2K9AR",
        },
        terms: {
          OnDemand: {
            "QA3NBPZEQKZ2K9AR.JRTCKXETXF": {
              priceDimensions: {
                "QA3NBPZEQKZ2K9AR.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description:
                    "$0.0208 per On Demand Linux t3.small Instance Hour",
                  appliesTo: [],
                  rateCode: "QA3NBPZEQKZ2K9AR.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0208000000",
                  },
                },
              },
              sku: "QA3NBPZEQKZ2K9AR",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
          Reserved: "<filtered by output_options.pricing_terms>",
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonEC2 in us-east-1 from AWS Pricing API",
  }),
} as const;

/** Captured 2026-03-22 from aws-pricing-mcp-server. Input: { service_code: "AmazonEC2", filters: [instanceType=m5.large, os=Linux, tenancy=Shared] } */
export const ec2M5Large = {
  success: mcpText({
    status: "success",
    service_name: "AmazonEC2",
    data: [
      {
        product: {
          productFamily: "Compute Instance",
          attributes: {
            instanceType: "m5.large",
            operatingSystem: "Linux",
            tenancy: "Shared",
            regionCode: "us-east-1",
            usagetype: "BoxUsage:m5.large",
            capacitystatus: "Used",
            preInstalledSw: "NA",
            servicecode: "AmazonEC2",
            servicename: "Amazon Elastic Compute Cloud",
            memory: "8 GiB",
            vcpu: "2",
            storage: "EBS only",
            currentGeneration: "Yes",
            instanceFamily: "General purpose",
          },
          sku: "6C86BEPQVG73ZGGR",
        },
        terms: {
          OnDemand: {
            "6C86BEPQVG73ZGGR.JRTCKXETXF": {
              priceDimensions: {
                "6C86BEPQVG73ZGGR.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description:
                    "$0.096 per On Demand Linux m5.large Instance Hour",
                  appliesTo: [],
                  rateCode: "6C86BEPQVG73ZGGR.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0960000000",
                  },
                },
              },
              sku: "6C86BEPQVG73ZGGR",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
          Reserved: "<filtered by output_options.pricing_terms>",
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonEC2 in us-east-1 from AWS Pricing API",
  }),
} as const;
