// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 from aws-pricing-mcp-server. Input: { service_code: "AmazonRDS", filters: [instanceType=db.t3.micro, engine=PostgreSQL, deployment=Single-AZ] } */
export const rdsT3MicroPostgres = {
  success: mcpText({
    status: "success",
    service_name: "AmazonRDS",
    data: [
      {
        product: {
          productFamily: "Database Instance",
          attributes: {
            instanceType: "db.t3.micro",
            regionCode: "us-east-1",
            usagetype: "InstanceUsage:db.t3.micro",
            databaseEngine: "PostgreSQL",
            deploymentOption: "Single-AZ",
            servicecode: "AmazonRDS",
            servicename: "Amazon Relational Database Service",
            memory: "1 GiB",
            vcpu: "2",
            storage: "EBS Only",
            currentGeneration: "Yes",
            instanceFamily: "General purpose",
          },
          sku: "TGN7QDJF2AGFU9XA",
        },
        terms: {
          OnDemand: {
            "TGN7QDJF2AGFU9XA.JRTCKXETXF": {
              priceDimensions: {
                "TGN7QDJF2AGFU9XA.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description:
                    "USD 0.018 per db.t3.micro Single-AZ instance hour (or partial hour) running PostgreSQL",
                  appliesTo: [],
                  rateCode: "TGN7QDJF2AGFU9XA.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0180000000",
                  },
                },
              },
              sku: "TGN7QDJF2AGFU9XA",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
          Reserved: "<filtered by output_options.pricing_terms>",
        },
        version: "20260318225923",
        publicationDate: "2026-03-18T22:59:23Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonRDS in us-east-1 from AWS Pricing API",
  }),
} as const;

/** Captured 2026-03-22 from aws-pricing-mcp-server. Input: { service_code: "AmazonRDS", filters: [instanceType=db.r6g.large, engine=Aurora PostgreSQL] }. 2 items captured, 1 kept. */
export const rdsR6gLargeAuroraPostgres = {
  success: mcpText({
    status: "success",
    service_name: "AmazonRDS",
    data: [
      {
        product: {
          productFamily: "Database Instance",
          attributes: {
            instanceType: "db.r6g.large",
            regionCode: "us-east-1",
            usagetype: "InstanceUsage:db.r6g.large",
            databaseEngine: "Aurora PostgreSQL",
            deploymentOption: "Single-AZ",
            servicecode: "AmazonRDS",
            servicename: "Amazon Relational Database Service",
            memory: "16 GiB",
            vcpu: "2",
            storage: "EBS Only",
            currentGeneration: "Yes",
            instanceFamily: "Memory optimized",
          },
          sku: "4U9P9G87PY8QVQH5",
        },
        terms: {
          OnDemand: {
            "4U9P9G87PY8QVQH5.JRTCKXETXF": {
              priceDimensions: {
                "4U9P9G87PY8QVQH5.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description:
                    "$ 0.26 per RDS db.r6g.large Single-AZ instance hour (or partial hour) running Aurora PostgreSQL",
                  appliesTo: [],
                  rateCode: "4U9P9G87PY8QVQH5.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.2600000000",
                  },
                },
              },
              sku: "4U9P9G87PY8QVQH5",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
          Reserved: "<filtered by output_options.pricing_terms>",
        },
        version: "20260318225923",
        publicationDate: "2026-03-18T22:59:23Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonRDS in us-east-1 from AWS Pricing API",
  }),
} as const;

/** RDS decomposer: Multi-AZ compute. Input: { service_code: "AmazonRDS", filters: [instanceType=db.t3.micro, engine=PostgreSQL, deployment=Multi-AZ] } */
export const rdsT3MicroPostgresMultiAZ = {
  success: mcpText({
    status: "success",
    service_name: "AmazonRDS",
    data: [
      {
        product: {
          productFamily: "Database Instance",
          attributes: {
            instanceType: "db.t3.micro",
            regionCode: "us-east-1",
            usagetype: "Multi-AZUsage:db.t3.micro",
            databaseEngine: "PostgreSQL",
            deploymentOption: "Multi-AZ",
            servicecode: "AmazonRDS",
            servicename: "Amazon Relational Database Service",
            memory: "1 GiB",
            vcpu: "2",
            storage: "EBS Only",
            currentGeneration: "Yes",
            instanceFamily: "General purpose",
          },
          sku: "RDSMAZ7QDJF2AG01",
        },
        terms: {
          OnDemand: {
            "RDSMAZ7QDJF2AG01.JRTCKXETXF": {
              priceDimensions: {
                "RDSMAZ7QDJF2AG01.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description:
                    "USD 0.036 per db.t3.micro Multi-AZ instance hour (or partial hour) running PostgreSQL",
                  appliesTo: [],
                  rateCode: "RDSMAZ7QDJF2AG01.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0360000000",
                  },
                },
              },
              sku: "RDSMAZ7QDJF2AG01",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
          Reserved: "<filtered by output_options.pricing_terms>",
        },
        version: "20260318225923",
        publicationDate: "2026-03-18T22:59:23Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonRDS in us-east-1 from AWS Pricing API",
  }),
} as const;
