// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 from aws-pricing-mcp-server. Input: { service_code: "AmazonEC2", filters: [instanceType=z99.nonexistent] }. Server returns error with suggestion. */
export const emptyData = {
  success: mcpText({
    status: "error",
    error_type: "empty_results",
    message:
      "No results found for given filters [[PricingFilter(field='productFamily', type='TERM_MATCH', value='Compute Instance'), PricingFilter(field='instanceType', type='TERM_MATCH', value='z99.nonexistent'), PricingFilter(field='operatingSystem', type='TERM_MATCH', value='Linux')]], service: \"AmazonEC2\", region \"us-east-1\"",
    service_code: "AmazonEC2",
    region: "us-east-1",
    suggestion:
      "Try these approaches: (1) Verify that the service code is valid. Use get_service_codes() to get valid service codes. (2) Validate region and filter values using get_pricing_attribute_values(). (3) Test with fewer filters to isolate the issue.",
    examples: {
      "Example service codes": [
        "AmazonEC2",
        "AmazonS3",
        "AmazonES",
        "AWSLambda",
        "AmazonDynamoDB",
      ],
      "Example regions": ["us-east-1", "eu-west-1", "ap-south-1"],
    },
  }),
} as const;

/** Synthetic: zero-price response — constructed for free-tier edge case testing. */
export const zeroPrice = {
  success: mcpText({
    data: [
      {
        terms: {
          OnDemand: {
            "TERM-FREE": {
              priceDimensions: {
                "DIM-FREE": {
                  beginRange: "0",
                  pricePerUnit: { USD: "0.0000000000" },
                },
              },
            },
          },
        },
      },
    ],
  }),
} as const;

/** Synthetic: empty response object — MCP server returned valid JSON but no data key. */
export const emptyResponse = {
  success: mcpText({}),
} as const;

/** Synthetic: malformed response — text field is not valid JSON. */
export const malformedJson = {
  success: { type: "text" as const, text: "not valid json {{{" },
} as const;
