// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** ELBv2 ALB hourly charge. Input: { service_code: "AWSELB", filters: [productFamily=Load Balancer-Application, usagetype=LoadBalancerUsage] } */
export const elbv2AlbHourly = {
  success: mcpText({
    status: "success",
    service_name: "AWSELB",
    data: [
      {
        product: {
          productFamily: "Load Balancer-Application",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "LoadBalancerUsage",
            group: "ELB:Balancer",
            servicecode: "AWSELB",
            servicename: "Elastic Load Balancing",
          },
          sku: "ELBALBHRSKU00001",
        },
        terms: {
          OnDemand: {
            "ELBALBHRSKU00001.JRTCKXETXF": {
              priceDimensions: {
                "ELBALBHRSKU00001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description:
                    "$0.0225 per Application Load Balancer-hour (or partial hour)",
                  appliesTo: [],
                  rateCode: "ELBALBHRSKU00001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0225000000",
                  },
                },
              },
              sku: "ELBALBHRSKU00001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message: "Retrieved pricing for AWSELB in us-east-1 from AWS Pricing API",
  }),
} as const;

/** ELBv2 ALB LCU-hour. Input: { service_code: "AWSELB", filters: [productFamily=Load Balancer-Application, usagetype=LCUUsage] } */
export const elbv2AlbLcu = {
  success: mcpText({
    status: "success",
    service_name: "AWSELB",
    data: [
      {
        product: {
          productFamily: "Load Balancer-Application",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "LCUUsage",
            group: "ELB:Balancer",
            servicecode: "AWSELB",
            servicename: "Elastic Load Balancing",
          },
          sku: "ELBALBLCUSKU0001",
        },
        terms: {
          OnDemand: {
            "ELBALBLCUSKU0001.JRTCKXETXF": {
              priceDimensions: {
                "ELBALBLCUSKU0001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Hrs",
                  endRange: "Inf",
                  description: "$0.008 per LCU-hour (or partial hour)",
                  appliesTo: [],
                  rateCode: "ELBALBLCUSKU0001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0080000000",
                  },
                },
              },
              sku: "ELBALBLCUSKU0001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message: "Retrieved pricing for AWSELB in us-east-1 from AWS Pricing API",
  }),
} as const;
