// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Lambda decomposer: CloudWatch Logs. Input: { service_code: "AmazonCloudWatch", filters: [productFamily=Data Payload, group=CW:Logs, usagetype=DataProcessing-Bytes] } */
export const cloudWatchLogs = {
  success: mcpText({
    status: "success",
    service_name: "AmazonCloudWatch",
    data: [
      {
        product: {
          productFamily: "Data Payload",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "DataProcessing-Bytes",
            group: "CW:Logs",
            servicecode: "AmazonCloudWatch",
            servicename: "Amazon CloudWatch",
          },
          sku: "CWLOGSKU00000001",
        },
        terms: {
          OnDemand: {
            "CWLOGSKU00000001.JRTCKXETXF": {
              priceDimensions: {
                "CWLOGSKU00000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "GB",
                  endRange: "Inf",
                  description: "$0.50 per GB of log data ingested",
                  appliesTo: [],
                  rateCode: "CWLOGSKU00000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.5000000000",
                  },
                },
              },
              sku: "CWLOGSKU00000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonCloudWatch in us-east-1 from AWS Pricing API",
  }),
} as const;
