// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** SQS Standard queue requests. Input: { service_code: "AmazonSQS", filters: [productFamily=API Request, queueType=Standard] } */
export const sqsStandardRequests = {
  success: mcpText({
    status: "success",
    service_name: "AmazonSQS",
    data: [
      {
        product: {
          productFamily: "API Request",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "USE1-Requests-Tier1",
            queueType: "Standard",
            servicecode: "AmazonSQS",
            servicename: "Amazon Simple Queue Service",
          },
          sku: "SQSSTDREQ0000001",
        },
        terms: {
          OnDemand: {
            "SQSSTDREQ0000001.JRTCKXETXF": {
              priceDimensions: {
                "SQSSTDREQ0000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Requests",
                  endRange: "Inf",
                  description:
                    "$0.40 per million Amazon SQS Requests per month for Standard queue",
                  appliesTo: [],
                  rateCode: "SQSSTDREQ0000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0000004000",
                  },
                },
              },
              sku: "SQSSTDREQ0000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonSQS in us-east-1 from AWS Pricing API",
  }),
} as const;

/** SQS FIFO queue requests. Input: { service_code: "AmazonSQS", filters: [productFamily=API Request, queueType=FIFO] } */
export const sqsFifoRequests = {
  success: mcpText({
    status: "success",
    service_name: "AmazonSQS",
    data: [
      {
        product: {
          productFamily: "API Request",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "USE1-Requests-FIFO-Tier1",
            queueType: "FIFO",
            servicecode: "AmazonSQS",
            servicename: "Amazon Simple Queue Service",
          },
          sku: "SQSFIFOREQ000001",
        },
        terms: {
          OnDemand: {
            "SQSFIFOREQ000001.JRTCKXETXF": {
              priceDimensions: {
                "SQSFIFOREQ000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "Requests",
                  endRange: "Inf",
                  description:
                    "$0.50 per million Amazon SQS Requests per month for FIFO queue",
                  appliesTo: [],
                  rateCode: "SQSFIFOREQ000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0000005000",
                  },
                },
              },
              sku: "SQSFIFOREQ000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260320042925",
        publicationDate: "2026-03-20T04:29:25Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonSQS in us-east-1 from AWS Pricing API",
  }),
} as const;
