// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** RDS decomposer: Database storage gp3. Input: { service_code: "AmazonRDS", filters: [productFamily=Database Storage, volumeType=General Purpose (SSD)] } */
export const rdsStorageGp3 = {
  success: mcpText({
    status: "success",
    service_name: "AmazonRDS",
    data: [
      {
        product: {
          productFamily: "Database Storage",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "RDS:GP3-Storage",
            volumeType: "General Purpose (SSD)",
            deploymentOption: "Single-AZ",
            servicecode: "AmazonRDS",
            servicename: "Amazon Relational Database Service",
          },
          sku: "RDSSTRGP3SK0001",
        },
        terms: {
          OnDemand: {
            "RDSSTRGP3SK0001.JRTCKXETXF": {
              priceDimensions: {
                "RDSSTRGP3SK0001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "GB-Mo",
                  endRange: "Inf",
                  description:
                    "$0.023 per GB-month of General Purpose (SSD) gp3 provisioned storage",
                  appliesTo: [],
                  rateCode: "RDSSTRGP3SK0001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0230000000",
                  },
                },
              },
              sku: "RDSSTRGP3SK0001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260318225923",
        publicationDate: "2026-03-18T22:59:23Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonRDS in us-east-1 from AWS Pricing API",
  }),
} as const;

/** RDS decomposer: Backup (storage snapshot). Input: { service_code: "AmazonRDS", filters: [productFamily=Storage Snapshot] } */
export const rdsBackupStorage = {
  success: mcpText({
    status: "success",
    service_name: "AmazonRDS",
    data: [
      {
        product: {
          productFamily: "Storage Snapshot",
          attributes: {
            regionCode: "us-east-1",
            usagetype: "RDS:ChargedBackupUsage",
            servicecode: "AmazonRDS",
            servicename: "Amazon Relational Database Service",
          },
          sku: "RDSBKUPSK000001",
        },
        terms: {
          OnDemand: {
            "RDSBKUPSK000001.JRTCKXETXF": {
              priceDimensions: {
                "RDSBKUPSK000001.JRTCKXETXF.6YS6EN2CT7": {
                  unit: "GB-Mo",
                  endRange: "Inf",
                  description: "$0.018 per GB-month of backup storage used",
                  appliesTo: [],
                  rateCode: "RDSBKUPSK000001.JRTCKXETXF.6YS6EN2CT7",
                  beginRange: "0",
                  pricePerUnit: {
                    USD: "0.0180000000",
                  },
                },
              },
              sku: "RDSBKUPSK000001",
              effectiveDate: "2026-03-01T00:00:00Z",
              offerTermCode: "JRTCKXETXF",
              termAttributes: {},
            },
          },
        },
        version: "20260318225923",
        publicationDate: "2026-03-18T22:59:23Z",
      },
    ],
    message:
      "Retrieved pricing for AmazonRDS in us-east-1 from AWS Pricing API",
  }),
} as const;
