// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 via DescribeType. Input: { resource_type: "AWS::SQS::Queue" }. 19 props in full schema, trimmed to 8. */
export const sqsQueue = {
  success: mcpText({
    typeName: "AWS::SQS::Queue",
    description:
      "The ``AWS::SQS::Queue`` resource creates an Amazon SQS standard or FIFO queue.\n Keep the following caveats in mind:\n  +  If you don't specify the ``FifoQueue`` property, Amazon SQS creates a standard queue.\n  +  If you change the value of the ``FifoQueue`` property, SQS creates a new queue and deletes the existing one.\n  +  You can't change the queue type after you create it.",
    properties: {
      QueueName: {
        type: "string",
        description:
          "A name for the queue. To create a FIFO queue, the name of your FIFO queue must end with the ``.fifo`` suffix. For more information, see [FIFO queues](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html) in the *Developer Guide*.\n If you don't specify a name, CFN generates a unique physical ID and uses that ID for the queue name. For more information, see [Name type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-name.html).",
      },
      FifoQueue: {
        type: "boolean",
        description:
          "If set to true, creates a FIFO queue. If you don't specify this property, Amazon SQS creates a standard queue.",
      },
      VisibilityTimeout: {
        type: "integer",
        description:
          "The length of time during which a message will be unavailable after a message is delivered from the queue. This blocks other components from receiving the same message and gives the initial component time to process and delete the message from the queue.\n Values must be from 0 to 43,200 seconds (12 hours). If you don't specify a value, AWS CloudFormation uses the default value of 30 seconds.",
      },
      MessageRetentionPeriod: {
        type: "integer",
        description:
          "The number of seconds that Amazon SQS retains a message. You can specify an integer value from ``60`` seconds (1 minute) to ``1,209,600`` seconds (14 days). The default value is ``345,600`` seconds (4 days).",
      },
      DelaySeconds: {
        type: "integer",
        description:
          "The time in seconds for which the delivery of all messages in the queue is delayed. You can specify an integer value of ``0`` to ``900`` (15 minutes). The default value is ``0``.",
      },
      MaximumMessageSize: {
        type: "integer",
        description:
          "The limit of how many bytes that a message can contain before Amazon SQS rejects it. You can specify an integer value from ``1,024`` bytes (1 KiB) to ``262,144`` bytes (256 KiB). The default value is ``262,144`` (256 KiB).",
      },
      RedrivePolicy: {
        type: ["object", "string"],
        description:
          "The string that includes the parameters for the dead-letter queue functionality of the source queue as a JSON object.",
      },
      Tags: {
        type: "array",
        description: "The tags that you attach to this queue.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Tag",
        },
      },
    },
    required: [],
    readOnlyProperties: ["/properties/QueueUrl", "/properties/Arn"],
    primaryIdentifier: ["/properties/QueueUrl"],
    additionalProperties: false,
  }),
} as const;
