// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 via DescribeType. Input: { resource_type: "AWS::EC2::Instance" }. 48 props in full schema, trimmed to 10. */
export const ec2Instance = {
  success: mcpText({
    typeName: "AWS::EC2::Instance",
    description: "Resource Type definition for AWS::EC2::Instance",
    properties: {
      Tags: {
        type: "array",
        description: "The tags to add to the instance.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Tag",
        },
      },
      InstanceType: {
        type: "string",
        description: "The instance type.",
      },
      ImageId: {
        type: "string",
        description:
          "The ID of the AMI. An AMI ID is required to launch an instance and must be specified here or in a launch template.",
      },
      KeyName: {
        type: "string",
        description: "The name of the key pair.",
      },
      SecurityGroupIds: {
        type: "array",
        description: "The IDs of the security groups.",
        insertionOrder: false,
        items: {
          type: "string",
        },
      },
      SubnetId: {
        type: "string",
        description:
          "[EC2-VPC] The ID of the subnet to launch the instance into.\n\n",
      },
      InstanceId: {
        type: "string",
        description: "The EC2 Instance ID.",
      },
      BlockDeviceMappings: {
        type: "array",
        description:
          "The block device mapping entries that defines the block devices to attach to the instance at launch.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/BlockDeviceMapping",
        },
      },
    },
    required: [],
    readOnlyProperties: [
      "/properties/InstanceId",
      "/properties/PrivateIp",
      "/properties/PublicDnsName",
      "/properties/PublicIp",
      "/properties/PrivateDnsName",
      "/properties/VpcId",
      "/properties/State",
    ],
    primaryIdentifier: ["/properties/InstanceId"],
    additionalProperties: false,
  }),
} as const;
