// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 via DescribeType. Input: { resource_type: "AWS::EC2::SecurityGroup" }. 13 props in full schema, trimmed to 6. */
export const securityGroup = {
  success: mcpText({
    typeName: "AWS::EC2::SecurityGroup",
    description:
      "Specifies a security group. To create a security group, use the [VpcId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#cfn-ec2-securitygroup-vpcid) property to specify the VPC for which to create the security group.",
    properties: {
      GroupDescription: {
        type: "string",
        description:
          "A description for the security group. This is informational only.\n Constraints: Up to 255 characters in length\n Constraints for EC2-Classic: ASCII characters\n Constraints for EC2-VPC: a-z, A-Z, 0-9, spaces, and ._-:/()#,@[]+=&;{}!$*",
      },
      GroupName: {
        type: "string",
        description:
          "The name of the security group.\n Constraints: Up to 255 characters in length. Cannot start with ``sg-``.\n Valid characters: a-z, A-Z, 0-9, spaces, and ._-:/()#,@[]+=&;{}!$*",
      },
      VpcId: {
        type: "string",
        description:
          "The ID of the VPC for the security group. If you do not specify a VPC, the default VPC is used.",
      },
      SecurityGroupIngress: {
        type: "array",
        description:
          "The inbound rules associated with the security group. There is a short interruption during which you cannot connect to the security group.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Ingress",
        },
      },
      SecurityGroupEgress: {
        type: "array",
        description:
          "The outbound rules associated with the security group. There is a short interruption during which you cannot connect to the security group.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Egress",
        },
      },
      Tags: {
        type: "array",
        description: "Any tags assigned to the security group.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Tag",
        },
      },
    },
    required: ["GroupDescription"],
    readOnlyProperties: ["/properties/Id", "/properties/GroupId"],
    primaryIdentifier: ["/properties/Id"],
    additionalProperties: false,
  }),
} as const;
