// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 via DescribeType. Input: { resource_type: "AWS::ECR::Repository" }. 10 props in full schema, trimmed to 5. */
export const ecrRepository = {
  success: mcpText({
    typeName: "AWS::ECR::Repository",
    description:
      "The ``AWS::ECR::Repository`` resource specifies an Amazon Elastic Container Registry (Amazon ECR) repository, where users can push and pull Docker images, Open Container Initiative (OCI) images, and OCI compatible artifacts.",
    properties: {
      RepositoryName: {
        type: "string",
        description:
          "The name to use for the repository. The repository name may be specified on its own (such as ``nginx-web-app``) or it can be prepended with a namespace to group the repository into a category (such as ``project-a/nginx-web-app``). If you don't specify a name, CFNlong generates a unique physical ID and uses that ID for the repository name.",
        minLength: 2,
        maxLength: 256,
        pattern:
          "^(?=.{2,256}$)((?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*)$",
      },
      ImageScanningConfiguration: {
        description:
          "The image scanning configuration for the repository. This determines whether images are scanned for known vulnerabilities after being pushed to the repository.",
        $ref: "#/definitions/ImageScanningConfiguration",
      },
      ImageTagMutability: {
        type: "string",
        description:
          "The tag mutability setting for the repository. If this parameter is omitted, the default setting of ``MUTABLE`` will be used which will allow image tags to be overwritten.",
        enum: ["MUTABLE", "IMMUTABLE"],
      },
      EncryptionConfiguration: {
        description:
          "The encryption configuration for the repository. This determines how the contents of your repository are encrypted at rest.",
        $ref: "#/definitions/EncryptionConfiguration",
      },
      Tags: {
        type: "array",
        description: "An array of key-value pairs to apply to this resource.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Tag",
        },
      },
    },
    required: [],
    readOnlyProperties: ["/properties/Arn", "/properties/RepositoryUri"],
    primaryIdentifier: ["/properties/RepositoryName"],
    additionalProperties: false,
  }),
} as const;
