// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 via DescribeType. Input: { resource_type: "AWS::SNS::Topic" }. 15 props in full schema, trimmed to 5. */
export const snsTopic = {
  success: mcpText({
    typeName: "AWS::SNS::Topic",
    description:
      "The ``AWS::SNS::Topic`` resource creates a topic to which notifications can be published.\n  One account can create a maximum of 100,000 standard topics and 1,000 FIFO topics. For more information, see [endpoints and quotas](https://docs.aws.amazon.com/general/latest/gr/sns.html) in the *General Reference*.",
    properties: {
      TopicName: {
        type: "string",
        description:
          "The name of the topic you want to create. Topic names must include only uppercase and lowercase ASCII letters, numbers, underscores, and hyphens, and must be between 1 and 256 characters long. FIFO topic names must end with ``.fifo``.\n If you don't specify a name, CFN generates a unique physical ID and uses that ID for the topic name.",
      },
      FifoTopic: {
        type: "boolean",
        description: "Set to true to create a FIFO topic.",
      },
      DisplayName: {
        type: "string",
        description:
          "The display name to use for an SNS topic with SMS subscriptions. The display name must be maximum 100 characters long, including hyphens (-), underscores (_), spaces, and tabs.",
      },
      KmsMasterKeyId: {
        type: "string",
        description:
          "The ID of an AWS managed customer master key (CMK) for Amazon SNS or a custom CMK. For more information, see [Key terms](https://docs.aws.amazon.com/sns/latest/dg/sns-server-side-encryption.html#sse-key-terms).",
      },
      Tags: {
        type: "array",
        description: "The list of tags to add to a new topic.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Tag",
        },
      },
    },
    required: [],
    readOnlyProperties: ["/properties/TopicArn"],
    primaryIdentifier: ["/properties/TopicArn"],
    additionalProperties: false,
  }),
} as const;
