// AUTO-GENERATED by story 48-10 splitter — DO NOT EDIT BY HAND.
import { mcpText } from "./_helpers.js";

/** Captured 2026-03-22 via DescribeType. Input: { resource_type: "AWS::ECS::Cluster" }. 9 props in full schema, trimmed to 5. */
export const ecsCluster = {
  success: mcpText({
    typeName: "AWS::ECS::Cluster",
    description:
      "The ``AWS::ECS::Cluster`` resource creates an Amazon Elastic Container Service (Amazon ECS) cluster.",
    properties: {
      ClusterName: {
        type: "string",
        description:
          "A user-generated string that you use to identify your cluster. If you don't specify a name, CFNlong generates a unique physical ID for the name.",
      },
      ClusterSettings: {
        type: "array",
        description:
          "The settings to use when creating a cluster. This parameter is used to turn on CloudWatch Container Insights for a cluster.",
        items: {
          $ref: "#/definitions/ClusterSettings",
        },
      },
      CapacityProviders: {
        type: "array",
        description:
          "The short name of one or more capacity providers to associate with the cluster. A capacity provider must be associated with a cluster before it can be included as part of the default capacity provider strategy of the cluster or used in a capacity provider strategy when calling the [CreateService](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html) or [RunTask](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html) actions.",
        items: {
          type: "string",
        },
      },
      DefaultCapacityProviderStrategy: {
        type: "array",
        description:
          "The default capacity provider strategy for the cluster. When services or tasks are run in the cluster with no launch type or capacity provider strategy specified, the default capacity provider strategy is used.",
        items: {
          $ref: "#/definitions/CapacityProviderStrategyItem",
        },
      },
      Tags: {
        type: "array",
        description:
          "The metadata that you apply to the cluster to help you categorize and organize them. Each tag consists of a key and an optional value. You define both.\n The following basic restrictions apply to tags:\n +  Maximum number of tags per resource - 50.\n +  For each resource, each tag key must be unique, and each tag key can have only one value.",
        insertionOrder: false,
        items: {
          $ref: "#/definitions/Tag",
        },
      },
    },
    required: [],
    readOnlyProperties: ["/properties/Arn"],
    primaryIdentifier: ["/properties/ClusterName"],
    additionalProperties: false,
  }),
} as const;
