# Fish completion script for assignee
# Generated automatically from the Commander.js command tree.
# Install: assignee completions fish | source
#   or save to ~/.config/fish/completions/assignee.fish

complete -c assignee -f

complete -c assignee -n __fish_use_subcommand -a infra -d 'Manage cloud infrastructure (plan, apply, destroy, drift, …)'
complete -c assignee -n __fish_use_subcommand -a admin -d 'Inspect and verify managed resources (status, list, doctor, …)'
complete -c assignee -n __fish_use_subcommand -a dev -d 'Developer tooling (init, setup, completions, discover, …)'

# Sub-commands for 'infra'
complete -c assignee -n "__fish_seen_subcommand_from infra" -a plan -d 'Generate an infrastructure plan from natural language intent'
complete -c assignee -n "__fish_seen_subcommand_from infra" -a apply -d 'Execute an approved infrastructure plan'
complete -c assignee -n "__fish_seen_subcommand_from infra" -a destroy -d 'Safely destroy a managed AWS resource'
complete -c assignee -n "__fish_seen_subcommand_from infra" -a drift -d 'Check managed resources for configuration drift'
complete -c assignee -n "__fish_seen_subcommand_from infra" -a reconcile -d 'Reconcile drifted resources back to desired state'
complete -c assignee -n "__fish_seen_subcommand_from infra" -a optimize -d 'Scan managed resources for cost-rightsizing opportunities'
complete -c assignee -n "__fish_seen_subcommand_from infra" -a restore-provisions -d 'Restore provisions.json from a dated backup (BCP/DR)'

# Options for 'infra plan'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from plan" -l output -s o -r -d 'Output format (json|text)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from plan" -l json -d 'Shorthand for --output json (emit machine-readable envelope)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from plan" -l no-apply -d 'Skip the apply prompt after plan display'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from plan" -l no-advice -d 'Skip inline contextual advice generation'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from plan" -l source -s s -r -d 'Path to local files to upload after provisioning (e.g., static site)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from plan" -l set -r -d 'Pre-set field values (repeatable), supports human names (e.g., --set size=t3.medium)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from plan" -l yes -s y -d 'Accepted for CI wrapper compatibility; plan is read-only and does not mutate.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from plan" -l cost-detail -d 'Show per-resource cost breakdown below the cost summary block.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from plan" -l quick -s q -d 'Skip wizard prompts that have defaults — only ask for required fields without a default. Shows a summary gate before generating the plan.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from plan" -l wizard -d 'Alias for --quick — plan is read-only, so the wizard only prompts when the LLM can\'t resolve a required field.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from plan" -l target-account -r -d 'Target AWS account ID (12 digits). Validates format; cross-account assume-role is not yet supported.'

# Options for 'infra apply'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from apply" -l wizard -d 'Run the interactive configuration wizard.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from apply" -l quick -s q -d 'Skip wizard prompts that have defaults — only ask for required fields without a default. Shows a summary gate before provisioning.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from apply" -l no-advice -d 'Skip inline contextual advice generation'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from apply" -l yes -s y -d 'Auto-confirm apply without interactive prompt (for CI/CD)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from apply" -l checkpoint -s c -r -d 'Use a saved plan checkpoint instead of running Phase 1'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from apply" -l source -s s -r -d 'Path to local files to upload after provisioning (e.g., static site)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from apply" -l set -r -d 'Pre-set wizard field values (repeatable)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from apply" -l output -s o -r -d 'Output format (json|text)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from apply" -l json -d 'Shorthand for --output json (emit machine-readable envelope)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from apply" -l target-account -r -d 'Target AWS account ID (12 digits). Validates format; cross-account assume-role is not yet supported.'

# Options for 'infra destroy'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from destroy" -l yes -s y -d 'Auto-confirm destroy without interactive prompt (for CI/CD)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from destroy" -l pending-window-in-days -r -d 'KMS keys only: pending-deletion window (7-30 days, default 7). KMS keys continue billing until the window elapses.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from destroy" -l recovery-window-in-days -r -d 'SecretsManager secrets only: recovery window (7-30 days, default 7). Secrets continue billing until the window elapses.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from destroy" -l force-delete-without-recovery -d 'SecretsManager secrets only: skip the recovery window and destroy the secret immediately. Mutually exclusive with --recovery-window-in-days.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from destroy" -l output -s o -r -d 'Output format (json|text)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from destroy" -l json -d 'Shorthand for --output json (emit machine-readable envelope)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from destroy" -l target-account -r -d 'Target AWS account ID (12 digits). Validates format; cross-account assume-role is not yet supported.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from destroy" -l all -d 'Bulk-destroy every managed resource (default: dry-run plan). Use --yes to execute.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from destroy" -l no-confirm -d 'Skip the typed-account-ID confirmation gate when used with --all --yes (CI/CD escape hatch).'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from destroy" -l allow-large-sweep -d 'Allow bulk-destroy of more than 100 resources (explicit opt-in to override the safety threshold).'

# Options for 'infra drift'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from drift" -l resource -r -d 'Filter by resource type'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from drift" -l region -r -d 'Filter by AWS region'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from drift" -l status -r -d 'Filter by drift status'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from drift" -l exclude -r -d 'Exclude a drift status from output (e.g. --exclude BASELINE_MISSING for CI)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from drift" -l baseline -d 'Adopt the given [resource-id] into drift tracking by snapshotting its live CCAPI state as a baseline'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from drift" -l output -s o -r -d 'Output format (json|text)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from drift" -l json -d 'Shorthand for --output json'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from drift" -l output-file -r -d 'Write JSON report to file (requires --json)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from drift" -l concurrency -r -d 'Max parallel drift checks (default 10, max 50)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from drift" -l detailed -d 'Show all fields including matching ones'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from drift" -l wizard -d 'Run interactive configuration wizard (drift is read-only; aliased to --detailed to show every field).'

# Options for 'infra reconcile'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from reconcile" -l resource -r -d 'Filter by resource type'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from reconcile" -l dry-run -d 'Show what would be reconciled without making changes'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from reconcile" -l yes -s y -d 'Non-interactive mode — reconcile every drifted resource without prompting (canonical CI flag)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from reconcile" -l auto-reconcile -d '(deprecated alias for --yes) Reconcile all drifted resources without prompting. Prefer --yes; this alias is retained for backward compatibility and may be removed in a future major version.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from reconcile" -l output -s o -r -d 'Output format (json|text)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from reconcile" -l json -d 'Shorthand for --output json (emit machine-readable envelope)'

# Options for 'infra optimize'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from optimize" -l region -r -d 'AWS region to scan (defaults to AWS_REGION env var)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from optimize" -l output -s o -r -d 'Output format (json|text)'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from optimize" -l json -d 'Shorthand for --output json'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from optimize" -l min-savings -r -d 'Drop recommendations whose projected monthly savings are below this USD threshold (e.g. 10 for ≥$10/mo)'

# Options for 'infra restore-provisions'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from restore-provisions" -l from -r -d 'Restore from a specific backup date (YYYY-MM-DD). Defaults to most recent backup.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from restore-provisions" -l from-audit-log -d 'Rebuild missing provision records from the HMAC-chained audit log (~/.assignee/audit/audit.log). Reads `apply_resource_created` events and appends a reconstructed record for any ARN absent from provisions.json. Cannot be combined with --from <date>.'
complete -c assignee -n "__fish_seen_subcommand_from infra; and __fish_seen_subcommand_from restore-provisions" -l json -d 'Emit machine-readable JSON to stdout instead of human-readable text'

# Sub-commands for 'admin'
complete -c assignee -n "__fish_seen_subcommand_from admin" -a audit-verify -d 'Verify the HMAC chain integrity of the local audit log. Exits 0 on a clean chain; non-zero with diagnostics when the chain is broken.'
complete -c assignee -n "__fish_seen_subcommand_from admin" -a doctor -d 'Run a non-destructive health check of credentials, Bedrock, MCP servers, cache, config and best-practices'
complete -c assignee -n "__fish_seen_subcommand_from admin" -a status -d 'Show summary of managed infrastructure'
complete -c assignee -n "__fish_seen_subcommand_from admin" -a list -d 'List all resources managed by assignee.ai'
complete -c assignee -n "__fish_seen_subcommand_from admin" -a describe -d 'Re-render the apply-success line for a previously-applied resource by run id or ARN'

# Options for 'admin audit-verify'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from audit-verify" -l from -r -d 'Start date for verification range (ISO 8601). Scaffold: full chain always verified; range filtering is planned for a future release.'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from audit-verify" -l to -r -d 'End date for verification range (ISO 8601). Scaffold: full chain always verified; range filtering is planned for a future release.'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from audit-verify" -l log-file -r -d 'Audit log file path (default: /Users/serhii_l/.assignee/audit/audit.log)'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from audit-verify" -l json -d 'Emit machine-readable JSON to stdout instead of human-readable text'

# Options for 'admin doctor'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from doctor" -l output -s o -r -d 'Output format (json|text)'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from doctor" -l json -d 'Shorthand for --output json'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from doctor" -l skip-bedrock -d 'Skip the Bedrock LLM invoke check'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from doctor" -l skip-mcp -d 'Skip the MCP server launch probe'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from doctor" -l short -d 'Fast identity-only summary: STS account + ARN + region + active config (replaces the removed `whoami` command)'

# Options for 'admin status'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from status" -l output -s o -r -d 'Output format (json|text)'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from status" -l json -d 'Shorthand for --output json'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from status" -l region -r -d 'Filter to a specific AWS region'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from status" -l resource-type -r -d 'Filter to one CFN resource type (e.g. AWS::S3::Bucket or shorthand S3, Lambda)'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from status" -l bp-coverage -d 'Show BP rule coverage dashboard'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from status" -l gaps-only -d 'Only meaningful with --bp-coverage. Prints just the list of resource types with zero BP rules and exits non-zero if any gaps are found (CI-friendly). Structural types (RouteTable, VPCGatewayAttachment, etc.) are excluded by default — override with --include-structural-gaps.'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from status" -l include-structural-gaps -d 'Only meaningful with --bp-coverage --gaps-only. Includes structural/cross-reference types (RouteTable, VPCGatewayAttachment, SubnetRouteTableAssociation, EFS::MountTarget) in the gap list. Default is to exclude them because their BP content lives on child resources by design.'

# Options for 'admin list'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from list" -l output -s o -r -d 'Output format (json|text)'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from list" -l json -d 'Shorthand for --output json'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from list" -l region -r -d 'Filter to a specific AWS region'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from list" -l resource-type -r -d 'Filter to one CFN resource type (e.g. AWS::S3::Bucket or shorthand S3, Lambda)'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from list" -l total-cost -d 'After the table, print a total estimated monthly cost across all resources (skips Free / N/A / unparseable entries)'

# Options for 'admin describe'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from describe" -l output -s o -r -d 'Output format (json|text)'
complete -c assignee -n "__fish_seen_subcommand_from admin; and __fish_seen_subcommand_from describe" -l json -d 'Shorthand for --output json'

# Sub-commands for 'dev'
complete -c assignee -n "__fish_seen_subcommand_from dev" -a init -d 'Initialize assignee.ai project configuration'
complete -c assignee -n "__fish_seen_subcommand_from dev" -a setup -d 'Create IAM users and policies for least-privilege credential separation The operator role is REQUIRED — setup aborts if it fails.'
complete -c assignee -n "__fish_seen_subcommand_from dev" -a update -d 'Refresh a deployed static-website: upload new files to S3 and invalidate CloudFront'
complete -c assignee -n "__fish_seen_subcommand_from dev" -a completions -d 'Output shell completion script'
complete -c assignee -n "__fish_seen_subcommand_from dev" -a discover -d 'Browse and search all supported resource types, compound patterns, and CLI commands'
complete -c assignee -n "__fish_seen_subcommand_from dev" -a version -d 'Show version and environment info'

# Options for 'dev init'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from init" -l global -d 'Create global user config (~/.config/assignee/config.yaml) instead of project config'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from init" -l yes -s y -d 'Skip interactive prompts and accept defaults (CI scriptability)'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from init" -l wizard -d 'Run the interactive configuration wizard.'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from init" -l region -r -d 'AWS region to write into the config (skips the region prompt)'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from init" -l auto-fix -r -d 'Set preferences.auto_fix mode: ask | apply | skip (skips the auto-fix prompt)'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from init" -l profile -r -d 'AWS profile to use for credential resolution (reads ~/.aws/config; supports SSO, assumed-role, static)'

# Options for 'dev setup'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from setup" -l profile -r -d 'AWS CLI profile with admin/root credentials (reads from ~/.aws/credentials)'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from setup" -l yes -s y -d 'Skip confirmation prompts'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from setup" -l enable-llm-logging -d 'PRIVACY: Enable Bedrock invocation text logging to CloudWatch (logs every prompt and response). Default: OFF.'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from setup" -l disable-llm-logging -d 'PRIVACY: Explicitly DISABLE Bedrock invocation text logging (idempotent). Runs only the PutModelInvocationLoggingConfiguration call with textDataDeliveryEnabled=false; does NOT re-run the full IAM wizard. Mutually exclusive with --enable-llm-logging.'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from setup" -l dry-run -d 'Print the plan of resources that WOULD be created without invoking any AWS APIs'

# Options for 'dev update'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from update" -l source -s s -r -d 'Path to local directory containing the new site files (required)'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from update" -l delete -d 'Delete remote objects that have no local counterpart (default: OFF — additive uploads only)'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from update" -l invalidation-paths -r -d 'Comma-separated paths to invalidate on CloudFront (default: \'/*\')'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from update" -l no-invalidation -d 'Skip CloudFront cache invalidation entirely'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from update" -l wait -d 'Poll until invalidation Status === \'Completed\' (typically 1-5 min)'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from update" -l yes -s y -d 'Skip confirmation prompt (for CI/CD)'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from update" -l output -s o -r -d 'Output format (json|text)'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from update" -l json -d 'Shorthand for --output json (emit machine-readable envelope)'

# Options for 'dev discover'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from discover" -l json -d 'Output the full catalogue as a JSON array'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from discover" -l category -r -d 'Filter by category: resource-types | patterns | commands'

# Options for 'dev version'
complete -c assignee -n "__fish_seen_subcommand_from dev; and __fish_seen_subcommand_from version" -l json -d 'Emit machine-readable JSON to stdout instead of human-readable text'
