/**
 * W4-05 (Epic 100 Round 3) — TelemetryEvent schema.
 *
 * Canonical data shape for all telemetry events emitted by the
 * Assignee.ai agent pipeline. Designed for composition with:
 *   - W6's `filterAllowlistedFields` + `OTEL_FIELD_ALLOWLIST` (field-
 *     classification at emit time, @privacy decorator model).
 *   - W1's `filterSensitiveElicitedFields` (second-pass credential
 *     material scrub on elicited extras).
 *
 * Privacy model:
 *   - `event_name`, `timestamp`, `node_id`: OPERATIONAL — always emitted.
 *   - `tenant_id`: placeholder string until Epic 101 wires SaaS identity.
 *     Classified SYSTEM — omitted from PII-off payloads.
 *   - `extras`: run through `filterAllowlistedFields` (W6) then
 *     `filterSensitiveElicitedFields` (W1) before the adapter sees them.
 *     Unknown or PII fields are stripped unless `ASSIGNEE_OTEL_INCLUDE_PII=1`.
 *
 * Telemetry is OFF by default (L1-F52 invariant): adapter activation
 * requires `ASSIGNEE_TELEMETRY_ADAPTER` opt-in. Absent → no-op.
 *
 * @see packages/core/src/ports/telemetry-port.ts
 * @see packages/core/src/telemetry/in-memory-telemetry-adapter.ts
 * @see packages/core/src/telemetry/otel-allowlist.ts — field filtering
 */

// ── TelemetryEvent shape ──────────────────────────────────────────────

/**
 * A single telemetry event emitted by a graph node or the pipeline.
 *
 * The `extras` map carries node-specific operational signals. All keys
 * MUST appear in `OTEL_FIELD_ALLOWLIST` (W6); unknown keys are stripped
 * at emit time by `filterAllowlistedFields`.
 */
export interface TelemetryEvent {
  /**
   * Dot-qualified event name in `<node>.<lifecycle>` form.
   * Examples: "intent_parser.entry", "result_formatter.exit".
   * Use GraphNode constants as the prefix for graph-node events.
   */
  event_name: string;

  /**
   * ISO-8601 timestamp (UTC) when the event was created.
   * Generated by the emitter — adapters MUST NOT override this.
   */
  timestamp: string;

  /**
   * Graph node that emitted this event. Matches the GraphNode constant
   * string (e.g. "intent_parser"). Empty string for non-node events.
   */
  node_id: string;

  /**
   * Tenant identifier. Placeholder string "local" until Epic 101 wires
   * SaaS identity. Classified SYSTEM — never treated as PII since it
   * carries no user-identifying information in the local/pre-SaaS tier.
   */
  tenant_id: string;

  /**
   * Additional operational signals. Keys must be in OTEL_FIELD_ALLOWLIST.
   * The emit path strips unknown, PII, and sensitive-elicited fields
   * before forwarding to the adapter.
   */
  extras: Record<string, unknown>;
}
