import { CfnKey, AwsDefault } from "../../config/cfn-keys.js";
import { RESOURCE_TYPES } from "../../config/resource-types.js";
import { IamEffect } from "../../config/iam-effects.js";
import {
  AwsServicePrincipal,
  IamAction,
  IamPolicy,
} from "../../config/aws-arns.js";
import { markerRef } from "../../config/marker-tokens.js";
import type { ArchitecturePattern } from "../types.js";
import { StaticWebsiteResourceId as R } from "../pattern-resource-ids.js";
import { PatternId } from "../pattern-ids.js";

/**
 * Static Website pattern — S3 bucket + CloudFront distribution with
 * Origin Access Control (OAC). Fully CCAPI end-to-end as of
 * (f) 2026-04-09 Task 4b; before that migration the CloudFront
 * distribution, OAC, and S3 bucket policy were created via direct
 * SDK calls in a post-provision hook (cloudfront-setup.ts).
 *
 * Resource order:
 *   1. website-bucket       — AWS::S3::Bucket (private, encrypted)
 *   2. cdn-oac              — AWS::CloudFront::OriginAccessControl
 *   3. cdn-distribution     — AWS::CloudFront::Distribution (depends on
 *                             the OAC Id via markerRef; the S3 origin
 *                             domain is synthesized from the bucket
 *                             name)
 *   4. bucket-policy        — AWS::S3::BucketPolicy (depends on the
 *                             distribution's ARN via markerRef; grants
 *                             cloudfront.amazonaws.com read access
 *                             scoped to aws:SourceArn)
 *
 * File upload (--source flag) still happens in the post-apply
 * result-formatter step AFTER all four CCAPI resources land, because
 * the upload is an application-level concern (user's HTML/CSS/JS),
 * not part of the infrastructure graph.
 */
export const staticWebsitePattern: ArchitecturePattern = {
  patternId: PatternId.STATIC_WEBSITE,
  displayName: "Static Website (S3 + CloudFront)",
  keywords: [
    "static website",
    "static site",
    "s3 cloudfront",
    "cdn website",
    "frontend hosting",
    "spa hosting",
  ],
  resourceList: [
    {
      resourceType: RESOURCE_TYPES.S3_BUCKET,
      resourceId: R.WEBSITE_BUCKET,
      displayName: "S3 Website Bucket",
    },
    {
      resourceType: RESOURCE_TYPES.CLOUDFRONT_ORIGIN_ACCESS_CONTROL,
      resourceId: R.CDN_OAC,
      displayName: "Origin Access Control",
    },
    {
      resourceType: RESOURCE_TYPES.CLOUDFRONT_DISTRIBUTION,
      resourceId: R.CDN_DISTRIBUTION,
      displayName: "CloudFront CDN (HTTPS)",
    },
    {
      resourceType: RESOURCE_TYPES.S3_BUCKET_POLICY,
      resourceId: R.BUCKET_POLICY,
      displayName: "S3 Bucket Policy (OAC read grant)",
    },
  ],
  dependencyOrder: [
    // Group 0: S3 bucket first — CloudFront's origin validation runs
    // immediately at CreateDistribution time, but S3 bucket DNS takes
    // a few seconds to propagate globally (us-east-1 global namespace).
    // Separating the bucket into its own group gives it 5-10s of
    // natural DNS propagation time while the OAC is created in group 1.
    [R.WEBSITE_BUCKET],
    // Group 1: OAC creation (~5-10s) acts as an implicit delay for
    // S3 DNS propagation before the distribution references the bucket.
    [R.CDN_OAC],
    [R.CDN_DISTRIBUTION],
    [R.BUCKET_POLICY],
  ],
  defaultOptions: {
    [R.WEBSITE_BUCKET]: {
      BucketEncryption: {
        ServerSideEncryptionConfiguration: [
          {
            ServerSideEncryptionByDefault: {
              SSEAlgorithm: AwsDefault.ENCRYPTION_AES256,
            },
          },
        ],
      },
      VersioningConfiguration: { Status: CfnKey.ENABLED },
      // Private bucket — OAC is the ONLY path to the content. Block
      // all public access so a misconfigured policy cannot accidentally
      // expose the bucket. This is the whole security premise of OAC.
      PublicAccessBlockConfiguration: {
        BlockPublicAcls: true,
        BlockPublicPolicy: true,
        IgnorePublicAcls: true,
        RestrictPublicBuckets: true,
      },
    },
    [R.CDN_OAC]: {
      OriginAccessControlConfig: {
        Name: "assignee-static-website-oac",
        Description: "OAC for assignee.ai static-website compound pattern",
        SigningProtocol: "sigv4",
        SigningBehavior: "always",
        OriginAccessControlOriginType: "s3",
      },
    },
    [R.CDN_DISTRIBUTION]: {
      DistributionConfig: {
        // 2026-04-12: CallerReference is NOT accepted by CCAPI for
        // AWS::CloudFront::Distribution — it's auto-generated by the
        // service. Including it triggers "extraneous key [CallerReference]
        // is not permitted". Removed.
        Comment: "Assignee.ai static website (S3 + OAC)",
        Enabled: true,
        DefaultRootObject: "index.html",
        PriceClass: "PriceClass_100",
        // 2026-04-12: CCAPI expects flat arrays for Origins,
        // CustomErrorResponses, and AllowedMethods — NOT the
        // {Quantity, Items} wrapper objects used by the SDK/REST API.
        // The previous implementation used the SDK shape and was
        // rejected with "expected type: JSONArray, found: JSONObject".
        Origins: [
          {
            Id: "S3Origin",
            // Use the regional S3 endpoint — the global s3.amazonaws.com
            // redirects but CloudFront rejects it for new buckets due to
            // DNS propagation delay. The regional endpoint resolves
            // immediately. The region is hardcoded to us-east-1 here
            // because the compound marker resolver only substitutes
            // resource IDs, not region values. A future improvement
            // could inject the configured region via a new marker type.
            // CloudFront CCAPI validates the S3 origin by bucket name.
            // The regional REST endpoint format is:
            //   <bucket>.s3.<region>.amazonaws.com
            // BUT the CCAPI model resolves the bucket name internally
            // when OriginAccessControlId is set — use the regional
            // endpoint WITHOUT the bucket name prefix, letting CCAPI
            // construct the full domain from the bucket identifier.
            DomainName: `${markerRef(R.WEBSITE_BUCKET)}.s3.amazonaws.com`,
            OriginAccessControlId: markerRef(R.CDN_OAC),
            S3OriginConfig: {
              OriginAccessIdentity: "",
            },
          },
        ],
        DefaultCacheBehavior: {
          TargetOriginId: "S3Origin",
          ViewerProtocolPolicy: "redirect-to-https",
          AllowedMethods: ["GET", "HEAD"],
          CachedMethods: ["GET", "HEAD"],
          // AWS-managed "CachingOptimized" policy — modern replacement
          // for the legacy ForwardedValues/MinTTL/DefaultTTL/MaxTTL
          // tuple. Using the managed policy id avoids shipping tuning
          // knobs that nobody in the static-website hot path wants to
          // touch at plan time.
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6",
          Compress: true,
        },
        // Single-page-app friendly: map 403 → index.html with 200.
        CustomErrorResponses: [
          {
            ErrorCode: 403,
            ResponsePagePath: "/index.html",
            // CCAPI expects integer, not string — "200" triggers
            // "expected type: Integer, found: String"
            ResponseCode: 200,
            ErrorCachingMinTTL: 10,
          },
        ],
      },
    },
    [R.BUCKET_POLICY]: {
      // BucketPolicy.Bucket is a marker ref to the bucket logical id
      // — resolves to the bucket's name at apply time. Note that the
      // S3::BucketPolicy CCAPI primaryIdentifier IS the bucket name,
      // so this doubles as both the cross-reference and the primary
      // identifier.
      Bucket: markerRef(R.WEBSITE_BUCKET),
      // The PolicyDocument grants read access to CloudFront service
      // principal, scoped by aws:SourceArn to the specific
      // distribution that will reference this bucket. The resolver
      // substitutes the full distribution ARN via markerRef
      // (buildResourceArn synthesizes the account-scoped global ARN
      // for CloudFront distributions — see arn-builder.ts).
      PolicyDocument: {
        Version: IamPolicy.VERSION,
        Statement: [
          {
            Sid: "AllowCloudFrontServicePrincipalReadOnly",
            Effect: IamEffect.ALLOW,
            Principal: {
              Service: AwsServicePrincipal.CLOUDFRONT,
            },
            Action: IamAction.S3_GET_OBJECT,
            // S3 object ARN — uses the resolved bucket name as the
            // resource segment. The compound resolver substitutes
            // markerRef(R.WEBSITE_BUCKET) with the real bucket name
            // before the policy hits CCAPI.
            Resource: `arn:aws:s3:::${markerRef(R.WEBSITE_BUCKET)}/*`,
            Condition: {
              StringEquals: {
                "aws:SourceArn": markerRef(R.CDN_DISTRIBUTION),
              },
            },
          },
        ],
      },
    },
  },
};
