/**
 * Keyword → CloudFormation-resource-type lookup tables used by the
 * classifier. Split into three ordered blocks so more-specific phrases
 * win against shorter substrings in the regular table.
 *
 * Order of precedence (first match wins within each block; blocks
 * evaluated in the order listed here):
 *   1. TASK_4B_PRIORITY_KEYWORDS — OAC + BucketPolicy
 *   2. COMPOUND_CROSS_REF_KEYWORDS — compound-dispatcher cross-refs
 *   3. KEYWORD_TO_RESOURCE_TYPE — general catalogue
 *
 * @see Story 20.4
 */

import { RESOURCE_TYPES } from "@assignee/core";
import type { KeywordEntry } from "./types.js";

/**
 * Maps natural language keywords to CloudFormation resource types.
 * Used for classifying the resource type from a description string.
 */
export const KEYWORD_TO_RESOURCE_TYPE: KeywordEntry[] = [
  {
    keywords: ["s3", "bucket", "object storage"],
    resourceType: RESOURCE_TYPES.S3_BUCKET,
  },
  {
    keywords: ["lambda", "serverless function", "function as a service"],
    resourceType: RESOURCE_TYPES.LAMBDA_FUNCTION,
  },
  {
    keywords: ["dynamodb", "dynamo", "nosql table"],
    resourceType: RESOURCE_TYPES.DYNAMODB_TABLE,
  },
  {
    keywords: ["ec2", "virtual machine", "compute instance"],
    resourceType: RESOURCE_TYPES.EC2_INSTANCE,
  },
  {
    keywords: ["rds", "relational database", "postgresql", "mysql", "aurora"],
    resourceType: RESOURCE_TYPES.RDS_DB_INSTANCE,
  },
  {
    keywords: ["sqs", "message queue", "queue service"],
    resourceType: RESOURCE_TYPES.SQS_QUEUE,
  },
  {
    keywords: ["sns", "notification", "pub/sub", "publish subscribe"],
    resourceType: RESOURCE_TYPES.SNS_TOPIC,
  },
  {
    keywords: ["iam role", "execution role", "service role"],
    resourceType: RESOURCE_TYPES.IAM_ROLE,
  },
  {
    keywords: ["ssm parameter", "parameter store", "systems manager parameter"],
    resourceType: RESOURCE_TYPES.SSM_PARAMETER,
  },
  {
    keywords: ["ecs", "container service", "fargate"],
    resourceType: RESOURCE_TYPES.ECS_CLUSTER,
  },
  {
    keywords: ["secrets manager", "secret", "credentials store"],
    resourceType: RESOURCE_TYPES.SECRETSMANAGER_SECRET,
  },
  {
    keywords: ["ecr", "container registry", "docker registry"],
    resourceType: RESOURCE_TYPES.ECR_REPOSITORY,
  },
  {
    keywords: ["vpc", "virtual private cloud"],
    resourceType: RESOURCE_TYPES.EC2_VPC,
  },
  {
    keywords: ["security group", "firewall"],
    resourceType: RESOURCE_TYPES.EC2_SECURITY_GROUP,
  },
  {
    keywords: [
      "load balancer",
      "application load balancer",
      "network load balancer",
      "elastic load balancer",
    ],
    resourceType: RESOURCE_TYPES.ELBV2_LOAD_BALANCER,
  },
  {
    keywords: ["subnet", "private subnet", "public subnet"],
    resourceType: RESOURCE_TYPES.EC2_SUBNET,
  },
  {
    keywords: ["route table", "routing table"],
    resourceType: RESOURCE_TYPES.EC2_ROUTE_TABLE,
  },
  {
    keywords: ["internet gateway", "igw"],
    resourceType: RESOURCE_TYPES.EC2_INTERNET_GATEWAY,
  },
  {
    keywords: ["nat gateway", "network address translation"],
    resourceType: RESOURCE_TYPES.EC2_NAT_GATEWAY,
  },
  {
    keywords: ["cloudwatch logs", "log group", "logging"],
    resourceType: RESOURCE_TYPES.LOGS_LOG_GROUP,
  },
  {
    keywords: ["api gateway", "http api", "websocket api"],
    resourceType: RESOURCE_TYPES.APIGATEWAYV2_API,
  },
  {
    keywords: ["cloudwatch alarm", "metric alarm", "monitoring alarm"],
    resourceType: RESOURCE_TYPES.CLOUDWATCH_ALARM,
  },
  {
    keywords: ["route", "network route"],
    resourceType: RESOURCE_TYPES.EC2_ROUTE,
  },
  {
    keywords: ["efs", "elastic file system", "nfs file system"],
    resourceType: RESOURCE_TYPES.EFS_FILE_SYSTEM,
  },
  {
    keywords: [
      "eventbridge rule",
      "event bridge rule",
      "events rule",
      "scheduled rule",
      "cron rule",
      "cloudwatch event rule",
    ],
    resourceType: RESOURCE_TYPES.EVENTS_RULE,
  },
  {
    keywords: [
      "eventbridge bus",
      "event bus",
      "custom event bus",
      "cross-account event bus",
      "saas partner event bus",
    ],
    resourceType: RESOURCE_TYPES.EVENTS_EVENT_BUS,
  },
  // A10 (2026-04-09): AWS::SNS::Subscription — classifier returns on
  // first match, so the "sns" keyword above would capture any "sns
  // subscription" phrase. Use unique multi-word phrases here; real
  // classification for subscriptions happens in the compound
  // cross-ref block which runs BEFORE this table.
  {
    keywords: ["subscription to sns topic", "sns topic subscription"],
    resourceType: RESOURCE_TYPES.SNS_SUBSCRIPTION,
  },
];

/**
 * WV4-A: compound cross-reference resources auto-generated by the
 * compound dispatcher (vpc-networking / three-tier-web patterns).
 * Matched BEFORE the regular table so multi-word phrases win against
 * shorter substrings (e.g. "vpc gateway attachment" must not be
 * classified as "vpc").
 */
export const COMPOUND_CROSS_REF_KEYWORDS: KeywordEntry[] = [
  {
    keywords: ["vpc gateway attachment", "vpcgatewayattachment"],
    resourceType: RESOURCE_TYPES.EC2_VPC_GATEWAY_ATTACHMENT,
  },
  {
    keywords: ["subnet route table association", "subnetroutetableassociation"],
    resourceType: RESOURCE_TYPES.EC2_SUBNET_ROUTE_TABLE_ASSOCIATION,
  },
  {
    keywords: ["efs mount target", "efsmounttarget"],
    resourceType: RESOURCE_TYPES.EFS_MOUNT_TARGET,
  },
  // A10: SNS Subscription — priority block so multi-word phrases win
  // against the bare "sns" keyword in the regular table.
  {
    keywords: [
      "sns subscription",
      "snssubscription",
      "topic subscription",
      "subscribe to topic",
      "subscribe to sns",
    ],
    resourceType: RESOURCE_TYPES.SNS_SUBSCRIPTION,
  },
  // 2026-04-14: RDS::DBSubnetGroup — priority block so "db subnet
  // group" wins against the bare "rds" keyword that would otherwise
  // classify it as RDS_DB_INSTANCE.
  {
    keywords: [
      "db subnet group",
      "dbsubnetgroup",
      "rds subnet group",
      "database subnet group",
    ],
    resourceType: RESOURCE_TYPES.RDS_DB_SUBNET_GROUP,
  },
  // A11 (2026-04-09): KMS::Key customer-managed-key classification.
  {
    keywords: [
      "kms key",
      "kmskey",
      "customer managed key",
      "customer-managed key",
      "cmk",
      "encryption key",
      "kms cmk",
    ],
    resourceType: RESOURCE_TYPES.KMS_KEY,
  },
  // A12 (2026-04-09): Events::Connection — unique phrases would
  // otherwise be subsumed by "eventbridge rule" or "event bus".
  {
    keywords: [
      "eventbridge connection",
      "events connection",
      "api connection",
      "webhook connection",
      "outbound api connection",
    ],
    resourceType: RESOURCE_TYPES.EVENTS_CONNECTION,
  },
  // A13 (2026-04-09): Events::ApiDestination — same priority-block
  // reasoning as EVENTS_CONNECTION.
  {
    keywords: [
      "api destination",
      "apidestination",
      "eventbridge destination",
      "outbound webhook",
      "webhook destination",
      "external api target",
    ],
    resourceType: RESOURCE_TYPES.EVENTS_API_DESTINATION,
  },
  // A14 (2026-04-09): CloudFront::Distribution — OAC entry in
  // TASK_4B_PRIORITY_KEYWORDS block runs first so "cloudfront oac"
  // wins against the plain "cloudfront" substring below.
  {
    keywords: [
      "cloudfront",
      "cloud front",
      "cdn",
      "content delivery network",
      "cloudfront distribution",
      "edge cache",
    ],
    resourceType: RESOURCE_TYPES.CLOUDFRONT_DISTRIBUTION,
  },
];

/**
 * (f) 2026-04-09 Task 4b: OAC + BucketPolicy priority block. Runs
 * BEFORE the main CloudFront block so more-specific phrases win
 * against bare "cloudfront" / "bucket".
 */
export const TASK_4B_PRIORITY_KEYWORDS: KeywordEntry[] = [
  {
    keywords: [
      "cloudfront origin access control",
      "cloudfront oac",
      "origin access control",
      "oac for cloudfront",
      "oac for s3",
    ],
    resourceType: RESOURCE_TYPES.CLOUDFRONT_ORIGIN_ACCESS_CONTROL,
  },
  {
    keywords: [
      "s3 bucket policy",
      "bucket policy",
      "s3 resource policy",
      "bucketpolicy",
    ],
    resourceType: RESOURCE_TYPES.S3_BUCKET_POLICY,
  },
];
